### PR TITLE
Command parsers: use exceptions for error handling #305

### LINKED ISSUE #305: Command parsers: use exceptions for error handling
The command parsers such as `AddCommandParser` can only define their `parse()` methods as follows:
```java
    public Command parse(String args) {
```
We would expect that an `AddCommandParser` would return an `AddCommand`, however `AddCommandParser#parse()` as currently implemented can only declare itself as returning a `Command`.

This is because the code currently abuses polymorphism to indicate errors by returning an `IncorrectCommand`. We could make our code more explicit by using exceptions instead.

### PR DESCRIPTION
**Pull request by yamgent**
Fixes #305.

Proposed merge commit message:

```
All CommandParser#parse(String) return a generic Command type, instead
of the specific command that they are tasked to parse (for example,
AddCommand for AddCommandParser).

This is because the methods might also return an IncorrectCommand if it
encounters a parse error. This causes an unnecessary loss of specificity
in the return value type if the parsing is successful (e.g. receiving a
Command object instead of an AddCommand object), and in the error info
if the parsing failed (e.g. receiving an IncorrectCommand instead of a
specific Exception object containing the exact stack trace).

Let's change all CommandParser#parse(String) methods to return their
specific command type, and throw a ParseErrorException instead when
encountering an error, to allow the caller to deal with it.
```

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@yamgent submitted v1 for review.

* [v1 1/3] [Add ParseErrorException](https://github.com/se-edu/addressbook-level4/pull/333/commits/407f726957233e212cae807ed5fc0e5f5fb9e806)
* [v1 2/3] [Modify all CommandParser\#parse\(String\) to throw ParseErrorException](https://github.com/se-edu/addressbook-level4/pull/333/commits/55bc7291cb91fab3c7161980448b607b4088f301)
* [v1 3/3] [Change CommandParser\#parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/351cd40b6b7e0e26db99ac4582384748bf0ef220)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/297506b87fabe6de6baa7901388039ec50199802...351cd40b6b7e0e26db99ac4582384748bf0ef220))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by PierceAndy** [comment]
I'm not sure referring to command parsers in general as `CommandParser` is a good practice, as that might imply that there is a `CommandParser` parent class.

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -17,11 +15,11 @@
      * Parses the given {@code String} of arguments in the context of the DeleteCommand
      * and returns an DeleteCommand object for execution.
      */
-    public Command parse(String args) {
+    public DeleteCommand parse(String args) throws ParseErrorException  {
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: Two many spaces.

File: src/main/java/seedu/address/logic/parser/ParseErrorException.java [hunk 2]
```diff
@@ -0,0 +1,10 @@
+package seedu.address.logic.parser;
+
+/**
+ * Represents a parse error encountered by a parser.
+ */
+public class ParseErrorException extends Exception {
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/ParseErrorException.java]: Why not just call it `ParseException`? Exceptions are supposed to only be used for errors anyway, so the `Error` is implied.

File: src/main/java/seedu/address/logic/parser/Parser.java [hunk 3]
```diff
@@ -42,37 +42,41 @@ public Command parseCommand(String userInput) {
...
+            case HelpCommand.COMMAND_WORD:
+                return new HelpCommand();
 
-        default:
-            return new IncorrectCommand(MESSAGE_UNKNOWN_COMMAND);
+            default:
+                return new IncorrectCommand(MESSAGE_UNKNOWN_COMMAND);
+            }
+        } catch (ParseErrorException parserException) {
+            return new IncorrectCommand(parserException.getMessage());
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/Parser.java]: Rather than catching it here, propagate it out instead? No reason why we have to go to the trouble of wrapping the exception into a command. We also lose some information as well (e.g. the stacktrace)

**Comment by CanIHasReview** [comment]
# v2

@yamgent submitted v2 for review.

* [v2 1/4] [Add ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/033ccebb6fc58bb38fdd447e411a9c6b557d4ee7)
* [v2 2/4] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/d707d30aae42aa3ab3def4063f95e546a095dcb4)
* [v2 3/4] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/55833fdd8e6a56a592f2800e3eb11af6cdb9bfba)
* [v2 4/4] [Modify Parser\#parseCommand\(String\) to not wrap ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/9b44ce95825acca175f89885e2b8e0fb98eeffd5)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/297506b87fabe6de6baa7901388039ec50199802...9b44ce95825acca175f89885e2b8e0fb98eeffd5)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/db0228687e2f1740b64a6408df504b48d90eaebd~1...db0228687e2f1740b64a6408df504b48d90eaebd))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/ParseException.java [hunk 4]
```diff
@@ -0,0 +1,10 @@
+package seedu.address.logic.parser;
```
Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/ParseException.java]: create a new sub package `seedu.address.logic.parser.exceptions` and put this exception in the package to be consistent with the others?

**Comment by CanIHasReview** [comment]
# v3

@yamgent submitted v3 for review.

* [v3 1/4] [Add ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/34bdd5a7a5177ddd672af7d84f47bbf16a993a04)
* [v3 2/4] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/6389de08bc4ccc86dd946bd68b744c675a5ef66d)
* [v3 3/4] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/f8c9df528fffe57398bbbacf9e8bbb3b76085bd9)
* [v3 4/4] [Modify Parser\#parseCommand\(String\) to not wrap ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/9fc413349c5c82ba992a2cb3edf32ace4c8eaa6d)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/297506b87fabe6de6baa7901388039ec50199802...9fc413349c5c82ba992a2cb3edf32ace4c8eaa6d)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/43b4a7a003e5f58cdb58eed2fdbbfc31e5f46ea1~1...43b4a7a003e5f58cdb58eed2fdbbfc31e5f46ea1))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/Parser.java [hunk 5]
```diff
@@ -42,37 +43,41 @@ public Command parseCommand(String userInput) {
 
         final String commandWord = matcher.group("commandWord");
         final String arguments = matcher.group("arguments");
-        switch (commandWord) {
+        try {
+            switch (commandWord) {
 
-        case AddCommand.COMMAND_WORD:
-            return new AddCommandParser().parse(arguments);
+            case AddCommand.COMMAND_WORD:
```
Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/Parser.java]: Is this change needed? Same for the others

Comment (yamgent) [inline src/main/java/seedu/address/logic/parser/Parser.java]: It is done this way because we would have to combine [v3 2/4] and [v3 4/4] together otherwise, but they are doing two different things.

These changes do not show up on the end diff.

File: src/main/java/seedu/address/ui/CommandBox.java [hunk 6]
```diff
@@ -54,6 +55,11 @@ private void handleCommandInputChanged() {
             setStyleToIndicateCommandFailure();
             logger.info("Invalid command: " + commandTextField.getText());
             raise(new NewResultAvailableEvent(e.getMessage()));
+        } catch (ParseException e) {
```
Comment (MightyCupcakes) [inline src/main/java/seedu/address/ui/CommandBox.java]: combine it like this if both handlers don't differ

```java

} catch (CommandException | ParseException e) {
    // ...
}

File: src/main/java/seedu/address/logic/parser/Parser.java (hunk 5 above)
Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/Parser.java]: I am referring to the indentation changes. Seems like you can leave the indentation alone and this commit will be much shorter

Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/Parser.java]: Okay, my bad.

Comment (PierceAndy) [inline src/main/java/seedu/address/logic/parser/Parser.java]: Is it not possible to rebase both [v3 2/4] and [v3 4/4] so that indentation changes changes don't appear?

Comment (yamgent) [inline src/main/java/seedu/address/logic/parser/Parser.java]: Not sure what you meant by that... the indentation is intentional because of the addition of the try/catch block.

Comment (PierceAndy) [inline src/main/java/seedu/address/logic/parser/Parser.java]: Oops, you're right. Please disregard my point.

**Comment by CanIHasReview** [comment]
# v4

@yamgent submitted v4 for review.

* [v4 1/4] [Add ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/8b3350126f3017b7abb90b875edd2c2d8b65884d)
* [v4 2/4] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/e4ac5a4fdd707b56164b18f56a0bf34e9993afdc)
* [v4 3/4] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/b4be09e2a5c6b6c9f450dc157df7724ec633e3ce)
* [v4 4/4] [Modify Parser\#parseCommand\(String\) to not wrap ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/cf9943c45c1a2d935337b9b978e0dfb48fc1172c)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/297506b87fabe6de6baa7901388039ec50199802...cf9943c45c1a2d935337b9b978e0dfb48fc1172c)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level4/compare/08a03622cde2662f29160284c0b866d14139192e~1...08a03622cde2662f29160284c0b866d14139192e))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 7]
```diff
@@ -124,27 +124,43 @@ private void assertCommandSuccess(String inputCommand, String expectedMessage,
...
+        AddressBook expectedAddressBook = new AddressBook(model.getAddressBook());
+        List<ReadOnlyPerson> expectedShownList = new ArrayList<>(model.getFilteredPersonList());
+        assertCommandBehavior(ParseException.class, inputCommand, expectedMessage, expectedAddressBook,
+                expectedShownList);
     }
 
     /**
      * Executes the command, confirms that the result message is correct
-     * and that a CommandException is thrown if expected
+     * and that a specific Exception is thrown if expected
```
Comment (MightyCupcakes) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: `and that the expected Exception is thrown.`

**Comment by yamgent** [comment]
@PierceAndy May I have your review for this iteration?

**Comment by CanIHasReview** [comment]
# v5

@yamgent submitted v5 for review.

* [v5 1/4] [Add ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/f966983d4d7b789b5e968949a859f0305e190465)
* [v5 2/4] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/2cc6d61932d7841381aae6ffdb833459a9ae255a)
* [v5 3/4] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/ac4916a23072075c61be17fad15abaaac823ba04)
* [v5 4/4] [Modify Parser\#parseCommand\(String\) to not wrap ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/e806fad89fd927adecb4098665233f3ba0f0748b)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/f5efb728b72c193913006d96d4d5591da810af50...e806fad89fd927adecb4098665233f3ba0f0748b)) ([:chart_with_upwards_trend: Interdiff between v4 and v5](https://github.com/se-edu/addressbook-level4/compare/d38b994cd4952764dd5834201767f587f43ffc67~1...d38b994cd4952764dd5834201767f587f43ffc67))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/5/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v6

@yamgent submitted v6 for review.

* [v6 1/4] [Add ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/0cd1cf6b119c483126260f8b6387cfb5b135f3b1)
* [v6 2/4] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/ac3974e56dac3d3e6e2ce3c95ca30ead08082573)
* [v6 3/4] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/842108e3497b601dd28d4175d0b5a2b1c93e4950)
* [v6 4/4] [Modify Parser\#parseCommand\(String\) to not wrap ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/e0b7a2126bcc93ba932732e9a7466b9e1da036c5)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/4c4e1ed78fd8465512c5b434a3c592da52740717...e0b7a2126bcc93ba932732e9a7466b9e1da036c5)) ([:chart_with_upwards_trend: Interdiff between v5 and v6](https://github.com/se-edu/addressbook-level4/compare/c6fe305fcf4f04b5831a490c39416b2d909c71da~1...c6fe305fcf4f04b5831a490c39416b2d909c71da))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/6/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 8]
```diff
@@ -19,7 +18,7 @@
      * Parses the given {@code String} of arguments in the context of the FindCommand
      * and returns an FindCommand object for execution.
```
Comment (damithc) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java]: Typo here: `an` (same typo in some other places). FirstTimer issue?

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 9]
```diff
@@ -129,27 +129,43 @@ private void assertCommandSuccess(String inputCommand, String expectedMessage,
...
+     * and that the expected Exception is thrown.
      * and also confirms that the following three parts of the LogicManager object's state are as expected:<br>
      *      - the internal address book data are same as those in the {@code expectedAddressBook} <br>
      *      - the backing list shown by UI matches the {@code shownList} <br>
      *      - {@code expectedAddressBook} was saved to the storage file. <br>
      */
-    private void assertCommandBehavior(boolean isCommandExceptionExpected, String inputCommand, String expectedMessage,
-                                       ReadOnlyAddressBook expectedAddressBook,
-                                       List<? extends ReadOnlyPerson> expectedShownList) {
+    private <T> void assertCommandBehavior(Class<T> expectedException,
```
Comment (damithc) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: I wonder if we should use Optional here (instead of using null to signal 'no exception expected')

Comment (yamgent) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: Yes, that would make the intention clearer. Will try it out.

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java (hunk 8 above)
Comment (yamgent) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java]: Created #357.

File: src/test/java/seedu/address/logic/LogicManagerTest.java (hunk 9 above)
Comment (damithc) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: Optinal is meant to be used mostly as a return value. So read up a bit about pros and cons about using Optionals as parameters before deciding.

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 10]
```diff
@@ -129,27 +129,43 @@ private void assertCommandSuccess(String inputCommand, String expectedMessage,
...
+        AddressBook expectedAddressBook = new AddressBook(model.getAddressBook());
+        List<ReadOnlyPerson> expectedShownList = new ArrayList<>(model.getFilteredPersonList());
+        assertCommandBehavior(ParseException.class, inputCommand, expectedMessage, expectedAddressBook,
+                expectedShownList);
     }
 
     /**
      * Executes the command, confirms that the result message is correct
-     * and that a CommandException is thrown if expected
+     * and that the expected Exception is thrown.
```
Comment (PierceAndy) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: Can merge with previous line?

**Comment by CanIHasReview** [comment]
# v7

@yamgent submitted v7 for review.

* [v7 1/4] [Add ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/afd317ec64e007abda5fde2e32c35a2fb15a3995)
* [v7 2/4] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/481af3bb09f1525d066431d68b886413e44a5a55)
* [v7 3/4] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/c260b99a096ec0f7682f1fb99d9f8381b18cf21f)
* [v7 4/4] [Modify Parser\#parseCommand\(String\) to not wrap ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/756affaaac707e2cb91609c3175e4aee7904b495)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/dc9fe96a38a2b5f9bb5bb4c05c3ff1db47b1effd...756affaaac707e2cb91609c3175e4aee7904b495)) ([:chart_with_upwards_trend: Interdiff between v6 and v7](https://github.com/se-edu/addressbook-level4/compare/18a96a1ff9758e2240abda5448f92e5fc87ee614~1...18a96a1ff9758e2240abda5448f92e5fc87ee614))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/7/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 11]
```diff
@@ -130,27 +130,42 @@ private void assertCommandSuccess(String inputCommand, String expectedMessage,
...
+     * Executes the command, confirms that a ParseException is thrown and that the result message is correct.
+     * Both the 'address book' and the 'last shown list' are verified to be unchanged.
+     * @see #assertCommandBehavior(boolean, String, String, ReadOnlyAddressBook, List)
+     */
+    private void assertParseFailure(String inputCommand, String expectedMessage) {
+        AddressBook expectedAddressBook = new AddressBook(model.getAddressBook());
+        List<ReadOnlyPerson> expectedShownList = new ArrayList<>(model.getFilteredPersonList());
+        assertCommandBehavior(ParseException.class, inputCommand, expectedMessage, expectedAddressBook,
+                expectedShownList);
+    }
```
Comment (damithc) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: There is some duplication between these two methods. May be extract a `assertFailure(Exception, String, String)` method?

File: src/main/java/seedu/address/logic/parser/exceptions/ParseException.java [hunk 12]
```diff
@@ -0,0 +1,10 @@
+package seedu.address.logic.parser.exceptions;
```
Comment (damithc) [inline src/main/java/seedu/address/logic/parser/exceptions/ParseException.java]: Commit 1 can be merged with commit 2?

These two has some duplication.

>All command parsers return an IncorrectCommand object when they
encounter a parse error.
>
>This error handling behavior is not explicit. Instead of throwing an
exception as expected, a child class object (IncorrectCommand) of the
return type (Command) is returned.

How about this?
```
All command parsers return an IncorrectCommand object when they
encounter a parse error.

The parse error can be made more visible if an exception was thrown 
instead.
```

**Comment by CanIHasReview** [comment]
# v8

@yamgent submitted v8 for review.

* [v8 1/3] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/c5489286a0476daaa308ccebc6a26ff1f999a127)
* [v8 2/3] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/a1b9b117cd93fb94f54ba9494cf613ecc6ccf84b)
* [v8 3/3] [Modify Parser\#parseCommand\(String\) to not wrap ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/c007dda76b3ed2484789b366cb2f5745c870a901)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/a5d9fcc4cce6b798663a565091e38782d140b7e7...c007dda76b3ed2484789b366cb2f5745c870a901)) ([:chart_with_upwards_trend: Interdiff between v7 and v8](https://github.com/se-edu/addressbook-level4/compare/0241a278af061f8381b9f5a8797402eda3505f23~1...0241a278af061f8381b9f5a8797402eda3505f23))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/8/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 13]
```diff
@@ -108,49 +108,50 @@ public void tearDown() {
...
     }
 
     /**
-     * Executes the command, confirms that a CommandException is thrown and that the result message is correct.
+     * Executes the command, confirms that the exception is thrown and that the result message is correct.
      * Both the 'address book' and the 'last shown list' are verified to be unchanged.
      * @see #assertCommandBehavior(boolean, String, String, ReadOnlyAddressBook, List)
      */
-    private void assertCommandFailure(String inputCommand, String expectedMessage) {
+    private <T> void assertFailure(String inputCommand, Class<T> expectedException, String expectedMessage) {
```
Comment (damithc) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: `assertCommandFailure` (to be symmetric)?

**Comment by CanIHasReview** [comment]
# v9

@yamgent submitted v9 for review.

* [v9 1/3] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/c5489286a0476daaa308ccebc6a26ff1f999a127)
* [v9 2/3] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/a1b9b117cd93fb94f54ba9494cf613ecc6ccf84b)
* [v9 3/3] [Modify Parser\#parseCommand\(String\) to not wrap ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/e10d3ebfb11efaad984615d0e389b2ed34d87241)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/a5d9fcc4cce6b798663a565091e38782d140b7e7...e10d3ebfb11efaad984615d0e389b2ed34d87241)) ([:chart_with_upwards_trend: Interdiff between v8 and v9](https://github.com/se-edu/addressbook-level4/compare/2af820ff1e07508e5d44728fee2b4e1148ff8cd1~1...2af820ff1e07508e5d44728fee2b4e1148ff8cd1))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/9/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 14]
```diff
@@ -108,49 +108,50 @@ public void tearDown() {
...
      * Both the 'address book' and the 'last shown list' are verified to be unchanged.
      * @see #assertCommandBehavior(boolean, String, String, ReadOnlyAddressBook, List)
      */
-    private void assertCommandFailure(String inputCommand, String expectedMessage) {
+    private <T> void assertCommandFailure(String inputCommand, Class<T> expectedException, String expectedMessage) {
         AddressBook expectedAddressBook = new AddressBook(model.getAddressBook());
         List<ReadOnlyPerson> expectedShownList = new ArrayList<>(model.getFilteredPersonList());
-        assertCommandBehavior(true, inputCommand, expectedMessage, expectedAddressBook, expectedShownList);
+        assertCommandBehavior(expectedException, inputCommand, expectedMessage, expectedAddressBook,
+                expectedShownList);
```
Comment (damithc) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: What do you think of adding two convenience methods like this? It might reduce the verbosity of the test cases.
```java
private void assertCommandException(String inputCommand, String expectedMessage) {
    assertCommandFailure(inputCommand, CommandException.class, expectedMessage) ;
}

private void assertParseException(String inputCommand, String expectedMessage) {
    assertCommandFailure(inputCommand, ParseException.class, expectedMessage) ;
}
```

Comment (yamgent) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: Good point, will add the two convenience methods.

**Comment by CanIHasReview** [comment]
# v10

@yamgent submitted v10 for review.

* [v10 1/3] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/c5489286a0476daaa308ccebc6a26ff1f999a127)
* [v10 2/3] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/a1b9b117cd93fb94f54ba9494cf613ecc6ccf84b)
* [v10 3/3] [Modify Parser\#parseCommand\(String\) to not wrap ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/2c7fec3f732df7ec86b24c343227f3fba21e99f9)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/a5d9fcc4cce6b798663a565091e38782d140b7e7...2c7fec3f732df7ec86b24c343227f3fba21e99f9)) ([:chart_with_upwards_trend: Interdiff between v9 and v10](https://github.com/se-edu/addressbook-level4/compare/9ba7ad4dc19de115f49e8b880bf0d5cf5ac33fa2~1...9ba7ad4dc19de115f49e8b880bf0d5cf5ac33fa2))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/10/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
@yamgent please request a review from those who approved earlier than the recent changes.

File: src/main/java/seedu/address/logic/parser/Parser.java (hunk 3 above)
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/Parser.java]: Reading further through the diff, however, I see that this commit still punts out at returning an `IncorrectCommand`, which is strange since the commit message promised me that all command parsers would now throw a `ParseException`? Unless `Parser` is not considered a command parser?

**Comment by pyokagan** [comment]
Do we also need to add a `@throws ParseException` in all the relevant javadocs as well?

File: src/main/java/seedu/address/logic/parser/exceptions/ParseException.java [hunk 15]
```diff
@@ -0,0 +1,10 @@
...
+
+/**
+ * Represents a parse error encountered by a parser.
+ */
+public class ParseException extends Exception {
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/exceptions/ParseException.java]: Should this extend `IllegalValueException`? Looking through the code base, it seems that we throw `IllegalValueException` for things like invalid phone numbers, so "invalid command input" might also fit into that, I think.

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 16]
```diff
@@ -108,49 +108,68 @@ public void tearDown() {
...
     }
 
     /**
-     * Executes the command, confirms that the result message is correct
-     * and that a CommandException is thrown if expected
+     * Executes the command, confirms that the result message is correct and that the expected Exception is thrown,
```
Comment (pyokagan) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: `Exception` -> `exception`.

**Comment by pyokagan** [comment]
> Which does make me wonder if they should be the same commit. I don't have a strong preference for this, but if you want them to be separate please add in a paragraph to [1/3] 

To add on, [1/3] and [3/3] should be grouped together (come directly one after another) since they have a strong coupling with each other.

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 17]
```diff
@@ -108,49 +108,68 @@ public void tearDown() {
...
+     * Executes the command, confirms that the parse exception is thrown and that the result message is correct.
+     * Both the 'address book' and the 'last shown list' are verified to be unchanged.
+     * @see #assertCommandBehavior(boolean, String, String, ReadOnlyAddressBook, List)
+     */
+    private void assertParseException(String inputCommand, String expectedMessage) {
+        assertCommandFailure(inputCommand, ParseException.class, expectedMessage);
+    }
+
+    /**
+     * Executes the command, confirms that the exception is thrown and that the result message is correct.
```
Comment (pyokagan) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: Okay, on second thought lots of javadocs in the file are already following the same pattern, so let's not rock the boat :-P

**Comment by CanIHasReview** [comment]
# v11

@yamgent submitted v11 for review.

* [v11 1/2] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/400ce4481cb8d60ce80e3505a2dd42d72675dac5)
* [v11 2/2] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/4a141fe8621ccf681666329f79048cfd75c9e0e9)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/8e4d306e4cc579b4e967b267a3c41aafcedbc700...4a141fe8621ccf681666329f79048cfd75c9e0e9)) ([:chart_with_upwards_trend: Interdiff between v10 and v11](https://github.com/se-edu/addressbook-level4/compare/20ccdf1a3b5653509d0d3fcff34e7c9a29a1d73e~1...20ccdf1a3b5653509d0d3fcff34e7c9a29a1d73e))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/11/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 18]
```diff
@@ -49,7 +50,7 @@ public Command parse(String args) {
 
             return new AddCommand(person);
         } catch (IllegalValueException ive) {
-            return new IncorrectCommand(ive.getMessage());
+            throw new ParseException(ive.getMessage());
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: This `ParseException` is thrown in response to the thrown `IllegalValueException`, so introduce an alternate `ParseException(Throwable cause)` constructor and use that instead?

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 19]
```diff
@@ -47,11 +48,11 @@ public Command parse(String args) {
             editPersonDescriptor.setAddress(ParserUtil.parseAddress(argMultimap.getValue(PREFIX_ADDRESS)));
             editPersonDescriptor.setTags(parseTagsForEdit(argMultimap.getAllValues(PREFIX_TAG)));
         } catch (IllegalValueException ive) {
-            return new IncorrectCommand(ive.getMessage());
+            throw new ParseException(ive.getMessage());
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java]: Same here.

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java (hunk 18 above)
Comment (yamgent) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Unfortunately since `ParseException` is inherited from `IllegalValueException`, we lost the ability to set the underlying cause (The `Exception` class has `public Exception(Throwable cause)`, but it is not available via `IllegalValueException`).

Allowing `IllegalValueException` to accept a `cause` seems to be weird (unless we are okay with writing `NameValidationException`, `AddressValidationException`, etc :P), so perhaps the alternative is to avoid inheriting from `IllegalValueException`?

Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: @yamgent 
> Allowing IllegalValueException to accept a cause seems to be weird (unless we are okay with writing NameValidationException, AddressValidationException, etc :P), so perhaps the alternative is to avoid inheriting from IllegalValueException?

Huh? What does exception chaining, which is idiomatic Java, got to do with naming?

Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: > What does exception chaining, which is idiomatic Java, got to do with naming?

The reason why we would want to set the `IllegalValueException` as the cause of the `ParseException` is so that its information (e.g. stacktrace) would not be lost, which fits with one of the goals of the commit, no?

**Comment by CanIHasReview** [comment]
# v12

@yamgent submitted v12 for review.

* [v12 1/2] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/4cfb285f78b7f7235dde31efe768eaff3afafad3)
* [v12 2/2] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/d07c465c574ff7b7550c299c30c06f3acd980389)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/8e4d306e4cc579b4e967b267a3c41aafcedbc700...d07c465c574ff7b7550c299c30c06f3acd980389)) ([:chart_with_upwards_trend: Interdiff between v11 and v12](https://github.com/se-edu/addressbook-level4/compare/5ff7db037a6e4a55f41997fcbcd21c3372c0ce1d~1...5ff7db037a6e4a55f41997fcbcd21c3372c0ce1d))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/12/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
Merge commit message:
>However, this behavior is not explicit, as
the CommandParsers are expected to only deal with the type that they
are tasked to parse (for example, the AddCommandParser is expected to
return an AddCommand, and nothing else). This also means that the
caller of the methods are unable to handle parse errors themselves.

Would this be better?
```
This causes an unnecessary loss of specificity in the return value type 
if the parsing is successful (e.g. receiving a Command object instead 
of an AddCommand object), and in the error info if the parsing failed
(e.g. receiving an IncorrectCommand instead of a specific Exception object
containing the exact stack trace).
```

**Comment by CanIHasReview** [comment]
# v13

@yamgent submitted v13 for review.

* [v13 1/2] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/7a1a7b6b40589926fd633c58ab1bf6fac246f33b)
* [v13 2/2] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/100358f28739044138251314e06309583ac83f38)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/ef06553753b5073c012ccac9ab1082c46b9d0f51...100358f28739044138251314e06309583ac83f38)) ([:chart_with_upwards_trend: Interdiff between v12 and v13](https://github.com/se-edu/addressbook-level4/compare/f137bff9415f54c2d80bfebc70e8aa0e0124ffcc~1...f137bff9415f54c2d80bfebc70e8aa0e0124ffcc))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/13/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by yamgent** [comment]
@damithc De-conflicted and also updated the merge commit message.

**Comment by CanIHasReview** [comment]
# v14

@yamgent submitted v14 for review.

* [v14 1/2] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/58bd7e0bb68739a17b6f6a8cc82e5929af9518ca)
* [v14 2/2] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/a048bf4e86477526c0136cbbde7150b13c4efbd6)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/cc22ed642b34f15798facec1bddd597aa8c0c395...a048bf4e86477526c0136cbbde7150b13c4efbd6)) ([:chart_with_upwards_trend: Interdiff between v13 and v14](https://github.com/se-edu/addressbook-level4/compare/278f16ef7a7eccca3f3b62e28cd446d8271386ae~1...278f16ef7a7eccca3f3b62e28cd446d8271386ae))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/14/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by yamgent** [comment]
Changes have to be made because `EditCommandParserTest` could not compile on this PR.

**Comment by CanIHasReview** [comment]
# v15

@yamgent submitted v15 for review.

* [v15 1/3] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/d38a57e6a84b72be5299900fcfd49646c3487384)
* [v15 2/3] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/8124f0bc6d907b246ec33cf0986a5dd9eead906b)
* [v15 3/3] [Remove IncorrectCommand](https://github.com/se-edu/addressbook-level4/pull/333/commits/caa9861166a93fc3fc63d3482a126c31c57a1f2c)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/cc22ed642b34f15798facec1bddd597aa8c0c395...caa9861166a93fc3fc63d3482a126c31c57a1f2c)) ([:chart_with_upwards_trend: Interdiff between v14 and v15](https://github.com/se-edu/addressbook-level4/compare/178aef74f90a12267b20bd562296e201960af12a~1...178aef74f90a12267b20bd562296e201960af12a))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/15/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by yamgent** [comment]
@damithc I removed `IncorrectCommand` for this iteration, need you to take a look at it again to approve the new design decision.

**Comment by CanIHasReview** [comment]
# v16

@yamgent submitted v16 for review.

* [v16 1/3] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/3acaf025fc39b265ace038d3802ff2926ac004d3)
* [v16 2/3] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/dd26832289612eaad9eeb63288a4d4cb017ed700)
* [v16 3/3] [Remove IncorrectCommand](https://github.com/se-edu/addressbook-level4/pull/333/commits/76c4505e11fe449e7910b78982f3ea12d3d4c5cf)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/6af393367c998910784881146ffa049725bc31bd...76c4505e11fe449e7910b78982f3ea12d3d4c5cf)) ([:chart_with_upwards_trend: Interdiff between v15 and v16](https://github.com/se-edu/addressbook-level4/compare/5d742102cf461ee1bd559d0e750eabd0467d7525~1...5d742102cf461ee1bd559d0e750eabd0467d7525))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/16/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by yamgent** [comment]
v16: Rebased

@damithc Just a reminder for the review. :)

**Comment by CanIHasReview** [comment]
# v17

@yamgent submitted v17 for review.

* [v17 1/3] [Modify all command parsers' parse\(String\) to throw ParseException](https://github.com/se-edu/addressbook-level4/pull/333/commits/621ede40779fe60058157430eef0db3e54bfa1aa)
* [v17 2/3] [Change command parsers' parse\(String\) return type to be more specific](https://github.com/se-edu/addressbook-level4/pull/333/commits/64eab5d850926fba45d8f3a759adbd9410119f3e)
* [v17 3/3] [Remove IncorrectCommand](https://github.com/se-edu/addressbook-level4/pull/333/commits/3b626bba65bb34231fe2e11ab5504073efddde13)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/015b57d6ae29042e4281de6a644a0a2f950f418a...3b626bba65bb34231fe2e11ab5504073efddde13)) ([:chart_with_upwards_trend: Interdiff between v16 and v17](https://github.com/se-edu/addressbook-level4/compare/bd63e0eb30b94b1b5bc42f3b7884a6bb291c7b5d~1...bd63e0eb30b94b1b5bc42f3b7884a6bb291c7b5d))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/333/17/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>
