### PR TITLE
Issue with undo/redo and modifications to filtered lists #737

### LINKED ISSUE #737: Issue with undo/redo and modifications to filtered lists
The following code sequence:
Find "Al"
Delete 1
List
Undo
Redo

deletes the wrong person after it is in the full unfiltered list. Can this be considered a bug?

### PR DESCRIPTION
**Pull request by yamidark**
Fixes #737 

EditCommand and DeleteCommand stores the target index of the person to edit
or delete respectively.

As a result, redoing of these index-based commands will be executed on the incorrect
person due to different indexing in differing views.

Let's update EditCommand and DeleteCommand to find and store the personToEdit
or personToDelete respectively before it's first execution. This ensures that future
execution of the same command will be on the correct person.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 1]
```diff
@@ -4,15 +4,19 @@
...
 import seedu.address.model.AddressBook;
 import seedu.address.model.ReadOnlyAddressBook;
+import seedu.address.model.person.ReadOnlyPerson;
 
 /**
  * Represents a command which can be undone and redone.
  */
 public abstract class UndoableCommand extends Command {
     private ReadOnlyAddressBook previousAddressBook;
+    private Predicate<ReadOnlyPerson> previousPredicate;
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: Over here you are only storing 1 predicate. However, there may be more complex buggy cases.
Suppose that there's 5 people in the list.
```
A
B
C
D
E
```

1. `find A C`
```
A
C
```

2. `edit 2 n/C BUGGY`
```
A
B 
C BUGGY
D
E
```

3. `find D E`
```
D
E
```

4. `edit 2 n/E BUGGY`
```
A
B
C BUGGY
D
E BUGGY
```

5. `undo` `undo`
```
A
B
C
D
E
```

6. `redo` // first bug
```
A
C BUGGY
C
D
E
```

7. `redo` // second bug
```
A
E BUGGY
C
D
E
```

As such, I don't think you can only store the previous Predicate using this algorithm.

**Comment by Zhiyuan-Amos** [comment]
I'm thinking of an alternate algorithm as suggested in https://github.com/se-edu/addressbook-level4/issues/737#issuecomment-345574057.

`EditCommand` stores an `Index` and `EditPersonDescriptor`. Instead, let's store the `Person` at the particular index, and the `EditPersonDescriptor`.

`DeleteCommand` stores an `Index`. Instead, let's store the `Person` at the index.

That way, whenever you redo, you will be editing/deleting that particular person, and there's no need to consider both indices & the current predicate / view anymore.

**Comment by yamidark** [comment]
Yes, that alternate algorithm seems to be a cleaner way of resolving this bug.

Will start working on it.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 1 above)
Comment (pyokagan) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: Can't reproduce this bug on my machine.

Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: ... Forgot to change branch before doing this, sorry!

@pyokagan which way of resolving this issue seems cleaner to you? This one or https://github.com/se-edu/addressbook-level4/issues/737#issuecomment-345574057?

**Comment by Zhiyuan-Amos** [comment]
@yamidark sorry for the false alarm in https://github.com/se-edu/addressbook-level4/pull/792#discussion_r160830371! :(

**Comment by yamidark** [comment]
@Zhiyuan-Amos  Nah, I should have done the check and confirmed the bug myself too.

So should I work on using https://github.com/se-edu/addressbook-level4/issues/737#issuecomment-345574057 or continue with the current method?

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 1 above)
Comment (pyokagan) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: > which way of resolving this issue seems cleaner to you? This one or #737 (comment)?

Don't have time to look into it fully, but my initial intuition is that #737 (comment) will be clunkier as the retrieval of the person to be recorded down for future redos can't be implemented in `UndoableCommand#execute()`, since UndoableCommand is not aware of what index(es) the command uses.

**Comment by Zhiyuan-Amos** [comment]
Hmm after thinking further about it, I'm not too sure. Iirc, the developer team was thinking of making all commands undoable. I.e. if I execute: `find A` followed by `list`, then I execute `undo`, I will see the result of `find A`.

In this case, by having `UndoableCommand` store a `previousPredicate`, this new feature can be easily supported in the future.

But specifically for this PR, I noticed that you will have to call `model.updateFilteredPersonList(previousPredicate)` whenever you call `redo()`. So there's an unintended side effect that the view will be refreshed for a split second due to the change of the predicate, though it's not much of an issue now since you can't really see it because it happens very quickly.

The plus point of using the solution [here](https://github.com/se-edu/addressbook-level4/issues/737#issuecomment-345574057) is that there's no need to call `model.updateFilteredPersonList(previousPredicate)` whenever you call `redo()`; redoing works fine regardless of the state of the filtered list. That way, we solve the issue just by tweaking the `Logic` component alone, instead of having to couple it a little with the `Model` component.

@damithc Prof, what do you think?

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 

> So there's an unintended side effect that the view will be refreshed for a split second due to the change of the predicate, though it's not much of an issue now since you can't really see it because it happens very quickly.

I don't think that's true. A UI framework which re-renders on every trivial change of the model would lead to extremely bad performance. From what I can tell, JavaFX will only re-render once the application thread yields control to the event loop. In other words, if we run a command that gets stuck in an infinite loop, the UI won't update at all.

But this prompts me to the fact that *performance* could also be a factor to consider as well. So, I started to do some simple benchmarks with a large addressbook, only to find an old performance regression instead :-P Issue coming soon.

Anyway, I don't mind using another approach. I don't really have a horse in this race, and this is my last post on this matter.

**Comment by Zhiyuan-Amos** [comment]
> I don't think that's true. A UI framework which re-renders on every trivial change of the model would lead to extremely bad performance. From what I can tell, JavaFX will only re-render once the application thread yields control to the event loop. In other words, if we run a command that gets stuck in an infinite loop, the UI won't update at all.

Wow that's insightful, thanks Paul ^^

@yamidark can you try doing the next iteration just by updating `EditCommand` & `DeleteCommand` alone? Would like to see whether this implementation is indeed simpler or not. Tq ^^

**Comment by Zhiyuan-Amos** [comment]
@yamidark seems like the first iteration looks way neater because there's no need to store the boolean flags. 

Thanks for your second iteration! :) You can revert back to your first iteration's code, update commit [2/3] as per https://github.com/se-edu/addressbook-level4/pull/792#pullrequestreview-88016194 and submit the 3rd iteration.

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java [hunk 2]
```diff
@@ -148,6 +154,9 @@ public void addPerson(ReadOnlyPerson person) throws DuplicatePersonException {
         public ReadOnlyAddressBook getAddressBook() {
             return new AddressBook();
         }
+
+        @Override
+        public Predicate<ReadOnlyPerson> getFilteredPersonListPredicate() { return PREDICATE_SHOW_ALL_PERSONS; }
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/AddCommandTest.java]: Is there a reason why you put this method here instead of putting it in `ModelStub`, just like for `getFilteredPersonListPredicate()`?

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java [hunk 3]
```diff
@@ -165,6 +174,9 @@ public void addPerson(ReadOnlyPerson person) throws DuplicatePersonException {
...
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/AddCommandTest.java]: same as above ^^

File: src/main/java/seedu/address/model/ModelManager.java [hunk 4]
```diff
@@ -92,6 +92,11 @@ public void updatePerson(ReadOnlyPerson target, ReadOnlyPerson editedPerson)
         return FXCollections.unmodifiableObservableList(filteredPersons);
     }
 
+    @Override
+    public Predicate<ReadOnlyPerson> getFilteredPersonListPredicate() {
+        return (Predicate<ReadOnlyPerson>) filteredPersons.getPredicate();
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/model/ModelManager.java]: Since this method may return null, we should specify it in the header comments what does ` null` return means.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 5]
```diff
@@ -4,15 +4,20 @@
...
 import seedu.address.model.AddressBook;
 import seedu.address.model.ReadOnlyAddressBook;
+import seedu.address.model.person.ReadOnlyPerson;
 
 /**
  * Represents a command which can be undone and redone.
  */
 public abstract class UndoableCommand extends Command {
     private ReadOnlyAddressBook previousAddressBook;
+    private Optional<Predicate<ReadOnlyPerson>> previousPredicate = Optional.empty();
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: shouldn't use `Optional` as a field in classes :P `previousPredicate` can be of type `Predicate<ReadOnlyPerson>`. 

I'm thinking that for `ModelManager#getFilteredPersonListPredicate()`, because `FilteredList#getPredicate()` returns `null` if there's no `Predicate`, so what we can do is (make this code neater, i just typed it out quickly :P):
```
if (filteredPersons.getPredicate() == null) {
    return PREDICATE_SHOW_ALL_PERSONS;
} else {
    return (Predicate<ReadOnlyPerson>) filteredPersons.getPredicate();
}
```

This way, you don't have to deal with a `null` return.

That way, in `UndoableCommand#redo()`, you can simply:
```
model.updateFilteredPersonList(previousPredicate);
```

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 6]
```diff
@@ -42,6 +54,7 @@ protected final void undo() {
     protected final void redo() {
         requireNonNull(model);
         try {
+            previousPredicate.ifPresent(model::updateFilteredPersonList);
```
Comment (eugenepeh) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: btw @Zhiyuan-Amos , in the case where the state is used in both undo and redo, wouldn't it be confusing to have "previous" prefix in variable names?

**Comment by Zhiyuan-Amos** [comment]
> E.g. if I perform find John then find Mary, undo'ing find Mary will show all people again?
> btw @Zhiyuan-Amos , in the case where the state is used in both undo and redo, wouldn't it be confusing to have "previous" prefix in variable names?

If I'm reading you correctly, you're saying that `model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)` in `undo()` should be changed to `model.updateFilteredPersonList(previousPredicate)`?  Yup, in that case, the "previous" prefix can be confusing.

Though I'm not sure whether we should be doing that in this PR, since this PR should specifically fix the bug of wrong `redo-ing`, rather than deciding whether we should update the `undo()` to display all persons or the previous view ^^

**Comment by eugenepeh** [comment]
> Though I'm not sure whether we should be doing that in this PR, since this PR should specifically fix the bug of wrong redo-ing, rather than deciding whether we should update the undo() to display all persons or the previous view ^^

icic. In my point of view, however, the main problem here is that, the undo/redo doesn't set the "state" back to the previous one. I believe that by tackling that issue in this PR, we will resolve the existing issue with redo too. Hence, i think it is justifiable that we fix them all in this PR.

**Comment by Zhiyuan-Amos** [comment]
Hmm ok! I think these few choices work:
1. Fix `undo` only to show the view according to `previousPredicate`. That way, `redo` is bound to execute on the correct view.
2. Fix `redo` only to show the view according to `previousPredicate` before executing it. 
3. Fix both `undo` and `redo` to show the view according to `previousPredicate`.

I think 1. seems good, it seems intuitive as well since by undo-ing, you reset the view to show the user the previous view as well. What do you think? ^^

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 7]
```diff
@@ -24,6 +29,13 @@ private void saveAddressBookSnapshot() {
         this.previousAddressBook = new AddressBook(model.getAddressBook());
     }
 
+    /**
+     * Stores the current state of {@code model#filteredPersonList#Predicate}
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: This looks like a violation of Law of Demeter :P There's no need to be that specific, maybe you can write something like `Stores the predicate used by the model to filter the list of persons`.

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java (hunk 2 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: @Zhiyuan-Amos  The header comment of `ModelStub` mentions that all of its methods should be failing, so I thought it would be more consistent to do the same for `getFilteredPersonListPredicate()` to fail in `ModelStub` and then return a default value in its subclasses like `getAddressBook()` method.

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: Oh ok got it! ^^ On first look, it doesn't seem intuitive that both methods `getAddressBook()` and `getFilteredPersonListPredicate()` are needed here, since the header comments for this class says: `A Model stub that always throw a DuplicatePersonException when trying to add a person.`

@eugenepeh should we have some kind of comments to denote that `getAddressBook()` and `getFilteredPersonListPredicate()` are required for `AddCommand` to execute?

**Comment by yamidark** [comment]
> Hmm ok! I think these few choices work:
> 1. Fix undo only to show the view according to previousPredicate. That way, redo is bound to execute on the correct view.
> 2. Fix redo only to show the view according to previousPredicate before executing it.
> 3. Fix both undo and redo to show the view according to previousPredicate.

> I think 1. seems good, it seems intuitive as well since by undo-ing, you reset the view to show the user > the previous view as well. What do you think? ^^

I also thought of doing 1. initially and removing `model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)` in `redo()` as I feel it would be more intuitive to the user for the view to be restored to before or after executing the command.

However, I thought that since I should be focusing only on the current issue in this PR hence I ended up doing 2. instead.

As such if fixing the issue of restoring the "state" after `undo()`/`redo()` should fall within this issue/PR, then I agree that 1. would be better and I can work on that too.

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java (hunk 2 above)
Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: Hmm @Zhiyuan-Amos , in such case, I think `getFilteredPersonListPredicate()` shouldn't even be called in the first place, since throwing DuplicatePersonException won't make AddCommand execute successfully. 

In this few scenarios, the main purpose is to test whether the functionality is working as per expectation. So if its not suppose to execute, we should override the default functionality to make sure it fails. For the `ModelStubAcceptingPersonAdded`, however, we can leave it as it is without overriding since 
1. it doesn't not affect any of the test results
2. even if we integrate Undo/Redo into systemtest, the default functionality does not differ from what we're testing.

Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: @eugenepeh  Actually `getFilteredPersonListPredicate()` gets called before the `AddCommand` executes and the `DuplicatePersonException` gets thrown, since we need to save the "state" before actually executing the command, which is why I needed to override again `getFilteredPersonListPredicate()` to pass in `ModelStubThrowingDuplicatePersonException` and `ModelStubAcceptingPersonAdded`.

**Comment by Zhiyuan-Amos** [comment]
> I also thought of doing 1. initially and removing model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS) in redo() as I feel it would be more intuitive to the user for the view to be restored to before or after executing the command.
> However, I thought that since I should be focusing only on the current issue in this PR hence I ended up doing 2. instead.

We don't need to remove `model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)` in `redo()` for the algorithm to work right?

`undo()` will look something like this:

```java
 protected final void undo() {
     requireAllNonNull(model, previousAddressBook);
     model.resetData(previousAddressBook);
     model.updateFilteredPersonList(previousPredicate); // the change is only done in this line
 }
```

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java (hunk 2 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: Yup, @eugenepeh both `getAddressBook()` and `getFilteredPersonListPredicate()` are called before `addPerson()` is called. So, we can't have `getFilteredPersonListPredicate()` failing :P 

As such, should we leave comments? Maybe something like

```
~~~~~~~~~~~~~~~~~These methods below are called prior to calling addPerson(ReadOnlyPerson)~~~~~~
```

**Comment by Zhiyuan-Amos** [comment]
> I just thought that restoring the view for undo() while leaving redo() to show all persons would be weird and perhaps confusing to users since DeleteCommand does not set the view to all persons after it's execution.

Yup, that's an inconsistency on the side of `DeleteCommand`. No need to settle in this PR ^^

**Comment by Zhiyuan-Amos** [comment]
@eugenepeh @yamidark The issue with option 1 is that we are assuming that nothing can come in between an `undo()` and `redo()`. i.e. you can't have `undo(), FooCommand that updates the view, redo()`. This assumption is pretty valid, and we currently have tests for it (see `UndoRedoStackTest#push_nonUndoableCommand_redoStackClearedAndCommandNotAdded()`). But ah, I'm not sure whether we should therefore couple the logic of `UndoableCommand` with `UndoRedoStack`.

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java (hunk 2 above)
Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: ahh i c, I thought it was AddCommand execute successfully > get predicate > save state.

In that case, do we even need to override it? It make sense that doing the same for the rest makes it more uniform but at the same time, it doesn't matter (to the test itself) as long as it returns something. 

I would prefer retain the default functionality so that our tests cover more area.

**Comment by eugenepeh** [comment]
@Zhiyuan-Amos `FooCommand that updates the view`, commands such as list/find etc are currently not undoable? Maybe that will need to be the next issue that we need to solve then :P

**Comment by eugenepeh** [comment]
@Zhiyuan-Amos , in such case, since the undo command saves the previous view, wouldn't redo apply the previous view first before performing the command? Hence it should work properly? In this case, does `FooCommand that updates the view` even matters?

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java (hunk 2 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: Hmm if I'm not wrong, we should override all methods for a `Stub` so that no matter what implementations are being changed in `ModelManager`'s methods, this test will be unaffected. I.e. The `Stub` should be independent of `ModelManager`.

**Comment by Zhiyuan-Amos** [comment]
> since the undo command saves the previous view

Just to be clearer to make sure we're on the same page: Upon command execution, the `previousPredicate` is saved.

For this bug to be fixed, we simply need to update `redo()` to apply `previousPredicate` on the `filteredList`, before executing the command.

So I was thinking of why not let's not touch `redo()`, but let's update `undo()` instead. I.e. only `undo()` is updated to apply `previousPredicate` on the `filteredList`. But I realized that doesn't work. Thus this [comment](https://github.com/se-edu/addressbook-level4/pull/792#issuecomment-357725885).

> In this case, does FooCommand that updates the view even matters?

I think I wasn't quite clear, so basically if we have `undo() -> NonUndoableFooCommand that updates view and isn't added to undoRedoStack cos it's NonUndoable -> redo()`, then the `redo()` will be applied on the wrong view. ^^

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java (hunk 2 above)
Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: ahh, oh yess... we're extending an empty ModelStub -my turn to get sacked for forgetting the fundamentals >_<-

Yes you're right, I guess the comments are fine then

**Comment by eugenepeh** [comment]
@Zhiyuan-Amos @yamidark , sorry that I got confused somewhere. My earlier example assumed that find/list commands are Undoable which they are not. 

Currently, I think we're stuck between the decision between getting it right and getting it to work.

Getting it right - we should make commands such as find/list to be undoable as well in this case, which will in turn fix this issue.

Getting it to work - by setting the state to previous just before the command is being reapplied. However this will create more work if we want to set it right next time.

**Comment by Zhiyuan-Amos** [comment]
No worries Eugene! :)) 

> find/list to be undoable as well

Cos this is a design decision, I think it's better to put this on hold first. The key thing is to fix this bug so that students doing AB-Lvl4 this semester will not face this bug again. Also furthermore, this is only @yamidark's 2nd PR, so I think we'll just take the easier way out first ^^

@yamidark are you clear on what are the changes to be made in the following iteration?

**Comment by yamidark** [comment]
> are you clear on what are the changes to be made in the following iteration?

@Zhiyuan-Amos I need to modify `undo()`, remove `Optional` from `previousPredicate`, and update the comments and commit messages (should I add the comments for `ModelStub` subclassess here too)?

**Comment by Zhiyuan-Amos** [comment]
> should I add the comments for ModelStub subclassess here too

Yup, add it in a separate commit.

> modify undo()

`undo()` stays the same ^^

**Comment by yamidark** [comment]
> undo() stays the same

So I stick with the restore view right before executing the command in redo() here?

**Comment by Zhiyuan-Amos** [comment]
> So I stick with the restore view right before executing the command in redo() here?

Yup that's right ^^

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java [hunk 8]
```diff
@@ -172,6 +174,8 @@ public void addPerson(ReadOnlyPerson person) throws DuplicatePersonException {
             personsAdded.add(new Person(person));
         }
 
+        /* ---------------These methods below are called prior to calling addPerson(ReadOnlyPerson)--------- */
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/AddCommandTest.java]: Leave a space in between the `-` and the words i.e. `/* --- These... (ReadOnlyPerson) ---- */`. Same for above.

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: The~~se~~

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: Also, as per our convention in System Tests, the `---- */` should end exactly on the 120 char line limit. The number of `-` on the left hand side and right hand side don't have to match though, as long as it looks ok ^^

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 9]
```diff
@@ -24,6 +28,26 @@ private void saveAddressBookSnapshot() {
...
+     * Stores the predicate used in {@code model#filteredPersons}.
+     */
+    private void savePredicateSnapshot() {
+        previousPredicate = model.getFilteredPersonListPredicate();
+    }
+
+    /**
+     * Returns the previousPredicate stored.
+     * Returns a default predicate to show all persons
+     * if previousPredicate is null.
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: the wrapping of the lines should be done on the 120 char; there's no need to wrap it otherwise.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 10]
```diff
@@ -36,12 +60,15 @@ protected final void undo() {
     }
 
     /**
-     * Executes the command and updates the filtered person
-     * list to show all persons.
+     * Reverts the filtered person list to its previous view
+     * before executing the command.
+     * Updates the filtered person list to show all persons
+     * after execution completes.
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: the wrapping of the lines should be done on the 120 char; there's no need to wrap it otherwise.

Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: @eugenepeh hmm actually I think that this header comment shouldn't be updated. The reverting of the filtered person list to its previous view ought to be abstracted out from callers; the callers simply need to know that the `redo()` operation will be done correctly.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 11]
```diff
@@ -36,12 +60,15 @@ protected final void undo() {
...
      */
     protected final void redo() {
         requireNonNull(model);
         try {
+            model.updateFilteredPersonList(getPreviousPredicate());
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: @eugenepeh I think the comment should be added here instead because on first look, it's not intuitive why we need to update the filtered list.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 12]
```diff
@@ -24,6 +28,26 @@ private void saveAddressBookSnapshot() {
...
+    /**
+     * Returns the previousPredicate stored.
+     * Returns a default predicate to show all persons
+     * if previousPredicate is null.
+     */
+    private Predicate<ReadOnlyPerson> getPreviousPredicate() {
+        if (previousPredicate == null) {
+            return PREDICATE_SHOW_ALL_PERSONS;
+        } else {
+            return previousPredicate;
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: Currently, `filteredPersons` in `ModelManager` can hold 3 things:
1. null
1. (unused) -> true
1. some person filter

The default predicate is `null`. However, since in our code base we decided not to deal with `null`s, I think that the better way is to simply update `ModelManager` to never allow `filteredPersons` to hold `null`.

```
public ModelManager(ReadOnlyAddressBook addressBook, UserPrefs userPrefs) {
    ....
    filteredPersons.setPredicate(PREDICATE_SHOW_ALL_PERSONS); // add this line at the end
}
```

That way, we don't have to consider the case of `previousPredicate` being `null`, and so we can remove all these logic and do away with this getter method.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 9 above)
Comment (yamidark) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: @Zhiyuan-Amos  was following approximately how the comments were being wrapped in the same class though. We should also wrap the line after each sentence, right?

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 12 above)
Comment (yamidark) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: >I think that the better way is to simply update ModelManager to never allow filteredPersons to hold null

@Zhiyuan-Amos Sounds good. This should be done on a separate commit, right?

**Comment by Zhiyuan-Amos** [comment]
Can you check if the updated `DeleteCommandSystemTest` works without this PR? I tried this test after reverting other changes except for `DeleteCommandSystemTest`, and the test passes as well; seems like this test doesn't test the new functionality.

If I'm not wrong, it's cos 
1. `Benson Meier` is at index 1 in the unfiltered list
1. `Benson Meier` is still at index 1 after being filtered.
1. The delete command executes on index 1

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 12 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: Yup, can do it as the first commit. ^^

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 9 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: > how the comments were being wrapped in the same class 

I have no idea why I wrapped it that way previously. :P That time I was still a noob I guess.

> We should also wrap the line after each sentence, right?

Yup, sorry missed that out in the earlier comment :)

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 10 above)
Comment (eugenepeh) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: @Zhiyuan-Amos yes, I agree that the process should be abstract. The caller only needs to know what changes at the end.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 11 above)
Comment (eugenepeh) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: Yup, it's not intuitive to someone (such as me :P) that why it needs to update list to previous state and back to all people at the end.

**Comment by yamidark** [comment]
>seems like this test doesn't test the new functionality.

@Zhiyuan-Amos Yea did not notice that the `Benson Meier` is 1st person in both the filtered and unfiltered list 😓 . 

In fact, while trying to rebuild the test using another filtered list, I noticed that the methods in `TestUtil` which `DeleteCommandSystemTest` uses for getting `Person` and `Index`, calls directly from the 
unfiltered list `model.getAddressBook().getPersonList()` instead of the displayed filtered list `model.getFilteredPersonList()`. 

```java
    /**
     * Returns the last index of the person in the {@code model}'s person list.
     */
    public static Index getLastIndex(Model model) {
        return Index.fromOneBased(model.getAddressBook().getPersonList().size());
    }

    /**
     * Returns the person in the {@code model}'s person list at {@code index}.
     */
    public static ReadOnlyPerson getPerson(Model model, Index index) {
        return model.getAddressBook().getPersonList().get(index.getZeroBased());
    }
```

Thus I would need to either change `DeleteCommandSystemTest` to get the `Person` and `Index` by itself or `TestUtil` to get from the displayed filtered list `model.getFilteredPersonList()`, in order to build tests that requires a filtered list. As I'm not sure if the behavior in `TestUtil` is intended, may I seek your opinion on this matter?

**Comment by Zhiyuan-Amos** [comment]
@yamidark Why did you do such a hard PR T.T I'll think about it tmr :P

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 11 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: I'm thinking that if we update the filteredPersons to all people at the end, then there's duplicate code because in `EditCommand`, the original execution already updates the list as well x.x

**Comment by yamidark** [comment]
>Can you try investigating this?

@Zhiyuan-Amos From what I investigated, in #555 during the conversion from `DeleteCommandTest` to `DeleteCommandSystemTest`, it was previously using `expectedAddressBook` for its assertion checks, which does not have a filtered person list.

You then suggested in https://github.com/se-edu/addressbook-level4/pull/555#discussion_r128346279 (v4 11/11) to switch over to use `Model` as per other tests, leading to the `model#addressBook#personList` to get the same person list used all along, which were later refactored into `TestUtil` in the same PR.

Since the assertion tests on `Model` now instead of `AddressBook` back then, and we are including (and have included some) tests on filtered lists, I think that the change to `filteredPersonList` is necessary.

>If you can change everything to use filteredPersons instead, and the tests work fine without requiring some major revamp, we can make the change

It seems only `DeleteCommandSystemTest` uses those method in `TestUtil`, thus we can safely change the methods in `TestUtil` to use `filteredPersons` alone.

**Comment by eugenepeh** [comment]
Opened issue #797 for the recent discussion

Sorry @yamidark that I've caused a bit of confusion here. Sometimes I get a little mixed up with the students' work and the se-edu addressbook. 

> It seems only DeleteCommandSystemTest uses those method in TestUtil, thus we can safely change the methods in TestUtil to use filteredPersons alone.

Good discovery, we should proceed with that and change the test sequence in DeleteCommandSystemTest to match the scenario in #737 .

**Comment by Zhiyuan-Amos** [comment]
@yamidark great work on doing such a thorough investigation, go ahead and make the changes in a separate commit :)

File: src/main/java/seedu/address/model/ModelManager.java [hunk 13]
```diff
@@ -92,6 +92,12 @@ public void updatePerson(ReadOnlyPerson target, ReadOnlyPerson editedPerson)
         return FXCollections.unmodifiableObservableList(filteredPersons);
     }
 
+    @Override
+    @SuppressWarnings("unchecked")
+    public Predicate<ReadOnlyPerson> getFilteredPersonListPredicate() {
+        return (Predicate<ReadOnlyPerson>) filteredPersons.getPredicate();
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/model/ModelManager.java]: Follow what I mentioned [above](https://github.com/se-edu/addressbook-level4/pull/792#discussion_r161701954), I think we should have an assertion here to ensure that this line never returns null. The code will be clunkier, but it's much safer in ensuring that we don't have programmer errors of setting predicate to be null.

```java
Predicate<ReadOnlyPerson> toReturn = (Predicate<ReadOnlyPerson>) filteredPersons.getPredicate();
assert toReturn != null; // should we comment here? seems unintuitive on first sight, since #getPredicate() is expected to possibly return null
return toReturn;
```

**Comment by pyokagan** [comment]
@Zhiyuan-Amos What comment did you delete from me btw?

**Comment by Zhiyuan-Amos** [comment]
@pyokagan I deleted my long comment where I thought there was a bug with this PR, but it was actually my mistake. I deleted it because it was a useless comment and it's really long, and kinda disrupts the code review. Didn't know that deleting my comment will auto-delete all your comments as well.

Your comments are concerning:
1. Unable to reproduce the bug on your machine (since it's my error actl).
2. Your thoughts on the solution to fixing this issue.

File: src/main/java/seedu/address/model/ModelManager.java (hunk 13 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/model/ModelManager.java]: Hmm, another way to do it (which allows us to remove `@SuppressWarnings("unchecked")` is to do:
```java
Predicate<? super ReadOnlyPerson> toReturn = filteredPersons.getPredicate();
if (!(toReturn instance of Predicate<ReadOnlyPerson>)) { // this line checks for null too
    throw new AssertionError("some text");
}
return (Predicate<ReadOnlyPerson>) toReturn;
```

Comment (yamidark) [reply src/main/java/seedu/address/model/ModelManager.java]: @Zhiyuan-Amos  the second method seems to give errors though? 
>Illegal generic type for instanceof
Condition 'toReturn instanceof Predicate<ReadOnlyPerson>' is redundant and can be replaced with '!= null' less

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 11 above)
Comment (yamidark) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: `AddCommand` also updates the list to all persons, just that it does so in the `ModelManager` instead.

File: src/main/java/seedu/address/model/ModelManager.java (hunk 13 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/model/ModelManager.java]: Let's do the first one then.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java (hunk 9 above)
Comment (yamidark) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: Should I clean up those other comments in `UndoableCommand` in the next iteration too?

Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: Nope, that's a separate issue altogether ^^

**Comment by yamidark** [comment]
@Zhiyuan-Amos @eugenepeh I have updated the PR with changes suggested/requested.
May I submit the next iteration for review?

**Comment by Zhiyuan-Amos** [comment]
@yamidark yup :) in the future just go ahead.

File: src/main/java/seedu/address/model/ModelManager.java [hunk 14]
```diff
@@ -37,6 +37,8 @@ public ModelManager(ReadOnlyAddressBook addressBook, UserPrefs userPrefs) {
 
         this.addressBook = new AddressBook(addressBook);
         filteredPersons = new FilteredList<>(this.addressBook.getPersonList());
+        // set a show all person as default predicate to prevent filteredPersons having a null value predicate
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/model/ModelManager.java]: set**s** a show all person**s**... null ~~value~~ predicate

File: src/main/java/seedu/address/model/ModelManager.java [hunk 15]
```diff
@@ -92,6 +94,15 @@ public void updatePerson(ReadOnlyPerson target, ReadOnlyPerson editedPerson)
         return FXCollections.unmodifiableObservableList(filteredPersons);
     }
 
+    @Override
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/model/ModelManager.java]: As spoken, this should be done in future commits :P

File: src/test/java/seedu/address/testutil/TestUtil.java [hunk 16]
```diff
@@ -35,20 +35,20 @@ public static String getFilePathInSandboxFolder(String fileName) {
...
     /**
      * Returns the last index of the person in the {@code model}'s person list.
      */
     public static Index getLastIndex(Model model) {
-        return Index.fromOneBased(model.getAddressBook().getPersonList().size());
+        return Index.fromOneBased(model.getFilteredPersonList().size());
     }
 
     /**
      * Returns the person in the {@code model}'s person list at {@code index}.
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/testutil/TestUtil.java]: Update header comments. Same for above.

**Comment by vivekscl** [comment]
@Zhiyuan-Amos Alright. Will review it soon 👍

File: src/test/java/seedu/address/logic/commands/UndoableCommandTest.java [hunk 17]
```diff
@@ -36,7 +36,13 @@ public void executeUndo() throws Exception {
     }
 
     @Test
-    public void redo() {
+    public void redo() throws Exception {
+        // run the command once to save the states
+        dummyCommand.execute();
+
+        // revert back to original state
+        dummyCommand.undo();
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/UndoableCommandTest.java]: seems like there's no other way to go about this, so let's extract these code out as a method `redoSetup()`. This raises the level of abstraction.

File: src/test/java/systemtests/DeleteCommandSystemTest.java [hunk 18]
```diff
@@ -60,11 +62,25 @@ public void delete() {
         /* ------------------ Performing delete operation while a filtered list is being shown ---------------------- */
 
         /* Case: filtered person list, delete index within bounds of address book and person list -> deleted */
-        showPersonsWithName(KEYWORD_MATCHING_MEIER);
+        Model modelBeforeDeletingFirstFiltered = getModel();
+        showPersonsWithName(KEYWORD_MATCHING_FIONA);
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/DeleteCommandSystemTest.java]: you made the change for this test, do you need to update the `EditCommandSystemTest`?

File: src/test/java/seedu/address/logic/commands/RedoCommandTest.java [hunk 19]
```diff
@@ -34,13 +34,25 @@ public void setUp() {
     }
 
     @Test
-    public void execute() {
-        UndoRedoStack undoRedoStack = prepareStack(
+    public void execute() throws Exception {
+        UndoRedoStack undoRedoStackOne = prepareStack(
+                Arrays.asList(deleteCommandOne, deleteCommandTwo), Collections.emptyList());
+        UndoRedoStack undoRedoStackTwo = prepareStack(
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/RedoCommandTest.java]: is there a need for 2 stacks?

File: src/test/java/systemtests/DeleteCommandSystemTest.java (hunk 18 above)
Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/DeleteCommandSystemTest.java]: Also, we should assert that the 1st person in the filtered person list != 1st person in address book.

Comment (yamidark) [reply src/test/java/systemtests/DeleteCommandSystemTest.java]: >you made the change for this test, do you need to update the EditCommandSystemTest?

Unlike in `DeleteCommandSystemTest`, the 1st person does not get deleted in `EditCommandSystemTest`, so the 1st person of the filtered list will be different, so there isn't a need for change here.

Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/DeleteCommandSystemTest.java]: Ok cool. Let's update `EditCommandSystemTest` to have the assertion as well ^^

File: src/main/java/seedu/address/model/ModelManager.java (hunk 14 above)
Comment (vivekscl) [inline src/main/java/seedu/address/model/ModelManager.java]: The comment seems a bit long-winded, does this sound better? 
`Sets a default predicate as null predicates are not dealt with`
@Zhiyuan-Amos should this comment be in the header comment of the constructor instead?

File: src/main/java/seedu/address/model/ModelManager.java [hunk 20]
```diff
@@ -92,6 +94,15 @@ public void updatePerson(ReadOnlyPerson target, ReadOnlyPerson editedPerson)
...
+    @SuppressWarnings("unchecked")
+    public Predicate<ReadOnlyPerson> getFilteredPersonListPredicate() {
+        Predicate<ReadOnlyPerson> toReturn = (Predicate<ReadOnlyPerson>) filteredPersons.getPredicate();
+        // the predicate set inside filteredPersons should never be null
```
Comment (vivekscl) [inline src/main/java/seedu/address/model/ModelManager.java]: This comment could be:
`The predicate should not be set to null`

**Comment by Zhiyuan-Amos** [comment]
@yamidark as spoken, let's take a look at using `Reflection` over [here](https://stackoverflow.com/a/34658/8828382) to simplify the test cases. If iirc, the reason why we didn't use `Reflection` previously was that we wanted to minimise introducing new concepts to students. However, this seems like a good place to use `Reflection` since the only alternative is to have dependencies on `deleteCommand#execute()` and `undoCommand#execute()`, and quite a bit of setting up code is required as well.

After you've done up the next iteration, leave a write-up here explaining why we are using `Reflection` and why it's better. That's because we need to rope others in like Prof to approve of this first before we can carry on ^^

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java [hunk 21]
```diff
@@ -150,6 +150,8 @@ public void addPerson(ReadOnlyPerson person) throws DuplicatePersonException {
             throw new DuplicatePersonException();
         }
 
+        /* ------------ These methods below are called prior to calling addPerson(ReadOnlyPerson) ------------------- */
```
Comment (vivekscl) [inline src/test/java/seedu/address/logic/commands/AddCommandTest.java]: To be consistent with the rest of the code base maybe you could change this to:
`//=========== These methods below are called prior to calling addPerson(ReadOnlyPerson) =================`
Same goes with the other one.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 22]
```diff
@@ -42,6 +53,9 @@ protected final void undo() {
     protected final void redo() {
         requireNonNull(model);
         try {
+            // restore filtered person list to the same previous view to ensure command executes itself on the same
+            // correct {@code Person} as before
```
Comment (vivekscl) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: This comment could be:
`Restore the previous view of the filtered person list to ensure that the command is executed on the correct {@code Person}`

File: src/test/java/seedu/address/logic/commands/RedoCommandTest.java [hunk 23]
```diff
@@ -34,13 +34,25 @@ public void setUp() {
...
-        redoCommand.setData(model, EMPTY_COMMAND_HISTORY, undoRedoStack);
+        undoCommand.setData(model, EMPTY_COMMAND_HISTORY, undoRedoStackOne);
+        redoCommand.setData(model, EMPTY_COMMAND_HISTORY, undoRedoStackTwo);
         Model expectedModel = new ModelManager(getTypicalAddressBook(), new UserPrefs());
 
+        // run the commands first to save their states
+        deleteCommandOne.execute();
+        deleteCommandTwo.execute();
+
+        // revert back to original state
```
Comment (vivekscl) [inline src/test/java/seedu/address/logic/commands/RedoCommandTest.java]: revert back to **the** original state

File: src/test/java/seedu/address/logic/commands/UndoableCommandTest.java [hunk 24]
```diff
@@ -36,7 +36,13 @@ public void executeUndo() throws Exception {
     }
 
     @Test
-    public void redo() {
+    public void redo() throws Exception {
+        // run the command once to save the states
```
Comment (vivekscl) [inline src/test/java/seedu/address/logic/commands/UndoableCommandTest.java]: ...to save the state~~s~~

File: src/test/java/seedu/address/logic/commands/UndoableCommandTest.java [hunk 25]
```diff
@@ -36,7 +36,13 @@ public void executeUndo() throws Exception {
...
+        dummyCommand.execute();
+
+        // revert back to original state
```
Comment (vivekscl) [inline src/test/java/seedu/address/logic/commands/UndoableCommandTest.java]: revert back to **the** original state

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java (hunk 21 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: which part of the code are you referring to? Cos from [AddCommandSystemTest](https://github.com/se-edu/addressbook-level4/blob/master/src/test/java/systemtests/AddCommandSystemTest.java#L123), it's done this way :P

File: src/main/java/seedu/address/model/ModelManager.java (hunk 20 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/model/ModelManager.java]: On further look, I wonder if this comment is necessary, since the following assert basically implies this comment.

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java (hunk 21 above)
Comment (vivekscl) [reply src/test/java/seedu/address/logic/commands/AddCommandTest.java]: Yeah I just realised :sweat_smile:. So there's no need to change it. It was used in the ModelManager.

File: src/main/java/seedu/address/model/ModelManager.java (hunk 20 above)
Comment (vivekscl) [reply src/main/java/seedu/address/model/ModelManager.java]: I don't think it is necessary either.

File: src/main/java/seedu/address/model/Model.java [hunk 26]
```diff
@@ -39,6 +39,9 @@ void updatePerson(ReadOnlyPerson target, ReadOnlyPerson editedPerson)
     /** Returns an unmodifiable view of the filtered person list */
     ObservableList<ReadOnlyPerson> getFilteredPersonList();
 
+    /** Returns the predicate used in the filtered person list */
+    Predicate<ReadOnlyPerson> getFilteredPersonListPredicate();
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/model/Model.java]: The header comment can be improved to state that it's guaranteed not to return null.

File: src/main/java/seedu/address/model/ModelManager.java (hunk 14 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/model/ModelManager.java]: I don't think there's a need to; this should be abstracted away from the caller. As long as we mention that we do not deal with nulls in the [getter](https://github.com/se-edu/addressbook-level4/pull/792#pullrequestreview-89720174) and setter method, I think it should be fine.

I think the setter method's header comments can be further specified to inform callers to call `PREDICATE_SHOW_ALL_PERSONS` instead of passing in `null` if they want to show all persons. But that's not the job of this PR :)

**Comment by yamidark** [comment]
>The words state and view are being used interchangeably. Do they mean the same thing? If they do then we could standardize on one.

@vivekscl `state` is used to refer to the full `AddressBook` while `view` is refering to the `Model`'s filtered person list. But seems like we could probably differentiate it clearer by mentioning `AddressBook`'s `state` and `Model`'s `view` instead of by themselves.

**Comment by vivekscl** [comment]
> `state` is used to refer to the full `AddressBook` while `view` is referring to the `Model`'s filtered person list.

@yamidark Oh, now I understand. 

> But seems like we could probably differentiate it clearer by mentioning AddressBook's state and Model's view instead of by themselves.

Sounds good to me since that would make things clearer for new developers as well. :smile:

**Comment by yamidark** [comment]
As me and @Zhiyuan-Amos have discussed, we have decided to use `Reflection` in order to simplify the updated `redo()` test cases in `UndoableCommandTest` and `RedoCommandTest`.

Our current solution to #737 is to update `UndoableCommand#redo()` to revert the `Model` filtered person list back to it's previous `Model` view before re-executing the command, to ensure that index-based commands such as `EditCommand` and `DeleteCommand` will execute on the correct person, and to keep the `Model` view after execution of `undo()`/`redo()` to remain the showing all persons.

This, however, creates dependencies on the `UndoableCommand` to be executed once first in order to save the `Model`'s view before `RedoCommand` can re-execute the command successfully, especially since we do not support null predicates in our code. 

As such, the `redo()` tests in `UndoableCommand` and `RedoCommandTest` require lots of setting up by executing and undoing the command before we can run the `redo()` test, which makes the code very ugly and dependent on other components to work too.

Since all we need is to ensure the private `UndoableCommand#previousPredicate` field value is not `null`, we decided to use `Reflection` to set the `UndoableCommand#previousPredicate` field to the default `PREDICATE_SHOW_ALL_PERSONS` for testing purposes. This will greatly simplify the code and also remove dependencies on the other classes, isolating `UndoableCommand#redo()` to test its own functionality. 

This also removes the need to set a base value for `UndoableCommand#previousPredicate` in the production code, enabling us to catch test cases where `redo()` does get invoked without calling `UndoableCommand#execute()` and `UndoableCommand#undo()` first, since `UndoableCommand#previousPredicate` will remain `null`.

File: src/test/java/seedu/address/testutil/ReflectionUtil.java [hunk 27]
```diff
@@ -0,0 +1,20 @@
...
+
+import java.lang.reflect.Field;
+
+/**
+ *  A utility class to access and modify private methods and fields
+ */
+public class ReflectionUtil {
+
+    /**
+     * Set the targetObject's private fieldName field to the targetValue
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/testutil/ReflectionUtil.java]: `{@code targetObject}'s`  etc

File: src/test/java/seedu/address/testutil/TestUtil.java [hunk 28]
```diff
@@ -51,4 +55,14 @@ public static Index getLastIndex(Model model) {
     public static Person getPerson(Model model, Index index) {
         return model.getFilteredPersonList().get(index.getZeroBased());
     }
+
+    /**
+     * Set up each {@code UndoableCommand} to be executed in {@code UndoableCommand#redo()}
+     */
+    public static void prepareRedo(UndoableCommand... commandsToRedo) throws Exception {
+        for (UndoableCommand commandToRedo: commandsToRedo) {
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/testutil/TestUtil.java]: let's try using `foreach`

File: src/test/java/seedu/address/testutil/ReflectionUtil.java [hunk 29]
```diff
@@ -0,0 +1,20 @@
...
+     */
+    public static void setPrivateField(Class targetClass, String fieldName, Object targetObject, Object targetValue)
+            throws Exception {
+        Field field = targetClass.getDeclaredField(fieldName);
```
Comment (yamgent) [inline src/test/java/seedu/address/testutil/ReflectionUtil.java]: Do we need to pass in the `targetClass`? How about `targetObject.getClass().getDeclaredField(fieldName)`?

File: src/test/java/seedu/address/testutil/TestUtil.java [hunk 30]
```diff
@@ -51,4 +55,14 @@ public static Index getLastIndex(Model model) {
     public static Person getPerson(Model model, Index index) {
         return model.getFilteredPersonList().get(index.getZeroBased());
     }
+
+    /**
+     * Set up each {@code UndoableCommand} to be executed in {@code UndoableCommand#redo()}
+     */
+    public static void prepareRedo(UndoableCommand... commandsToRedo) throws Exception {
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/testutil/TestUtil.java]: initPredicate

File: src/test/java/seedu/address/testutil/ReflectionUtil.java (hunk 29 above)
Comment (yamidark) [reply src/test/java/seedu/address/testutil/ReflectionUtil.java]: > Do we need to pass in the targetClass? How about `targetObject.getClass().getDeclaredField(fieldName)`?

The `targetObject` may be a subclass of the superclass which contains the target `fieldName`, which will cause us to get `NoSuchFieldException`. Thus it is necessary to specify the `targetClass` for which the target `fieldName` is specified.

File: src/test/java/seedu/address/testutil/TestUtil.java (hunk 30 above)
Comment (yamidark) [reply src/test/java/seedu/address/testutil/TestUtil.java]: @Zhiyuan-Amos Actually should this method be moved to `CommandTestUtil` instead since we should only be using this for unit tests?

File: src/test/java/seedu/address/testutil/ReflectionUtil.java (hunk 29 above)
Comment (yamgent) [reply src/test/java/seedu/address/testutil/ReflectionUtil.java]: Hmm ok, I was thinking whether we can swap the order of the parameters to make it look more "natural" to the order when we write code -> `targetClass, targetObject, fieldName, targetValue`. (The order follows: `((targetClass)targetObject).fieldName = targetValue`.)

@Zhiyuan-Amos What do you think about this?

File: src/test/java/seedu/address/testutil/TestUtil.java (hunk 30 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/testutil/TestUtil.java]: Yup, sounds good!

File: src/test/java/seedu/address/testutil/ReflectionUtil.java (hunk 29 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/testutil/ReflectionUtil.java]: Yup, this ordering is good! ^^

File: src/main/java/seedu/address/model/Model.java [hunk 31]
```diff
@@ -39,6 +39,12 @@ void updatePerson(Person target, Person editedPerson)
     /** Returns an unmodifiable view of the filtered person list */
     ObservableList<Person> getFilteredPersonList();
 
+    /**
+     * Returns the predicate used in the filtered person list
+     * Guarantees: predicate returned is non-null
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/model/Model.java]: we have `.` at the end of each sentence if it's multi-line :P

Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/model/Model.java]: Also, this line can be replaced with `@return a non-null predicate.`

File: src/test/java/seedu/address/testutil/ReflectionUtil.java [hunk 32]
```diff
@@ -0,0 +1,20 @@
...
+        field.setAccessible(true);
+        field.set(targetObject, targetValue);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/testutil/ReflectionUtil.java]: Do check if we need to call `field.setAccessible(false)` after setting the field.

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 33]
```diff
@@ -4,15 +4,21 @@
...
 import seedu.address.logic.commands.exceptions.CommandException;
 import seedu.address.model.AddressBook;
 import seedu.address.model.ReadOnlyAddressBook;
+import seedu.address.model.person.Person;
 
 /**
  * Represents a command which can be undone and redone.
  */
 public abstract class UndoableCommand extends Command {
+    public static final String PREVIOUS_PREDICATE_FIELD_NAME = "previousPredicate";
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: Since this isn't used in the main code base, I'm not sure whether this should be here. @yamgent should we move this to test class instead?

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 34]
```diff
@@ -24,6 +30,13 @@ private void saveAddressBookSnapshot() {
         this.previousAddressBook = new AddressBook(model.getAddressBook());
     }
 
+    /**
+     * Stores the predicate used in {@code model#filteredPersons}.
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: used **by**

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 35]
```diff
@@ -42,6 +55,9 @@ protected final void undo() {
     protected final void redo() {
         requireNonNull(model);
         try {
+            // Restore the previous view of the filtered person list to ensure that the command is executed on the
+            // correct {@code Person}
+            model.updateFilteredPersonList(previousPredicate);
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: put a new line here. This is to denote that the comments only apply for this particular line.

File: src/main/java/seedu/address/model/ModelManager.java [hunk 36]
```diff
@@ -37,6 +37,8 @@ public ModelManager(ReadOnlyAddressBook addressBook, UserPrefs userPrefs) {
 
         this.addressBook = new AddressBook(addressBook);
         filteredPersons = new FilteredList<>(this.addressBook.getPersonList());
+        // Sets a default predicate as null predicates are not dealt with
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/model/ModelManager.java]: We should rephrase this a bit more

File: src/test/java/seedu/address/testutil/ReflectionUtil.java (hunk 32 above)
Comment (yamidark) [reply src/test/java/seedu/address/testutil/ReflectionUtil.java]: Based on [this](https://stackoverflow.com/questions/10638826/java-reflection-impact-of-setaccessibletrue), the `getDeclaredField` will return a new `Field` instance without affecting the actual field of the class, and since this `field` is used only within the method, there shouldn't be a need to set the accessibility back to `false`.

**Comment by vivekscl** [comment]
@yamidark and @Zhiyuan-Amos  will review the commit messages in a while 👍

**Comment by pyokagan** [comment]
Note that having to use reflection in order to bypass a class' encapsulation is usually indicative of an API design problem. An API design needs to also be easily *testable* as well (one of the reasons we have TDD after all). You may wish to do an investigation into where the API design problem occurs.

In any case, I'd prefer the vanilla approach in v5 rather than resorting to a hack in the code base, as it'll encourage bad practices.

**Comment by Zhiyuan-Amos** [comment]
@pyokagan thanks for the insight! My thoughts on this:

For `UndoableCommand`:
1. `redo()` requires the private field `previousPredicate` to be initialized.
1. `previousPredicate` is initialized when `execute()` is called.
1. Therefore, if we want to unit test `RedoCommand` that it calls `UndoableCommand#redo()` correctly, then we will first need to init `previousPredicate` by calling `UndoableCommand#execute()`.

Also, after calling `execute()`, it only makes sense for us to call `undo()` before executing `RedoCommand` to call `UndoableCommand#redo()`.

1. As such, unit testing of `RedoCommand` is dependent on `UndoableCommand#undo()` and `UndoableCommand#execute()`. 

1. Also, having to call `undo()` and `execute()` as part of the preparation for the execution of `RedoComand` makes the code rather long, compared to simply using `Reflection`.

Seeking your advice on this Paul! :)

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 

> redo() requires the private field previousPredicate to be initialized.
> previousPredicate is initialized when execute() is called.
> Therefore, if we want to unit test RedoCommand that it calls UndoableCommand#redo() correctly, then we will first need to init previousPredicate by calling UndoableCommand#execute().
> [...]
> Also, having to call undo() and execute() as part of the preparation for the execution of RedoComand makes the code rather long, compared to simply using Reflection.

Yes, these are all the implementation details of the current design. Your argument assumes that we can't change the current undo/redo design to make it more easily testable. I'm saying you can, and you should :-)

So, I want a more convincing argument than "the current design doesn't let us easily test it with little code, so we'll just completely circumvent it."

A test depending on other components to work together is nothing new. (That's basically describing all integration tests). If a design doesn't allow you to easily unit test it, then look for another design. Using reflection to circumvent it is basically telling future developers that they don't have to care about API design at all.

**Comment by Zhiyuan-Amos** [comment]
@yamidark try Version 2, but this time create a method in `UndoableCommand` which does nothing, name it something like `preprocessCommand`. This method will be called:
```
@Override
public final CommandResult execute() throws CommandException {
    saveAddressBookSnapshot();
    preprocessCommand(); // here
    return executeUndoableCommand();
}
```

Then for `EditCommand` and `DeleteCommand`, override the method to create the `Person` object from the `Index`. Let's see whether it looks messy or not. This way of doing means we don't need to have a boolean flag `isFirstTimeExecuting`

**Comment by pyokagan** [comment]
btw, why is the regression test implemented in the system test level? We should try to follow the testing pyramid, no? https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html

**Comment by Zhiyuan-Amos** [comment]
> btw, why is the regression test implemented in the system test level? We should try to follow the testing pyramid, no? https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html

This bug happens after the execution of different `Command`s (`FindCommand`, `DeleteCommand / EditCommand`, `UndoCommand` etc), and it also concerns the state of the `Model` (`filteredPersons`), so it seems that we minimally require the test to be at integration level. So we should do it at integration level instead?

Thanks for the catch @pyokagan, it just seemed so natural to have it at the system level cos tests at integration level do not test for `undo` and `redo`.

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 37]
```diff
@@ -24,22 +24,20 @@
 
     private final Index targetIndex;
 
+    private Person personToDelete;
+
     public DeleteCommand(Index targetIndex) {
         this.targetIndex = targetIndex;
+        personToDelete = null;
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java]: there's no need to initialise this value (by it's default null anyways)

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 38]
```diff
@@ -64,19 +67,15 @@ public EditCommand(Index index, EditPersonDescriptor editPersonDescriptor) {
...
     public CommandResult executeUndoableCommand() throws CommandException {
-        List<Person> lastShownList = model.getFilteredPersonList();
-
-        if (index.getZeroBased() >= lastShownList.size()) {
+        if (personToEdit == null) {
             throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
         }
 
-        Person personToEdit = lastShownList.get(index.getZeroBased());
-        Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: you can still create the editedPerson here; there's no reason to bring it over to preprocessUndoableCommand right?

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 39]
```diff
@@ -49,6 +47,15 @@ public CommandResult executeUndoableCommand() throws CommandException {
         return new CommandResult(String.format(MESSAGE_DELETE_PERSON_SUCCESS, personToDelete));
     }
 
+    @Override
+    protected void preprocessUndoableCommand() {
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java]: perhaps we can throw `CommandException` here instead.

**Comment by eugenepeh** [comment]
@yamidark also take note that the correct way of typing commit message title as shown in [oss-process](https://oss-generic.github.io/process/docs/FormatsAndConventions.html#commit-message), is lowercase letter after the subject and colon. E.g. `UndoableCommand: Add preprocessUndoableCommand() method` -> `UndoableCommand: add preprocessUndoableCommand() method`

**Comment by Zhiyuan-Amos** [comment]
> it might lead to problem in undo -> redo (adds back the person) -> undo (unable to undo again).

Sorry @eugenepeh can elaborate a bit further? :) Yup, I updated `syncWithMasterTagList` to return a new `Person` object, but I can't see how it's related to this ><

**Comment by eugenepeh** [comment]
> Sorry @eugenepeh can elaborate a bit further? :) Yup, I updated syncWithMasterTagList to return a new Person object, but I can't see how it's related to this ><

Redo will add back the person deleted so the Person object may be different, no? D:

**Comment by Zhiyuan-Amos** [comment]
> Redo will add back the person deleted so the Person object (personToDelete) may be different, no? D:

You are referring to `AddCommand` is it? (cos redo-ing will add the person == `AddCommand`?) XD But we aren't concerned with that command here right? ><

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 

> So we should do it at integration level instead?

Can keep the system test if you want, but yes, the regression test should be implemented at a level that is not the system test level as well.

**Comment by eugenepeh** [comment]
>You are referring to AddCommand is it? (cos redo-ing will add the person == AddCommand?) XD But we aren't concerned with that command here right? ><

Oops sorry... undo resets AddressBook to previous state... hmm... how come its done this way? I thought this will takes up huge amount of memory the bigger the AddressBook and the more the UndoableCommands you have?

**Comment by Zhiyuan-Amos** [comment]
> Oops sorry... undo resets AddressBook to previous state... hmm... how come its done this way? I thought this will takes up huge amount of memory the bigger the AddressBook and the more the UndoableCommands you have?

This is a simpler way of doing it because we didn't have time previously to properly implement `undo()` for each `UndoableCommand`.

**Comment by eugenepeh** [comment]
> This is a simpler way of doing it because we didn't have time previously to properly implement undo() for each UndoableCommand.

icic... should we make an epic issue for this to correct it back? Akshay was complaining about one of my teams' projects taking up 2GB of ram last sem. I haven't investigate it but this might be the cause > <

**Comment by Zhiyuan-Amos** [comment]
> icic... should we make an epic issue for this to correct it back? 

Yup we can raise an issue for this ^^ Not sure if it's worth `epic` though XD

> Akshay was complaining about one of my teams' projects taking up 2GB of ram last sem. I haven't investigate it but this might be the cause > <

Hmm if your AddressBook is huge, and you executed a lot of `UndoableCommand`s, then this is likely to be the cause :<

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 38 above)
Comment (yamidark) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: >you can still create the editedPerson here; there's no reason to bring it over to preprocessUndoableCommand right?

Yes, you're right; just that I felt that creating the editedPerson is part of the preprocessing step thus I moved it over as well. Should I just leave it in `execute` instead?

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java (hunk 39 above)
Comment (yamidark) [reply src/main/java/seedu/address/logic/commands/DeleteCommand.java]: > perhaps we can throw CommandException here instead

Yep, since `preprocessUndoableCommand()` is called within `execute()` this seems okay.

**Comment by yamidark** [comment]
@Zhiyuan-Amos 

> For the test, take a look at #792 (comment)

May I know where I should add this integration test though? Do I create a new test class `UndoRedoCommandTest`?


> take a look at #547 (comment)

Noted. The reason I used `DummyCommand` was because `DeleteCommand` needed to call the `preprocessUndoableCommand` to save the person first, but then seems like I could just switch over to another `UndoableCommand` (e.g `AddCommand`) with does not require this call instead, or just call `preprocessUndoableCommand` in `setUp()`?

@eugenepeh 

>also take note that the correct way of typing commit message title as shown in oss-process, is lowercase letter after the subject and colon.

Sorry missed that 😓. Will update my commit messages (in the other PR too).

**Comment by Zhiyuan-Amos** [comment]
> Do I add the tests into DeleteCommandTest and EditCommandTest respectively (and update the header comment to include integration with Undo/RedoCommand?

Sounds good!

> Noted. The reason I used DummyCommand was because DeleteCommand needed to call the preprocessUndoableCommand to save the person first, but then seems like I could just switch over to another UndoableCommand (e.g AddCommand) with does not require this call instead, or just call preprocessUndoableCommand in setUp()?

1. I see, so the issue is that you need to call `execute()` and `undo()` before being able to execute `redo()` through `RedoCommand`? Yup, switch over to an `UndoableCommand` that does not require this then ^^

1. I get it that stubbing `DummyCommand` is the cleanest way to go, but we're like doing `half stub` cos we aren't stubbing the `Model`. Which was why we decided not to have `DummyCommand` as a `stub`.

1. Lastly, I don't think you can call `preprocessUndoableCommand` in `setUp()` cos it's a protected method right?

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 38 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: It's ok; ignore this comment, leave it in `preprocessUndoableCommand` ^^

**Comment by yamidark** [comment]
> Lastly, I don't think you can call preprocessUndoableCommand in setUp() cos it's a protected method right?

Seems like we are able to call the protected method;  however we need to use different index for `deleteCommandOne` and `deleteCommandTwo` if we call them at `setUp` since they will end up pointing to the same `Person`, or we call it right before calling `redo()` (which is probably uglier).

Which also brings up the issue if `Delete/EditCommand` should change its `equal` method to also consider the `personToDelete/Edit`.

**Comment by Zhiyuan-Amos** [comment]
> Seems like we are able to call the protected method (RedoCommandTest and UndoableCommand are in the same seedu.address.logic.commands package); however we need to use different index for deleteCommandOne and deleteCommandTwo if we call them at setUp since they will end up pointing to the same Person, or we call it right before calling redo() (which is probably uglier).

Haha let's just change it to use `AddCommand` then.

> Which also brings up the issue if Delete/EditCommand should change its equal method to also consider the personToDelete/Edit.

Ah. Problem. Let's just leave it as it is first; fix up the other issues first then submit the next iteration then we see how ^^

**Comment by Zhiyuan-Amos** [comment]
@yamidark don't do up the integration tests first. Let's just do up the main code base and see if this is the architecture that we want. If it's ok, then we can do the regression tests at integration level.

**Comment by yamidark** [comment]
>don't do up the integration tests first. 

Already did up the integration test in `DeleteCommandTest` 😱; will just submit it together in the next iteration for you all to review before I bring it over to `EditCommandTest` too.

**Comment by Zhiyuan-Amos** [comment]
@pyokagan can you take a look at V.10? Following what you've mentioned [earlier](https://github.com/se-edu/addressbook-level4/pull/792#issuecomment-359322646), here's an alternate design that I've come up with. This resolves the issue of using `Reflection` for unit testing. However, another issue that pops up with this design is that whether we should update `DeleteCommand#equals(Object)` & `EditCommand#equals(Object)` to consider the `Person` field as well.

Thanks Paul ^^

**Comment by pyokagan** [comment]
@Zhiyuan-Amos I'll only have time to do a review during the weekend if you want to have a full review.

Some general comments from a glance at the full diff and comment thread:

* Add a new test case rather than trying to retrofit an existing test case.

* Try to get the tests *correct* first (ensure they are testing boundary values and all that stuff) before moving on to care about simplicity. Correctness should always be the top priority.

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 

> However, another issue that pops up with this design is that whether we should update DeleteCommand#equals(Object) & EditCommand#equals(Object) to consider the Person field as well.

I don't quite get this question, btw. Are you asking e.g. if `DeleteCommand` has a new field `personToDelete`, should `personToDelete` be checked in `DeleteCommand#equals(Object)` as well?

Also, well, what do *you* think? You need to give your own opinion first :-)

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 
> can you take a look at V.10? Following what you've mentioned earlier, here's an alternate design that I've come up with

Wait, I already gave my opinion on the design right from the beginning, no? `preprocessUndoableCommand()` and having a flag that detects if the command is being run the first time or not are conceptually the same thing, and so have the same pros and cons.

**Comment by Zhiyuan-Amos** [comment]
@pyokagan 

> I don't quite get this question, btw. Are you asking e.g. if DeleteCommand has a new field personToDelete, should personToDelete be checked in DeleteCommand#equals(Object) as well?
Also, well, what do you think? You need to give your own opinion first :-)

Yup, that's what I meant; sorry for being unclear. 

1. It seems that for the rest of the code base, the `#equals(Object)` method considers all of the fields in the class. As such, it seems proper to consider `personToDelete` as well since it's a field in `DeleteCommand`.
1. However, `personToDelete` is not initialized till `preprocessUndoableCommand` is called. I'm not quite sure if there may be any issues here. One of my concerns is that:

i.e.:
```
DeleteCommand one = new DeleteCommand(Index.fromZeroBased(0));
DeleteCommand two = new DeleteCommand(Index.fromZeroBased(0));
two.execute();
one.equals(two); // returns false. This behavior is kinda unexpected.
```

However, it seems that there's no real need to compare the `personToDelete` since it's not exposed to the world; outside classes don't need to know that the internal representation consists of a `Person`.

The good thing about this design compared to the [previous](https://github.com/se-edu/addressbook-level4/pull/792#issuecomment-359314409) is that we no longer need complex preparations before executing tests.

@yamidark 

1. From what Paul has [commented](https://github.com/se-edu/addressbook-level4/pull/792#issuecomment-360159267), update the PR accordingly ya ^^ Sorry for giving the wrong instructions to not write tests ><
1. I think there's no real need to update `DeleteCommandSystemTest` & `EditCommandSystemTest`; the more complex cases should be performed on lower level tests (i.e. integration level tests). Wanna double check with @pyokagan if you are ok with this?
1. For RedoCommandTest, since we can call `preprocess...`, then we just need to add 2 lines of preprocessing.

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 

> However, it seems that there's no real need to compare the personToDelete since it's not exposed to the world; outside classes don't need to know that the internal representation consists of a Person.

Yes, outside classes don't need to know what exactly the internal fields of an object are. However, they do need to know that `DeleteCommand#execute()` needs to be called in order for subsequent undo/redo to work right?

As you pointed out, if we don't consider `personToDelete` in the `equals` method, we run into trouble in the following situation:
```
DeleteCommand one = new DeleteCommand(Index.fromZeroBased(0));
DeleteCommand two = new DeleteCommand(Index.fromZeroBased(0));
two.execute();
one.equals(two); // true, implying that one and two are equivalent, yet:
runUndoCommand(two); // executes successfully
runUndoCommand(one); // does not execute successfully!??????
```

So yes, since `DeleteCommand` does leak the fact that it transitions between two states (executed and not-executed), this needs to be considered in its `equals` method as well.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 40]
```diff
@@ -89,6 +127,11 @@ public void equals() {
         DeleteCommand deleteFirstCommandCopy = new DeleteCommand(INDEX_FIRST_PERSON);
         assertTrue(deleteFirstCommand.equals(deleteFirstCommandCopy));
 
+        // command preprocessed -> returns false
+        deleteFirstCommandCopy.setData(model, new CommandHistory(), new UndoRedoStack());
+        deleteFirstCommandCopy.preprocessUndoableCommand();
+        assertFalse(deleteFirstCommand.equals(deleteFirstCommandCopy));
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: both copies should call `setData`, so that you can be sure the reason why both commands aren't `equal` is cos of `preprocessUndoableCommand()`

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 41]
```diff
@@ -78,7 +81,42 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        String expectedMessage = String.format(DeleteCommand.MESSAGE_DELETE_PERSON_SUCCESS, personToDelete);
+
+        ModelManager expectedModelBeforeDeleting = new ModelManager(model.getAddressBook(), new UserPrefs());
+        ModelManager expectedModelAfterDeleting = new ModelManager(model.getAddressBook(), new UserPrefs());
+        showSecondPersonOnly(expectedModelAfterDeleting);
+        expectedModelAfterDeleting.deletePerson(personToDelete);
+
+        // deleteCommand success, command gets pushed into undoRedoStack
+        assertCommandSuccess(deleteCommand, model, expectedMessage, expectedModelAfterDeleting);
+        undoRedoStack.push(deleteCommand);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: you should use the same `undoRedoStack` and `commandHistory` for all the commands in the test. Then you won't need to call this line right?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 42]
```diff
@@ -78,7 +81,42 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+
+        // list to show all persons after undoCommand successfully execute
+        expectedModelBeforeDeleting.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
+        assertCommandSuccess(undoCommand, model, UndoCommand.MESSAGE_SUCCESS, expectedModelBeforeDeleting);
+
+        // list to show all persons after redoCommand successfully execute
+        expectedModelAfterDeleting.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
+
+        // ensure personToDelete is different from first person in the unfiltered list
+        assertNotEquals(personToDelete, model.getFilteredPersonList().get(0));
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: your comments say `unfilteredList`, but you are calling `model.getFilteredPersonList()` :P

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 43]
```diff
@@ -78,7 +81,42 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        // deleteCommand success, command gets pushed into undoRedoStack
+        assertCommandSuccess(deleteCommand, model, expectedMessage, expectedModelAfterDeleting);
+        undoRedoStack.push(deleteCommand);
+
+        // list to show all persons after undoCommand successfully execute
+        expectedModelBeforeDeleting.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
+        assertCommandSuccess(undoCommand, model, UndoCommand.MESSAGE_SUCCESS, expectedModelBeforeDeleting);
+
+        // list to show all persons after redoCommand successfully execute
+        expectedModelAfterDeleting.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: this should be joined with the test below since you don't have any verifications here.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 44]
```diff
@@ -78,7 +81,42 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        ModelManager expectedModelAfterDeleting = new ModelManager(model.getAddressBook(), new UserPrefs());
+        showSecondPersonOnly(expectedModelAfterDeleting);
+        expectedModelAfterDeleting.deletePerson(personToDelete);
+
+        // deleteCommand success, command gets pushed into undoRedoStack
+        assertCommandSuccess(deleteCommand, model, expectedMessage, expectedModelAfterDeleting);
+        undoRedoStack.push(deleteCommand);
+
+        // list to show all persons after undoCommand successfully execute
+        expectedModelBeforeDeleting.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: hmm you don't need this line cos `expectedModelBeforeDeleting` is not modified from the time it's initialized right?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 45]
```diff
@@ -80,6 +80,50 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+
+    @Test
+    public void undoRedo_deleteCommandFailure_failure() {
+        UndoCommand undoCommand = new UndoCommand();
+        RedoCommand redoCommand = new RedoCommand();
+        UndoRedoStack undoRedoStack = new UndoRedoStack();
+        undoCommand.setData(model, new CommandHistory(), undoRedoStack);
+        redoCommand.setData(model, new CommandHistory(), undoRedoStack);
+
+        Index outOfBoundIndex = Index.fromOneBased(model.getFilteredPersonList().size() + 1);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: why not create the `Index` `fromZeroBased` so that you do not have to add 1? :P

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 46]
```diff
@@ -80,6 +80,50 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        DeleteCommand deleteCommand = prepareCommand(outOfBoundIndex);
+
+        // deleteCommand failed, command not pushed into undoRedoStack
+        assertCommandFailure(deleteCommand, model, Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: `deleteCommand` is using a different `undoRedoStack` btw, so it's buggy here :P

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 47]
```diff
@@ -80,6 +80,50 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+
+        String expectedMessage = String.format(DeleteCommand.MESSAGE_DELETE_PERSON_SUCCESS, personToDelete);
+
+        ModelManager expectedModelBeforeDeleting = new ModelManager(model.getAddressBook(), new UserPrefs());
+        ModelManager expectedModelAfterDeleting = new ModelManager(model.getAddressBook(), new UserPrefs());
+        expectedModelAfterDeleting.deletePerson(personToDelete);
+
+        // deleteCommand success, command gets pushed into undoRedoStack
+        assertCommandSuccess(deleteCommand, model, expectedMessage, expectedModelAfterDeleting);
+        undoRedoStack.push(deleteCommand);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: see [2/5]

**Comment by Zhiyuan-Amos** [comment]
@pyokagan Is this design acceptable to you? ^^

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 45 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: > why not create the Index fromZeroBased so that you do not have to add 1? :P

copied this from the previous tests above. xD

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 43 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Would it be better if I separate and move the `assertNotEquals(personToDelete, model.getAddressBook().getPersonList().get(0))` test to the beginning instead?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 42 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >your comments say unfilteredList, but you are calling model.getFilteredPersonList() :P

The other test names has `unfilteredList` in them too but they also call `model.getFilteredPersonList()` :O.  Perhaps we change those over to `model.getAddressBook.getPersonList()` too (in a different issue)?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 46 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >deleteCommand is using a different undoRedoStack btw, so it's buggy here :P

As mentioned above, `deleteCommand` does not use the `undoRedoStack`, thus it shouldn't matter here too.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 43 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Hmm because the `model` is being updated as the tests proceed, so it seems better to perform this verification right before we redo.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 45 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: ok then! ^^

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 42 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Actually, this comment is unnecessary because it's simply repeating what `assertNotEquals` is doing right? :P

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 48]
```diff
@@ -78,7 +81,42 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
     }
 
     @Test
-    public void equals() {
+    public void undoRedo_filteredList_samePersonDeleted() throws Exception {
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: since the focus of this test is on the interactions of `DeleteCommand` with `UndoCommand` and `RedoCommand` (i.e. the verification of `DeleteCommand` is already performed in other tests), let's remove line 103. I.e. we simply call `deleteCommand.execute()` instead. This should result in some other lines that can be removed, such as line 95.

Also, lines 85-100 is all about preparing for the upcoming tests, which is quite a lot of lines (16 lines! :O) Let's group them together instead of segmenting them with new lines, otherwise it's kinda unclear when your actual test is starting. 

Also, for the creation of `UndoRedoStack`, let's try to use `UndoRedoStackUtil#prepareStack(...)` to create instead.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 41 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Ah I see, noted!

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 49]
```diff
@@ -78,7 +81,86 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        // deleteCommand failed, command not pushed into undoRedoStack
+        assertCommandFailure(deleteCommand, model, Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
+
+        // no commands in undoRedoStack, undoCommand and redoCommand fail
+        assertCommandFailure(undoCommand, model, UndoCommand.MESSAGE_FAILURE);
+        assertCommandFailure(redoCommand, model, RedoCommand.MESSAGE_FAILURE);
+    }
+
+    @Test
+    public void undoRedo_filteredList_samePersonDeleted() throws Exception {
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: since the focus of this test is on the interactions of `DeleteCommand` with `UndoCommand` and `RedoCommand` (i.e. the verification of `DeleteCommand` is already performed in other tests), let's remove line 103. I.e. we simply call `deleteCommand.execute()` instead. This should result in some other lines that can be removed, such as line 95.

Also, lines 85-100 is all about preparing for the upcoming tests, which is quite a lot of lines (16 lines! :O) Let's group them together instead of segmenting them with new lines, otherwise it's kinda unclear when your actual test is starting. 

Also, for the creation of `UndoRedoStack`, let's try to use `UndoRedoStackUtil#prepareStack(...)` to do so instead.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 42 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >Actually, this comment is unnecessary because it's simply repeating what assertNotEquals is doing right? :P

Now that you mention it, yep your right xD; so should I still switch over to `model.getAddressBook.getPersonList()` then?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 43 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >Hmm because the model is being updated as the tests proceed, so it seems better to perform this verification right before we redo.

sounds good; I just mix the 2 tests together?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 48 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >we simply call deleteCommand.execute() instead. This should result in some other lines that can be removed, such as line 95.

Hmm, if we just call `deleteCommand#execute()`, then we probably can just keep 1 `expectedModel` which does the delete/edit before testing `redo()` instead. Probably would be much neater too?

>Also, lines 85-100 is all about preparing for the upcoming tests, which is quite a lot of lines 

Perhaps we can also move the `UndoCommand`, `RedoCommand` and `UndoRedoStack` to the top global variables instead (which would remove lots of lines), but they won't be used for the other tests though

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 42 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: hmm nope, because the main issue we are trying to resolve is that: If the `filteredList` changes, the original `delete` and the `redo` ought to delete the same person. So you should get the person from `filteredList`.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 48 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: You can try, we'll see how it goes :P

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 43 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Can you help to check whether we use `assert !=` or `assertNotEquals` in the test code? Cos over here we are verifying an assumption first (i.e. sounds like we should use `assert !=` instead) before executing the `redoCommand`, otherwise the test will be meaningless.

Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: I thought we use assert for main and junit assertion for test? because assert can be turned off in the settings or something.

Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Edit: nvm I see some `assert` in addressbook system test lol

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: we turn off `assert` in mainly in production, but not for testing I think. :P

Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >we turn off assert in mainly in production, but not for testing I think. :P

Yup, which is why it was weird when I found some methods in `AddressBookSystemTest`. Perhaps we should create an issue to clean them all up?

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: @eugenepeh I updated my comment above ^^ So we should clean them all up by replacing `assert` with `Assert*`.

Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Opened issue #814

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 50]
```diff
@@ -24,6 +24,12 @@ private void saveAddressBookSnapshot() {
         this.previousAddressBook = new AddressBook(model.getAddressBook());
     }
 
+    /**
+     * Preprocess the UndoableCommand if necessary.
+     * UndoableCommands that require this preprocessing step should override this method.
+     */
+    protected void preprocessUndoableCommand() throws CommandException {}
```
[the remark this answers is not in the document]
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/UndoableCommand.java]: @yamidark delete this comment for this iteration and future iterations of this PR ya, cos this comment isn't helpful ^^

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 51]
```diff
@@ -89,6 +125,12 @@ public void equals() {
         DeleteCommand deleteFirstCommandCopy = new DeleteCommand(INDEX_FIRST_PERSON);
         assertTrue(deleteFirstCommand.equals(deleteFirstCommandCopy));
 
+        // command preprocessed -> returns false
+        deleteFirstCommand.setData(model, new CommandHistory(), new UndoRedoStack());
+        deleteFirstCommandCopy.setData(model, new CommandHistory(), new UndoRedoStack());
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: actually you can just update the above initialization code to call `prepareCommand`, so you don't need to `setData` here.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 52]
```diff
@@ -78,7 +95,26 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
     }
 
     @Test
-    public void equals() {
+    public void undoRedo_filteredList_samePersonDeleted() throws Exception {
+        showSecondPersonOnly(model);
```
[the remark this answers is not in the document]
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Also, I'm not sure how we can do it, but we need to make it clear why we are specifically crafting our test this way.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 47 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Let's do the init here using `UndoRedoStackUtil` too :)

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 53]
```diff
@@ -94,6 +94,35 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        assertCommandSuccess(redoCommand, model, RedoCommand.MESSAGE_SUCCESS, expectedModel);
+    }
+
+    @Test
+    public void undoRedo_deleteCommandFailureUnfilteredList_failure() {
+        Index outOfBoundIndex = Index.fromOneBased(model.getFilteredPersonList().size() + 1);
+        DeleteCommand deleteCommand = prepareCommand(outOfBoundIndex);
+
+        // deleteCommand failed, command not pushed into undoRedoStack
+        assertCommandFailure(deleteCommand, model, Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: it's weird that you are calling `deleteCommand#execute()` for the success case, but you are calling `assertCommandFailure` for the failure case :P

**Comment by Zhiyuan-Amos** [comment]
I will not review [3/5 and 5/5] yet cos they seem to be quite similar to [2/5 and 4/5] :)

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 53 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >it's weird that you are calling deleteCommand#execute() for the success case, but you are calling assertCommandFailure for the failure case :P

If the execution fails, a `CommandException` gets thrown which needed to be handled/caught somewhere, else the test will automatically fail at that point :X 
This may also make it clearer that the command fails?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 52 above)
[the remark this answers is not in the document]
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >Also, I'm not sure how we can do it, but we need to make it clear why we are specifically crafting our test this way.

Add a comment on top of `showSecondPerson(Model)` that we want to delete/edit a `Person` which has different indexing from the unfiltered list to ensure we delete by `Person` and not by `Index` during `undo()`/`redo()`?

[the remark this answers is not in the document]
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Perhaps we can put header comments for this test, since the 3-parts test method name `foo_bar_baz` isn't sufficient to inform readers what we are specifically testing for ^^

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 54]
```diff
@@ -78,7 +95,26 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+    public void undoRedo_filteredList_samePersonDeleted() throws Exception {
+        showSecondPersonOnly(model);
+
+        Person personToDelete = model.getFilteredPersonList().get(0);
+        DeleteCommand deleteCommand = prepareCommand(INDEX_FIRST_PERSON);
+        ModelManager expectedModel = new ModelManager(model.getAddressBook(), new UserPrefs());
+
+        // deleteCommand success, command gets pushed into undoRedoStack
+        deleteCommand.execute();
+        undoRedoStack.push(deleteCommand);
```
[the remark this answers is not in the document]
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Hmm hang on. Now that I think about it, I'm not sure whether this operation is safe, because technically we can `push` a command into `undoRedoStack` even though the execution is unsuccessful. E.g. in [commit 4](https://github.com/se-edu/addressbook-level4/pull/792/commits/f0d1dee45d14c69826233a428f81e77590c078c9#diff-4aa04d3892581d741aded0911f524ab1R118).

Any ideas how we can resolve this?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 53 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Since we've already tested for the failure of `DeleteCommand` execution in other tests, I'm thinking of doing:

```java
try {
    deleteCommand.execute():
    fail();
} catch (CommandException ce) {
    // expected
}
```

Hmm. Looks ugly though o.o But it's weird to call `assertCommandFailure` for `deleteCommand`, when we don't do `assertCommandSuccess` in the other tests :P

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 47 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Hmm, following what I [mentioned](https://github.com/se-edu/addressbook-level4/pull/792#discussion_r164614352), I think it may be better to call `push` then to init with `UndoRedoStackUtil`, because we are trying to simulate the action of the `LogicManager` that a command is pushed only when the execution is successful.

**Comment by pyokagan** [comment]
Sorry, I've suddenly hit a busy period in my work so I'll have to disappear for a while.

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 55]
```diff
@@ -24,22 +24,15 @@
...
-
-        List<Person> lastShownList = model.getFilteredPersonList();
-
-        if (targetIndex.getZeroBased() >= lastShownList.size()) {
-            throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
-        }
-
-        Person personToDelete = lastShownList.get(targetIndex.getZeroBased());
-
         try {
```
Comment (yamidark) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java]: Actually should I add a '`requireNonNull(Person)` check here, just to ensure we have to execute `preprocessUndoableCommand()` first and prevent somehow adding a `null` value into the person list?

Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/DeleteCommand.java]: Yup! 👍

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 54 above)
[the remark this answers is not in the document]
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >Hmm, following what I mentioned, I think it may be better to call push then to init with UndoRedoStackUtil, because we are trying to simulate the action of the LogicManager that a command is pushed only when the execution is successful.

Do I just revert back to `new UndoRedoStack()`  in this case?

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 56]
```diff
@@ -49,10 +42,33 @@ public CommandResult executeUndoableCommand() throws CommandException {
...
+        // instanceof handles nulls
+        if (!(other instanceof DeleteCommand)) {
+            return false;
+        }
+
+        // state check
+        DeleteCommand d = (DeleteCommand) other;
+        return targetIndex.equals(d.targetIndex)
+                && ((personToDelete == null && d.personToDelete == null)
+                    || (personToDelete != null && d.personToDelete != null && personToDelete.equals(d.personToDelete)));
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java]: Lots of unnecessary changes here. It'll be better to add a separate commit that modifies *all* the `#equals()` in the code base.

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 57]
```diff
@@ -119,7 +125,9 @@ public boolean equals(Object other) {
         // state check
         EditCommand e = (EditCommand) other;
         return index.equals(e.index)
-                && editPersonDescriptor.equals(e.editPersonDescriptor);
+                && editPersonDescriptor.equals(e.editPersonDescriptor)
+                && ((personToEdit == null && e.personToEdit == null)
+                    || (personToEdit != null && e.personToEdit != null && personToEdit.equals(e.personToEdit)));
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: `Object.equals(personToEdit, e.personToEdit)`

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 58]
```diff
@@ -24,6 +24,8 @@ private void saveAddressBookSnapshot() {
         this.previousAddressBook = new AddressBook(model.getAddressBook());
     }
 
+    protected void preprocessUndoableCommand() throws CommandException {}
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: This needs a javadoc that explains when `preprocessUndoableCommand()` is called (and when it is not called).

e.g. similar to the explanations in the [Android lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle.html)

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 59]
```diff
@@ -117,6 +117,17 @@ public static void showFirstPersonOnly(Model model) {
...
 
+    /**
+     * Updates {@code model}'s filtered list to show only the second person in the {@code model}'s address book.
+     */
+    public static void showSecondPersonOnly(Model model) {
+        Person person = model.getAddressBook().getPersonList().get(1);
+        final String[] splitName = person.getName().fullName.split("\\s+");
+        model.updateFilteredPersonList(new NameContainsKeywordsPredicate(Arrays.asList(splitName[0])));
+
+        assert model.getFilteredPersonList().size() == 1;
```
Comment (pyokagan) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: Exact copy of `showFirstPersonOnly()` :-( I hope this can be cleaned up in this PR or soonish.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 53 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >Hmm. Looks ugly though o.o But it's weird to call assertCommandFailure for deleteCommand, when we don't do assertCommandSuccess in the other tests :P

Yep looks ugly; not sure how to resolve this though 😓. Should I just leave it like this for now?

File: src/test/java/seedu/address/logic/commands/RedoCommandTest.java [hunk 60]
```diff
@@ -25,12 +26,14 @@
...
-    private final DeleteCommand deleteCommandTwo = new DeleteCommand(INDEX_FIRST_PERSON);
+    private final DeleteCommand deleteCommandTwo = new DeleteCommand(INDEX_SECOND_PERSON);
 
     @Before
-    public void setUp() {
+    public void setUp() throws Exception {
         deleteCommandOne.setData(model, EMPTY_COMMAND_HISTORY, EMPTY_STACK);
         deleteCommandTwo.setData(model, EMPTY_COMMAND_HISTORY, EMPTY_STACK);
+        deleteCommandOne.preprocessUndoableCommand();
+        deleteCommandTwo.preprocessUndoableCommand();
```
Comment (pyokagan) [inline src/test/java/seedu/address/logic/commands/RedoCommandTest.java]: Is `preprocessUndoableCommand()` meant to be a method that can be called directly by outsiders? I thought this is using the template pattern?

**Comment by pyokagan** [comment]
@Zhiyuan-Amos Perhaps it might be a good idea to move the responsibility of updating the `undoRedoStack` from `LogicManager` to `UndoableCommand` itself, if it would make the API more easily testable. After all, Commands are already able to modify the `undoRedoStack` (e.g. `UndoCommand` and `RedoCommand`)

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 53 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: just leave it first for now then ^^

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java (hunk 59 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: @yamidark maybe can update the existing method name to be something like `showPersonAtIndex(Model, Index)`. :)

File: src/test/java/seedu/address/logic/commands/RedoCommandTest.java (hunk 60 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/RedoCommandTest.java]: It's `protected` because sub-classes need to override it. Since the test code and the main code are in the same package, `RedoCommandTest` can call it directly. 

Is this wrong though? :O

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 57 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: Oh right 👍 . Side note, it's `Objects` though :P

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 54 above)
[the remark this answers is not in the document]
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: It's ok; I deleted this comment because I thought it doesn't make that much of a difference, whether we `init then push`, or `init with the command already inside`.

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java (hunk 59 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: >maybe can update the existing method name to be something like showPersonAtIndex(Model, Index). :)

Noted. Will do that in an earlier commit

**Comment by Zhiyuan-Amos** [comment]
> @Zhiyuan-Amos Perhaps it might be a good idea to move the responsibility of updating the undoRedoStack from LogicManager to UndoableCommand itself, if it would make the API more easily testable. After all, Commands are already able to modify the undoRedoStack (e.g. UndoCommand and RedoCommand)

Oh wow, sounds good. @yamidark do take note of this. As `UndoRedoStack#push(Command)` takes in a `Command` and performs some action depending on whether it's a `Command` or `UndoableCommand`, we can shift the updating of `undoRedoStack` to `Command`. I think it will look something like this:

1. Update `setData` to assign `undoRedoStack` in `Command` since now all commands need to update `undoRedoStack`.
1. Remove updating of `undoRedoStack` in `LogicManager`.
1. Implement template pattern in `Command#execute()` to call `undoRedoStack#push(Command)`.

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 

> As UndoRedoStack#push(Command) takes in a Command and performs some action depending on whether it's a Command or UndoableCommand, we can shift the updating of undoRedoStack to Command

I didn't think it too thoroughly, can drop the idea if it is too complicated. Anyway, might be out of scope for this PR.

File: src/test/java/seedu/address/logic/commands/RedoCommandTest.java (hunk 60 above)
Comment (pyokagan) [reply src/test/java/seedu/address/logic/commands/RedoCommandTest.java]: @Zhiyuan-Amos 

> Is this wrong though? :O

You tell me ;-). Are you designing `UndoableCommand` such that its `UndoableCommand#preprocessUndoableCommand()` can be called by outsiders directly? If so, then it should be probably be `public`. If not, the usage of directly calling `preprocessUndoableCommand()` here is bypassing the encapsulation?

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/RedoCommandTest.java]: Since `preprocessUndoableCommand()` is being used as part of the Template Pattern, it needs to be overwritten by subclasses, and so we assign it with a `protected` visibility modifier.

So, it should not be able to be called by outsiders directly. 

It's not alright for us to bypass encapsulation for tests for the purpose of having an easier test setup? I initially thought that it was fine, otherwise setting up for this test would be pretty untidy. The reason why we switched to this method was that the previous way of doing so would result in untidy tests setup :(

**Comment by Zhiyuan-Amos** [comment]
> As UndoRedoStack#push(Command) takes in a Command and performs some action depending on whether it's a Command or UndoableCommand, we can shift the updating of undoRedoStack to Command

@yamidark if you haven't fully implemented this, we can do it in a separate PR. You can store the changes that you've made in a separate branch ^^. Perhaps during then, we will one-shot perform this change and update all the tests accordingly.

File: src/test/java/seedu/address/logic/commands/RedoCommandTest.java (hunk 60 above)
Comment (pyokagan) [reply src/test/java/seedu/address/logic/commands/RedoCommandTest.java]: @Zhiyuan-Amos 
> It's not alright for us to bypass encapsulation for tests for the purpose of having an easier test setup?

The Internet has a few opinions on this topic, e.g. https://stackoverflow.com/questions/23702784/when-is-it-appropriate-to-bypass-encapsulation-in-unit-tests

Anyway, just make it the last *last* resort (and maybe mark it with a `TODO`). Ask @damithc , or the people from TEAMMATES, PowerPointLabs etc. for their help if necessary.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 61]
```diff
@@ -84,6 +84,40 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
         assertCommandFailure(deleteCommand, model, Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
     }
 
+    @Test
+    public void undoRedo_deleteCommandSuccessUnfilteredList_success() throws Exception {
+        UndoRedoStack undoRedoStack = UndoRedoStackUtil.prepareStack(Collections.emptyList(), Collections.emptyList());
+        UndoCommand undoCommand = prepareUndoCommand(model, undoRedoStack);
+        RedoCommand redoCommand = prepareRedoCommand(model, undoRedoStack);
+        Person personToDelete = model.getFilteredPersonList().get(0);
```
Comment (eugenepeh) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: should follow the style of other test cases `model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());`

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 62]
```diff
@@ -84,6 +84,40 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        DeleteCommand deleteCommand = prepareCommand(INDEX_FIRST_PERSON);
+        ModelManager expectedModel = new ModelManager(model.getAddressBook(), new UserPrefs());
```
Comment (eugenepeh) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: is there any reason why some `expectedModel` are initialized as `ModelManager` instead of `Model`?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 63]
```diff
@@ -84,6 +84,40 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+
+        deleteCommand.execute();
```
Comment (eugenepeh) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: can add some comments, to explain why this is necessary, for new developers

File: src/test/java/seedu/address/logic/commands/EditCommandTest.java [hunk 64]
```diff
@@ -147,18 +153,48 @@ public void execute_invalidPersonIndexFilteredList_failure() {
...
+        showPersonAtIndex(model, INDEX_SECOND_PERSON);
+        Person personToEdit = model.getFilteredPersonList().get(0);
+        editCommand.execute();
+        undoRedoStack.push(editCommand);
+
+        assertCommandSuccess(undoCommand, model, UndoCommand.MESSAGE_SUCCESS, expectedModel);
+
+        expectedModel.updatePerson(personToEdit, editedPerson);
+        assertNotEquals(model.getFilteredPersonList().get(0), personToEdit);
+        assertCommandSuccess(redoCommand, model, RedoCommand.MESSAGE_SUCCESS, expectedModel);
```
Comment (eugenepeh) [inline src/test/java/seedu/address/logic/commands/EditCommandTest.java]: takes a while to understand what the entire test is trying to do, perhaps can add some header comments to help?

E.g. `// redo -> edits second person in unfiltered person list`

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 62 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >is there any reason why some expectedModel are initialized as ModelManager instead of Model?

Nope, copied this part from the first test in `DeleteCommandTest` and didn't notice the difference :O. Will change it back to `Model`.

**Comment by yamidark** [comment]
@damithc @Zhiyuan-Amos 

Summary of what have been done/tried so far:

Our initial design was to get and save the `predicate` of the `filteredPersonList` together with the `AddressBook` state before calling `executeUndoableCommand()` in the `execute()` method. We then restored the `filteredPersonList` view with the stored predicate right before re-executing the command in `redo()`, thus ensuring the `Index` of the `Person` deleted or edited will be the same as initial execution.

However, this design results in dependency on the `redo()` method to require calling `execute()` first in order to get and save the non-`null` `predicate` first since our code base does not handle `null` `predicates`. This results in lots of preparation code required for the unit tests of `RedoCommandTest`. We first have to set-up the `RedoCommand` and `UndoCommand`, then call `execute()` and `undo()` for the command before we are able to test the `redo()` method. 

```Java
UndoRedoStack undoRedoStackOne = prepareStack(
                Arrays.asList(deleteCommandOne, deleteCommandTwo), Collections.emptyList());
        UndoRedoStack undoRedoStackTwo = prepareStack(
                Collections.emptyList(), Arrays.asList(deleteCommandTwo, deleteCommandOne));
        UndoCommand undoCommand = new UndoCommand();
        RedoCommand redoCommand = new RedoCommand();
        undoCommand.setData(model, EMPTY_COMMAND_HISTORY, undoRedoStackOne);
        redoCommand.setData(model, EMPTY_COMMAND_HISTORY, undoRedoStackTwo);
        Model expectedModel = new ModelManager(getTypicalAddressBook(), new UserPrefs());

        // run the commands first to save their states
        deleteCommandOne.execute();
        deleteCommandTwo.execute();

        // revert back to original state
        undoCommand.execute();
        undoCommand.execute();
```
One suggested way to simplify the code and allow unit testing of `RedoCommandTest` was to use Java.Reflection to initialize a default non-`null` `predicate` value. This however bypasses the class's encapsulation, which leads to bad practice as future developers may abuse this and end up building bad API designs.

We then switched over to a different design, where we implement a new method `preprocessUndoableCommand()` to be called before `executeUndoableCommand()` in the `execute()` method. This allows `DeleteCommand` and `EditCommand` to get and save the `personToDelete` or `personToEdit`, so that all executions of the same command will result in the same `Person` to be deleted/edited.

However, this design also has the same problems as the previous design, where we are required to call `execute()` first in order to call `preprocessUndoableCommand()` and save the `personToDelete` or `personToEdit`. This would lead to the same preparation code required for unit tests of `RedoCommand`, thus not resolving our problem.

One suggested way to resolve this was to replace the `DeleteCommand` used in `RedoCommandTest` with an `UndoableCommand` that does not require/override `preprocessUndoableCommand()`, such as `AddCommand`. This, however, also leads to messy code, and we can't really justify switching over to `AddCommand`.

Our current implementation calls the protected `preprocessUndoableCommand()` directly for the unit tests since they are in the same `seedu.address.logic.commands` package. This however still breaks class's encapsulation and thus is not desirable.

File: src/test/java/seedu/address/logic/commands/RedoCommandTest.java (hunk 60 above)
Comment (damithc) [reply src/test/java/seedu/address/logic/commands/RedoCommandTest.java]: I don't think TEAMMATES or PowerPointLabs has any better expertise on this aspect. :-p 
I have no objections to using protected methods for testing, at least for the time being. Although not ideal, easy access to protected methods is one reason why we put the test classes in the same package as the SUT class.

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/RedoCommandTest.java]: Thanks for your thoughts on this issue @damithc & @pyokagan, insightful indeed  :)

**Comment by Zhiyuan-Amos** [comment]
@yamidark following what prof mentioned [above](https://github.com/se-edu/addressbook-level4/pull/792#discussion_r166643920), let's continue working in this direction and let's try to get this merged before the weekend ^^ I'll review once you submit the next iteration (since you've already made modifications on some of the commits, I'm unable to access the commit at CanIHasReview).

File: src/main/java/seedu/address/logic/commands/UndoableCommand.java [hunk 65]
```diff
@@ -24,6 +24,12 @@ private void saveAddressBookSnapshot() {
         this.previousAddressBook = new AddressBook(model.getAddressBook());
     }
 
+    /**
+     * Called before executing the {@code UndoableCommand}
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/commands/UndoableCommand.java]: `This method is called before the execution of {@code UndoableCommand}.`

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 66]
```diff
@@ -107,10 +109,13 @@ public static void assertCommandFailure(Command command, Model actualModel, Stri
...
 
     /**
-     * Updates {@code model}'s filtered list to show only the first person in the {@code model}'s address book.
+     * Updates {@code model}'s filtered list to show only the person at the given {@code targetIndex} in the
+     * {@code model}'s address book.
      */
-    public static void showFirstPersonOnly(Model model) {
-        Person person = model.getAddressBook().getPersonList().get(0);
+    public static void showPersonAtIndex(Model model, Index targetIndex) {
+        assertTrue(targetIndex.getOneBased() < model.getFilteredPersonList().size());
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: why use one-based to compare with zero-based list? :P

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 67]
```diff
@@ -107,10 +109,13 @@ public static void assertCommandFailure(Command command, Model actualModel, Stri
...
+
+        Person person = model.getAddressBook().getPersonList().get(targetIndex.getZeroBased());
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: Why check for filtered list size, but get address book here?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 62 above)
Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: ping

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 68]
```diff
@@ -84,6 +84,43 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
         assertCommandFailure(deleteCommand, model, Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
     }
 
+    @Test
+    public void undoRedo_deleteCommandSuccessUnfilteredList_success() throws Exception {
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: executeUndoRedo_validIndexUnfilteredList_success

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 69]
```diff
@@ -84,6 +84,43 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        UndoRedoStack undoRedoStack = UndoRedoStackUtil.prepareStack(Collections.emptyList(), Collections.emptyList());
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: if you are creating an empty stack, then you can just use the constructor right haha

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 70]
```diff
@@ -84,6 +84,43 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+
+    @Test
+    public void undoRedo_deleteCommandFailureUnfilteredList_failure() {
+        UndoRedoStack undoRedoStack = UndoRedoStackUtil.prepareStack(Collections.emptyList(), Collections.emptyList());
+        UndoCommand undoCommand = prepareUndoCommand(model, undoRedoStack);
+        RedoCommand redoCommand = prepareRedoCommand(model, undoRedoStack);
+        Index outOfBoundIndex = Index.fromOneBased(model.getFilteredPersonList().size() + 1);
+        DeleteCommand deleteCommand = prepareCommand(outOfBoundIndex);
+
+        // deleteCommand failed, command not pushed into undoRedoStack
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: execution failed -> DeleteCommand not...

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 71]
```diff
@@ -84,6 +84,43 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        assertCommandFailure(deleteCommand, model, Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
+
+        // no commands in undoRedoStack, undoCommand and redoCommand fail
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: no commands in undoRedoStack -> undoCommand...

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 72]
```diff
@@ -133,4 +135,22 @@ public static void deleteFirstPerson(Model model) {
             throw new AssertionError("Person in filtered list must exist in model.", pnfe);
         }
     }
+
+    /**
+     * Returns an {@code UndoCommand} with the given {@code Model} and {@code UndoRedoStack} set.
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: lower case for model and undoRedoStack.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 73]
```diff
@@ -77,18 +84,49 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
         assertCommandFailure(deleteCommand, model, Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
     }
 
+    /**
+     * Delete a {@code Person} with different indexing from the unfiltered list to ensure {@code RedoCommand} deletes
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Deletes.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 74]
```diff
@@ -77,18 +84,49 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+     * by {@code Person} and not by {@code Index} during re-execution.
+     */
+    @Test
+    public void undoRedo_filteredList_samePersonDeleted() throws Exception {
+        UndoRedoStack undoRedoStack = UndoRedoStackUtil.prepareStack(Collections.emptyList(), Collections.emptyList());
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: use constructor instead.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 75]
```diff
@@ -77,18 +84,49 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        UndoCommand undoCommand = prepareUndoCommand(model, undoRedoStack);
+        RedoCommand redoCommand = prepareRedoCommand(model, undoRedoStack);
+        DeleteCommand deleteCommand = prepareCommand(INDEX_FIRST_PERSON);
+        Model expectedModel = new ModelManager(model.getAddressBook(), new UserPrefs());
+
+        showPersonAtIndex(model, INDEX_SECOND_PERSON);
+        Person personToDelete = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());
+        // delete -> deletes second person in unfiltered person list/first person in filtered person list
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: list / first (add 2 spaces)

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 76]
```diff
@@ -133,4 +135,22 @@ public static void deleteFirstPerson(Model model) {
...
+    public static UndoCommand prepareUndoCommand(Model model, UndoRedoStack undoRedoStack) {
+        UndoCommand undoCommand = new UndoCommand();
+        undoCommand.setData(model, new CommandHistory(), undoRedoStack);
+        return undoCommand;
+    }
+
+    /**
+     * Returns a {@code RedoCommand} with the given {@code model} and {@code undoRedoStack} set.
+     */
+    public static RedoCommand prepareRedoCommand(Model model, UndoRedoStack undoRedoStack) {
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: Maybe we can merge these methods.
`prepareCommand(Class commandClass, Model model, UndoRedoStack undoRedoStack)`. Not too sure tho x.x

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 77]
```diff
@@ -77,18 +81,49 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+        expectedModel.deletePerson(personToDelete);
+        assertNotEquals(personToDelete, model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased()));
+        // redo -> deletes same second person in unfiltered person list
+        assertCommandSuccess(redoCommand, model, RedoCommand.MESSAGE_SUCCESS, expectedModel);
+    }
+
+    @Test
+    public void equals() throws Exception {
+        DeleteCommand deleteFirstCommand = prepareCommand(INDEX_FIRST_PERSON);
+        DeleteCommand deleteSecondCommand = prepareCommand(INDEX_SECOND_PERSON);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: is this used? Doesn't seem to be used here XD

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 78]
```diff
@@ -77,18 +81,49 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
 
         // same object -> returns true
         assertTrue(deleteFirstCommand.equals(deleteFirstCommand));
 
         // same values -> returns true
-        DeleteCommand deleteFirstCommandCopy = new DeleteCommand(INDEX_FIRST_PERSON);
+        DeleteCommand deleteFirstCommandCopy = prepareCommand(INDEX_FIRST_PERSON);
         assertTrue(deleteFirstCommand.equals(deleteFirstCommandCopy));
 
+        // command preprocessed -> returns false
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: this comment should be more descriptive because it doesn't clarify whether both commands are preprocessed, or only 1 command is preprocessed.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 79]
```diff
@@ -77,18 +81,49 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
         assertCommandFailure(deleteCommand, model, Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
     }
 
+    /**
+     * Deletes a {@code Person} with different indexing from the unfiltered list to ensure {@code RedoCommand} deletes
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: > Deletes a {@code Person} with different indexing from the unfiltered list

This isn't clear. I'm not sure, but maybe we can do something like:
```
1. Deletes a {@code Person} from a filtered list.
2. Undo the deletion.
3. The unfiltered list should be shown now. Verify that the index of the previously deleted person in the unfiltered list is different to the index at the filtered list.
4. Redo the deletion. This ensures {@code RedoCommand} deletes the person object regardless of indexing.
```

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java (hunk 76 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: Will try this in my next iteration.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 77 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]:
```
    // different person -> returns false
    assertFalse(deleteFirstCommand.equals(deleteSecondCommand));
}
```
used in the very last line of the test (old test) :O.

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java (hunk 76 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: Tried something like this:
```Java
public static<T extends Command> T prepareUndoRedoCommand(Class<? extends Command> commandClass, Model model,
                                             UndoRedoStack undoRedoStack) throws Exception {
        Command command = commandClass.getConstructor().newInstance();
        command.setData(model, new CommandHistory(), undoRedoStack);
        return (T) command;
    }
```
Can't use `prepareCommand` as the name since `DeleteCommandTest` and `EditCommandTest` has it for their own commands.
Looks quite ugly to me though =x.
What's your opinion?

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: Ok let's revert this then.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 80]
```diff
@@ -81,6 +81,43 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
         assertCommandFailure(deleteCommand, model, Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
     }
 
+    @Test
+    public void executeUndoRedo_validIndexUnfilteredList_success() throws Exception {
+        UndoRedoStack undoRedoStack = new UndoRedoStack();
+        UndoCommand undoCommand = prepareUndoCommand(model, undoRedoStack);
+        RedoCommand redoCommand = prepareRedoCommand(model, undoRedoStack);
+        Person personToDelete = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());
```
Comment (eugenepeh) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Hmm, method name says `validIndexUnfilteredList`  but you're working on `FilteredPersonList`?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java [hunk 81]
```diff
@@ -81,6 +81,43 @@ public void execute_invalidIndexFilteredList_throwsCommandException() {
...
+
+        // delete -> first person deleted
+        deleteCommand.execute();
+        undoRedoStack.push(deleteCommand);
+
+        // undo -> reverts addressbook back to previous state and filtered person list to show all persons
+        assertCommandSuccess(undoCommand, model, UndoCommand.MESSAGE_SUCCESS, expectedModel);
+
+        // redo -> same first person deleted again
+        expectedModel.deletePerson(personToDelete);
```
Comment (eugenepeh) [inline src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Can you include a test to check that the first person in filtered list and unfiltered list are different?

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: This test is executed on an unfiltered list, so the person being deleted should be on index 1 on both occasions. :)

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 80 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: If im not wrong, since we are doing assertion tests with the model and the integration tests for the interaction with the model, only the `filteredPersonList` should be visible and used by us even if its unfiltered. 

@Zhiyuan-Amos May I have your opinion on this? Not too sure if using `filteredPersonList` may confuse students. If we change this to `getAddressBook().getPersonList()` it would then be inconsistent with the other unfiltered tests in `EditCommandTest` and `DeleteCommandTest` which may also confuse students. Maybe we raise another issue to change all this?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 81 above)
Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: In that case, this test doesn't test for the issue earlier isnt it? where redo deletes the wrong person.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 80 above)
Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Actually what I mean is, the method name should be updated to `FilteredList` if you're wo`ing on `FilteredPersonList

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 81 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: the regression test which handles the issue of redo deletes wrong person is in [3/6] and [4/6].
[5/6] and [6/6] are just extra integration tests that I added in, which is why they are on an unfiltered list.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 80 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: As mentioned below, we are working on the unfiltered list here.

Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Hmm okay but its not intuitive enough to know whether we're working on the unfiltered or filtered list here because the exact same line of code 
`Person personToDelete = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());` was used in [3/6].

I assume in order to set filter for the person list, we need to execute the code `showPersonAtIndex(model, INDEX_SECOND_PERSON);`?

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 81 above)
Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: ok, my confusion comes from the part above.

File: src/test/java/seedu/address/logic/commands/DeleteCommandTest.java (hunk 80 above)
Comment (yamidark) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: >I assume in order to set filter for the person list, we need to execute the code
showPersonAtIndex(model, INDEX_SECOND_PERSON);?

Yep.

iirc, we placed the line `Person personToDelete = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());` for the filtered list right after we call `showPersonAtIndex(model, INDEX_SECOND_PERSON);` instead of at the top as we thought it would be clearer that we are working on the filtered list, and to prevent too much preparation line codes at the top.

Would putting this back on the top make it clearer like in `execute_validIndexFilteredList_success()`? 
Or maybe we shift the line `DeleteCommand deleteCommand = prepareCommand(INDEX_FIRST_PERSON);` down to be together with the `Person personToDelete = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());`?

Comment (eugenepeh) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: Okay actually my few concerns are:

- `model` is a global variable. Using `model.getFilteredPersonList()` will carry over state from previous tests, if theres any.
- The filter is set using the method `showPersonAtIndex(model, INDEX_SECOND_PERSON);` which is not very intuitive, by just looking at this implementation alone.
- Method name contains `validIndexUnfilteredList` but using `getFilteredPersonList()` method adds on to the confusion.

I would say, it would be better if there is a `getUnfilteredPersonList()` method or comments that do the explanation. I would prefer the first over latter.

@Zhiyuan-Amos , what do you think?

Comment (Zhiyuan-Amos) [reply src/test/java/seedu/address/logic/commands/DeleteCommandTest.java]: > Method name contains validIndexUnfilteredList but using getFilteredPersonList() method adds on to the confusion.

Yup I think that using `getFilteredPersonList()` is quite confusing. But it seems that this issue should be resolved on the main code base side actually; `Logic` shouldn't be exposing that it's using a `filtered list` because there's no need to expose this information to the world. The View just simply needs a list to connect to.

So as of now, I'm ok with using `getFilteredPersonList()`, but we should rename this method eventually.

**Comment by Zhiyuan-Amos** [comment]
@eugenepeh thanks for reviewing! I can't imagine doing this alone :)

**Comment by Zhiyuan-Amos** [comment]
@damithc can I merge this PR now (or should I post on Gitter?) since it has been reviewed by Eugene, myself and yourself, and Paul has taken a look at the architecture in the earlier iterations already?

**Comment by yamidark** [comment]
@Zhiyuan-Amos Eh wait, I have not made the pushed the changes in commit message for [3/6] and [4/6]. Should I just push now and ask for another iteration?

**Comment by Zhiyuan-Amos** [comment]
> Eh wait, I have not made the pushed the changes in commit message for [3/6] and [4/6]. Should I just push now and ask for another iteration?

@yamidark yes, thanks for the reminder ^^

**Comment by damithc** [comment]
> @damithc can I merge this PR now (or should I post on Gitter?)

Let's follow the normal workflow. One more day is not going to make a big difference.

**Comment by Zhiyuan-Amos** [comment]
@yamidark [3/4] & [4/4] 3rd paragraphs do not match.

**Comment by eugenepeh** [comment]
Sorry @yamidark , some additional concerns of mine

>Hmm for [5/6] & [6/6] executeUndoRedo_validIndexUnfilteredList_success, on second thought, it actually provide any value in testing it?
If it works on the filteredlist, it should goes without saying that it will work on unfilteredlist if it's using same implementation.

**Comment by Zhiyuan-Amos** [comment]
@eugenepeh 

You are right that if the `filteredList` test works, then it should seem that the `unfilteredList` will work as well.

How I see it is that we are recognizing that there are 2 states in which the list can be in: Either filtered or unfiltered. Which is why we choose to test for both states. Not too sure if this argument is strong enough though.

**Comment by yamidark** [comment]
@eugenepeh [5/6] and [6/6] add integration tests on the unfiltered list as stated in the commit message, while [3/6] and [4/6] integration tests are on the filtered list.

**Comment by eugenepeh** [comment]
>@eugenepeh [5/6] and [6/6] add integration tests on the unfiltered list as stated in the commit message, while [3/6] and [4/6] integration tests are on the filtered list.

Oh okay, my eye sight are getting worse >_< 
In that case, no other comments. @Zhiyuan-Amos can go ahead and merge le

**Comment by Zhiyuan-Amos** [comment]
> Hmm, okay. Not a very strong argument but I guess it is sounds legit.

Yup I know it's not a strong argument >< For now it's also for consistency, since for `XCommandTest` and `XCommandSystemTest` we perform tests on both filtered and unfiltered lists too. :)

**Comment by Zhiyuan-Amos** [comment]
Hurray @yamidark!
