### PR TITLE
CommandBox stays red even after correct input is entered #296

### LINKED ISSUE #296: CommandBox stays red even after correct input is entered
When wrong input is entered multiple times, CommandBox remains red when correct input is entered.

e.g.
1. "add": Fail, CommandBox turns red
2. "add": Fail, CommandBox stays red
3. "add adam p/123 e/adam@gmail.com a/abc": Success, CommandBox stays red (should be white)
4. "add bob p/123 e/bob@gmail.com a/abc": Success, CommandBox turns white 

Suggested fix:

In CommandBox.java, `remove` should be changed to `removeAll` in

```java
private void setStyleToIndicateCommandSuccess() {
    commandTextField.getStyleClass().remove(ERROR_STYLE_CLASS);
}
```

### PR DESCRIPTION
**Pull request by kychua**
Fixes #296

### CODE REVIEW

File: src/test/java/guitests/CommandBoxTest.java [hunk 1]
```diff
@@ -56,4 +56,16 @@ public void commandBox_commandSucceedsAfterFailedCommand_textClearedAndErrorStyl
         assertEquals(defaultStyleOfCommandBox, commandBox.getStyleClass());
     }
 
+    @Test
+    public void commandBox_commandSucceedsAfterMultipleFailedCommands_textClearedAndErrorStyleClassRemoved() {
+        // add multiple error styles to simulate multiple failed commands
+        commandBox.getStyleClass().add(CommandBox.ERROR_STYLE_CLASS);
+        commandBox.getStyleClass().add(CommandBox.ERROR_STYLE_CLASS);
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: Quick question: why not run a 'command that fails' multiple times instead of adding styles directly?

**Comment by CanIHasReview** [comment]
# v1

@kychua submitted v1 for review.

* [v1 1/1] [Fix CommandBox uses error style for successful command](https://github.com/se-edu/addressbook-level4/pull/298/commits/2ea00335fa19aa4be843b953d0c0f0b7ffc4b2e1)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/d741336a16662b675c117ed2aa3ade11a934f24c...2ea00335fa19aa4be843b953d0c0f0b7ffc4b2e1))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/298/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/guitests/CommandBoxTest.java (hunk 1 above)
Comment (kychua) [inline src/test/java/guitests/CommandBoxTest.java]: It's following the format of the existing test `commandBox_commandSucceedsAfterFailedCommand_textClearedAndErrorStyleClassRemoved`. I'm not sure why it was written this way (@edmundmok?). The test stops working if implementation for indicating error is changed... Shall I change both to run 'command that fails' instead?

Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: Given this is a GUI test which are expensive to run, an alternative would be to collapse the last three tests into one. 

```java
@Test
    public void commandBox_commandFails() {

        commandBox.runCommand(COMMAND_THAT_FAILS);
        assertErrorBehavior(COMMAND_THAT_FAILS);

        commandBox.runCommand(COMMAND_THAT_SUCCEEDS);
        assertNormalBehavior();

       // explain what's going on here
       commandBox.runCommand(COMMAND_THAT_FAILS);
       commandBox.runCommand(COMMAND_THAT_FAILS);
        assertErrorBehavior(COMMAND_THAT_FAILS);

        commandBox.runCommand(COMMAND_THAT_SUCCEEDS);
        assertNormalBehavior();
    }

```

File: src/main/java/seedu/address/ui/CommandBox.java [hunk 2]
```diff
@@ -61,7 +61,7 @@ private void handleCommandInputChanged() {
      * Sets the command box style to indicate a successful command.
      */
     private void setStyleToIndicateCommandSuccess() {
-        commandTextField.getStyleClass().remove(ERROR_STYLE_CLASS);
+        commandTextField.getStyleClass().removeAll(ERROR_STYLE_CLASS);
```
Comment (damithc) [inline src/main/java/seedu/address/ui/CommandBox.java]: Instead of removing all, should we instead ensure it's not added multiple times in the first place?

Comment (yamgent) [inline src/main/java/seedu/address/ui/CommandBox.java]: Agree with recommendation, `setStyleToIndicateCommandFailure()` should probably check the styles already in the list first before adding `ERROR_STYLE_CLASS`.

**Comment by CanIHasReview** [comment]
# v2

@kychua submitted v2 for review.

* [v2 1/1] [Fix CommandBox uses error style for successful command](https://github.com/se-edu/addressbook-level4/pull/298/commits/7bbe0084118ef771ff7431815005503539b74dcc)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/d741336a16662b675c117ed2aa3ade11a934f24c...7bbe0084118ef771ff7431815005503539b74dcc)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/25fb8adb4916f46ba902c37e92c6b6c7d627b8e1~1...25fb8adb4916f46ba902c37e92c6b6c7d627b8e1))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/298/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/ui/CommandBox.java [hunk 3]
```diff
@@ -68,7 +69,10 @@ private void setStyleToIndicateCommandSuccess() {
      * Sets the command box style to indicate a failed command.
      */
     private void setStyleToIndicateCommandFailure() {
-        commandTextField.getStyleClass().add(ERROR_STYLE_CLASS);
+        ObservableList<String> styleClass = commandTextField.getStyleClass();
+        if (!styleClass.contains(ERROR_STYLE_CLASS)) {
+            styleClass.add(ERROR_STYLE_CLASS);
+        }
```
Comment (damithc) [inline src/main/java/seedu/address/ui/CommandBox.java]: I would rewrite as follows (to keep happy path unindented):
```java
if (styleClass.contains(ERROR_STYLE_CLASS)) {
    return;
}

styleClass.add(ERROR_STYLE_CLASS);
```

File: src/test/java/guitests/CommandBoxTest.java [hunk 4]
```diff
@@ -30,30 +30,36 @@ public void setUp() {
     }
 
     @Test
-    public void commandBox_commandSucceeds_textClearedAndStyleClassRemainsTheSame() {
+    public void commandBox_commandSucceeds_normalBehavior() {
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: To be symmetric, remove `_normalBehavior` part?

**Comment by damithc** [comment]
Commit message:
`Let's add an ERROR_STYLE_CLASS for failed commands ...` can be rephrased as `Let's teach CommandBox to add an ERROR_STYLE_CLASS for failed commands ...`

**Comment by CanIHasReview** [comment]
# v3

@kychua submitted v3 for review.

* [v3 1/1] [Fix CommandBox uses error style for successful command](https://github.com/se-edu/addressbook-level4/pull/298/commits/88b4cd74efeac7a28fed991e845e5a6563335271)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/d741336a16662b675c117ed2aa3ade11a934f24c...88b4cd74efeac7a28fed991e845e5a6563335271)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/57734d25c97f17ad58f78d2e5f4dc5ba09c839a2~1...57734d25c97f17ad58f78d2e5f4dc5ba09c839a2))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/298/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/guitests/CommandBoxTest.java [hunk 5]
```diff
@@ -30,30 +30,36 @@ public void setUp() {
     }
 
     @Test
-    public void commandBox_commandSucceeds_textClearedAndStyleClassRemainsTheSame() {
+    public void commandBox_commandSucceeds() {
         commandBox.runCommand(COMMAND_THAT_SUCCEEDS);
-
-        assertEquals("", commandBox.getCommandInput());
-        assertEquals(defaultStyleOfCommandBox, commandBox.getStyleClass());
+        assertNormalBehavior();
```
Comment (pyokagan) [inline src/test/java/guitests/CommandBoxTest.java]: Naming: Isn't this more like asserting the command success behavior rather than asserting the "normal" behavior?

File: src/test/java/guitests/CommandBoxTest.java [hunk 6]
```diff
@@ -30,30 +30,36 @@ public void setUp() {
...
-    }
+        commandBox.runCommand(COMMAND_THAT_SUCCEEDS);
+        assertNormalBehavior();
 
-    @Test
-    public void commandBox_commandSucceedsAfterFailedCommand_textClearedAndErrorStyleClassRemoved() {
-        // add error style to simulate a failed command
-        commandBox.getStyleClass().add(CommandBox.ERROR_STYLE_CLASS);
+        // run multiple failed commands
+        commandBox.runCommand(COMMAND_THAT_FAILS);
```
Comment (pyokagan) [inline src/test/java/guitests/CommandBoxTest.java]: There should be a `assertErrorBehavior()` right after this line to check that the error style class gets added right after the *first* error.

File: src/test/java/guitests/CommandBoxTest.java [hunk 7]
```diff
@@ -30,30 +30,36 @@ public void setUp() {
...
+        commandBox.runCommand(COMMAND_THAT_FAILS);
+        assertErrorBehavior(COMMAND_THAT_FAILS);
```
Comment (pyokagan) [inline src/test/java/guitests/CommandBoxTest.java]: I wonder if `assertErrorBehavior()` and the `commandBox.runCommand(...)` could be combined together given that it seems that they are likely to always be called one after another.

**Comment by CanIHasReview** [comment]
# v4

@kychua submitted v4 for review.

* [v4 1/1] [CommandBox: limit no\. of ERROR\_STYLE\_CLASS added to 1](https://github.com/se-edu/addressbook-level4/pull/298/commits/e6b8e2f9fbd1abe2874e2425e0acd6797e8c7e70)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/d741336a16662b675c117ed2aa3ade11a934f24c...e6b8e2f9fbd1abe2874e2425e0acd6797e8c7e70)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level4/compare/3860bb249531c48ceba8d440ef6df845ec5b4d8c~1...3860bb249531c48ceba8d440ef6df845ec5b4d8c))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/298/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/guitests/CommandBoxTest.java [hunk 8]
```diff
@@ -30,30 +30,35 @@ public void setUp() {
...
-        assertEquals(COMMAND_THAT_FAILS, commandBox.getCommandInput());
-        assertEquals(errorStyleOfCommandBox, commandBox.getStyleClass());
+        testSuccessfulCommand();
     }
 
-    @Test
-    public void commandBox_commandSucceedsAfterFailedCommand_textClearedAndErrorStyleClassRemoved() {
-        // add error style to simulate a failed command
-        commandBox.getStyleClass().add(CommandBox.ERROR_STYLE_CLASS);
+    private void testFailedCommand() {
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: To be consistent with other test code, use `assertBehaviorForFailedCommand`. Furthermore, the `assert` prefix signals that the method contains test assertions.

File: src/test/java/guitests/CommandBoxTest.java [hunk 9]
```diff
@@ -30,30 +30,35 @@ public void setUp() {
...
 
     @Test
-    public void commandBox_commandFails_textStaysAndErrorStyleClassAdded() {
-        commandBox.runCommand(COMMAND_THAT_FAILS);
+    public void commandBox_commandFails() {
+        testFailedCommand();
+
+        testSuccessfulCommand();
+
+        // run multiple failed commands
```
Comment (pyokagan) [inline src/test/java/guitests/CommandBoxTest.java]: This is quite obvious from the lines below :-P. As a reader of the code, I'd like to know why running multiple failed commands is a test case though.

File: src/test/java/guitests/CommandBoxTest.java [hunk 10]
```diff
@@ -30,30 +30,35 @@ public void setUp() {
...
-        assertEquals(defaultStyleOfCommandBox, commandBox.getStyleClass());
+    public void commandBox_commandSucceeds() {
+        testSuccessfulCommand();
     }
 
     @Test
-    public void commandBox_commandFails_textStaysAndErrorStyleClassAdded() {
-        commandBox.runCommand(COMMAND_THAT_FAILS);
+    public void commandBox_commandFails() {
+        testFailedCommand();
```
Comment (pyokagan) [inline src/test/java/guitests/CommandBoxTest.java]: As a reader of the code, I'd like to know the purpose of invoking `testFailedCommand()` and then `testSucessfulCommand()` in this sequence.

**Comment by pyokagan** [comment]
@yamgent Please help me peer review the next iteration first, thanks.

File: src/test/java/guitests/CommandBoxTest.java [hunk 11]
```diff
@@ -30,30 +30,35 @@ public void setUp() {
...
+        assertEquals(errorStyleOfCommandBox, commandBox.getStyleClass()); // error style class added
+    }
 
+    private void testSuccessfulCommand() {
         commandBox.runCommand(COMMAND_THAT_SUCCEEDS);
 
-        assertEquals("", commandBox.getCommandInput());
-        assertEquals(defaultStyleOfCommandBox, commandBox.getStyleClass());
+        assertEquals("", commandBox.getCommandInput()); // text cleared
+        assertEquals(defaultStyleOfCommandBox, commandBox.getStyleClass()); // style class unchanged
```
Comment (PierceAndy) [inline src/test/java/guitests/CommandBoxTest.java]: It seems odd to say `style class unchanged`. Does that mean that if a failed command was entered beforehand, the style remains unchanged from that style?

**Comment by CanIHasReview** [comment]
# v5

@kychua submitted v5 for review.

* [v5 1/1] [CommandBox: limit no\. of ERROR\_STYLE\_CLASS added to 1](https://github.com/se-edu/addressbook-level4/pull/298/commits/758c2509592e125c920e2863a3e7aa3e64c5b507)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...758c2509592e125c920e2863a3e7aa3e64c5b507)) ([:chart_with_upwards_trend: Interdiff between v4 and v5](https://github.com/se-edu/addressbook-level4/compare/f6afa32f8f74c6ddec94513b71fc3582790f5ea3~1...f6afa32f8f74c6ddec94513b71fc3582790f5ea3))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/298/5/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/guitests/CommandBoxTest.java [hunk 12]
```diff
@@ -30,30 +30,37 @@ public void setUp() {
...
 
-    @Test
-    public void commandBox_commandSucceedsAfterFailedCommand_textClearedAndErrorStyleClassRemoved() {
-        // add error style to simulate a failed command
-        commandBox.getStyleClass().add(CommandBox.ERROR_STYLE_CLASS);
+    private void assertBehaviorForFailedCommand() {
+        commandBox.runCommand(COMMAND_THAT_FAILS);
+
+        assertEquals(COMMAND_THAT_FAILS, commandBox.getCommandInput()); // text remains
+        assertEquals(errorStyleOfCommandBox, commandBox.getStyleClass()); // contains an error style class
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: `contains` is not exactly correct. This is an equality check.

File: src/test/java/guitests/CommandBoxTest.java [hunk 13]
```diff
@@ -30,30 +30,37 @@ public void setUp() {
     }
 
     @Test
-    public void commandBox_commandSucceeds_textClearedAndStyleClassRemainsTheSame() {
-        commandBox.runCommand(COMMAND_THAT_SUCCEEDS);
-
-        assertEquals("", commandBox.getCommandInput());
-        assertEquals(defaultStyleOfCommandBox, commandBox.getStyleClass());
+    public void commandBox_commandSucceeds() {
+        // verify that no error style class is added
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: No need for this comment

File: src/test/java/guitests/CommandBoxTest.java [hunk 14]
```diff
@@ -30,30 +30,37 @@ public void setUp() {
...
+        assertBehaviorForSuccessfulCommand();
     }
 
     @Test
-    public void commandBox_commandFails_textStaysAndErrorStyleClassAdded() {
-        commandBox.runCommand(COMMAND_THAT_FAILS);
+    public void commandBox_commandFails() {
+        assertBehaviorForFailedCommand();
+
+        // verify that error style class is removed
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: No need for this too.

File: src/test/java/guitests/CommandBoxTest.java [hunk 15]
```diff
@@ -30,30 +30,37 @@ public void setUp() {
...
+        assertBehaviorForSuccessfulCommand();
+
+        // verify that at most one error style class is added for failed commands
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: Like this:?
```java
// verify style is changed correctly even after multiple consecutive successful/failed commands
assertBehaviorForFailedCommand();
assertBehaviorForFailedCommand();
assertBehaviorForSuccessfulCommand();
assertBehaviorForSuccessfulCommand();
```

This way, our test is not biased by the bug we found (which the reader is unaware of anyway). What do you think?

File: src/test/java/guitests/CommandBoxTest.java (hunk 14 above)
Comment (yamgent) [inline src/test/java/guitests/CommandBoxTest.java]: Paul brought up a point that it is not obvious to the outside reader why success is being checked after fail, which I believe is the reason why this comment is here. Maybe this warrants separating the test cases, and putting the intention on the test cases' names?

Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: I suggest groping this two like this:

```java
// verify style is changed correctly when starting with a failed command and followed by a successful command
assertBehaviorForFailedCommand();
assertBehaviorForSuccessfulCommand();
```

GUI tests have significant startup costs, so I would not divide into multiple tests unless needed.

**Comment by CanIHasReview** [comment]
# v6

@kychua submitted v6 for review.

* [v6 1/1] [CommandBox: limit no\. of ERROR\_STYLE\_CLASS added to 1](https://github.com/se-edu/addressbook-level4/pull/298/commits/d3e01270eda0173820e5ecf49765afd5e075a265)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...d3e01270eda0173820e5ecf49765afd5e075a265)) ([:chart_with_upwards_trend: Interdiff between v5 and v6](https://github.com/se-edu/addressbook-level4/compare/75e1cc81075e609c6314fe4e1d83e4544cddd46d~1...75e1cc81075e609c6314fe4e1d83e4544cddd46d))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/298/6/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/guitests/CommandBoxTest.java [hunk 16]
```diff
@@ -30,29 +30,34 @@ public void setUp() {
     }
 
     @Test
-    public void commandBox_commandSucceeds_textClearedAndStyleClassRemainsTheSame() {
-        commandBox.runCommand(COMMAND_THAT_SUCCEEDS);
-
-        assertEquals("", commandBox.getCommandInput());
-        assertEquals(defaultStyleOfCommandBox, commandBox.getStyleClass());
+    public void commandBox_startingWithSuccessfulCommand() {
+        assertBehaviorForSuccessfulCommand();
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: Throw in a `assertBehaviorForFailedCommand();` to follow (to be symmetric with the other test below)?

File: src/test/java/guitests/CommandBoxTest.java [hunk 17]
```diff
@@ -30,29 +30,34 @@ public void setUp() {
...
+    public void commandBox_startingWithFailedCommand() {
+        // verify style is changed correctly when starting with a failed command and followed by a successful command
+        assertBehaviorForFailedCommand();
+        assertBehaviorForSuccessfulCommand();
+
+        // verify style is changed correctly even after multiple consecutive successful/failed commands
+        assertBehaviorForFailedCommand();
+        assertBehaviorForFailedCommand();
+        assertBehaviorForSuccessfulCommand();
+        assertBehaviorForSuccessfulCommand();
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: This sequence is better?
```
F
S

S
F
F
S
```
It covers  both `S S F` and `F F S` sequences

**Comment by pyokagan** [comment]
@damithc @yamgent The reason I asked for more inline comments is because this PR removes the descriptive test names (e.g. `commandBox_commandSucceedsAfterFailedCommand_textClearedAndErrorStyleClassRemoved`, `commandBox_commandFails_textStaysAndErrorStyleClassAdded`) which tells the reader what we are checking for.

Every `assertX()` statement that we write has a purpose behind it, and if the test name does not provide that context to the reader, then we will need to explain it via inline comments.

File: src/test/java/guitests/CommandBoxTest.java [hunk 18]
```diff
@@ -30,29 +30,34 @@ public void setUp() {
...
+    }
+
+    private void assertBehaviorForFailedCommand() {
         commandBox.runCommand(COMMAND_THAT_FAILS);
 
-        assertEquals(COMMAND_THAT_FAILS, commandBox.getCommandInput());
+        assertEquals(COMMAND_THAT_FAILS, commandBox.getCommandInput()); // text remains
         assertEquals(errorStyleOfCommandBox, commandBox.getStyleClass());
```
Comment (pyokagan) [inline src/test/java/guitests/CommandBoxTest.java]: Now that this is a utility function, we can afford to be more verbose in explaining what exactly we *intend* to check for with the `assertEquals()` here. Something like:
```java
// verify that the command box has only *one* ERROR_STYLE_CLASS, and the rest of its style classes are untouched.
```

**Comment by damithc** [comment]
@pyokagan 

> The reason I asked for more inline comments is because this PR removes the descriptive test names

Yup, more comments are useful in this case. From what I remember, I asked to remove those inline comments because I saw the same comment being repeated a few times. Perhaps the repeated explanation can be moved to the utility method that is being called? Any additional info that is specific to the call site (and not mentioned in the utility method documentation) can be still given at the call site.

**Comment by CanIHasReview** [comment]
# v7

@kychua submitted v7 for review.

* [v7 1/1] [CommandBox: limit no\. of ERROR\_STYLE\_CLASS added to 1](https://github.com/se-edu/addressbook-level4/pull/298/commits/2c91cf8d4ee22cb2656bf868d7b0e627a7d310e7)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...2c91cf8d4ee22cb2656bf868d7b0e627a7d310e7)) ([:chart_with_upwards_trend: Interdiff between v6 and v7](https://github.com/se-edu/addressbook-level4/compare/d67f87ff5ad8f2b0ff1361e3cfeb67c281a1c405~1...d67f87ff5ad8f2b0ff1361e3cfeb67c281a1c405))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/298/7/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/test/java/guitests/CommandBoxTest.java [hunk 19]
```diff
@@ -30,29 +30,44 @@ public void setUp() {
...
+        // verify that command box has only *one* ERROR_STYLE_CLASS, and other style classes are untouched
         assertEquals(errorStyleOfCommandBox, commandBox.getStyleClass());
     }
 
-    @Test
-    public void commandBox_commandSucceedsAfterFailedCommand_textClearedAndErrorStyleClassRemoved() {
-        // add error style to simulate a failed command
-        commandBox.getStyleClass().add(CommandBox.ERROR_STYLE_CLASS);
-
+    private void assertBehaviorForSuccessfulCommand() {
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: The alternative is to write a detailed header comment for the method. In the current version the reader has to read the body of the method to find out the full contract.

File: src/test/java/guitests/CommandBoxTest.java [hunk 20]
```diff
@@ -30,29 +30,44 @@ public void setUp() {
...
 
     @Test
-    public void commandBox_commandSucceeds_textClearedAndStyleClassRemainsTheSame() {
-        commandBox.runCommand(COMMAND_THAT_SUCCEEDS);
+    public void commandBox_startingWithSuccessfulCommand() {
+        assertBehaviorForSuccessfulCommand();
 
-        assertEquals("", commandBox.getCommandInput());
-        assertEquals(defaultStyleOfCommandBox, commandBox.getStyleClass());
+        // verify that ERROR_STYLE_CLASS is added
```
Comment (damithc) [inline src/test/java/guitests/CommandBoxTest.java]: If the `assertBehaviorForFailedCommand()` has a well defined contract, this comment is redundant? As a reader, I expect the method call to verify the command box behaves correctly for the failed command, one part of which is to add error style class.

File: src/test/java/guitests/CommandBoxTest.java [hunk 21]
```diff
@@ -30,29 +30,44 @@ public void setUp() {
...
+        assertBehaviorForFailedCommand();
     }
 
     @Test
-    public void commandBox_commandFails_textStaysAndErrorStyleClassAdded() {
+    public void commandBox_startingWithFailedCommand() {
+        assertBehaviorForFailedCommand();
+
+        // verify that ERROR_STYLE_CLASS is removed
```
Comment (PierceAndy) [inline src/test/java/guitests/CommandBoxTest.java]: Same point made by Damith applies here too.

File: src/test/java/guitests/CommandBoxTest.java (hunk 19 above)
Comment (yamgent) [inline src/test/java/guitests/CommandBoxTest.java]: Agree. This non-tests method can use a header comment; this is the style that the codebase uses anyway.

File: src/test/java/guitests/CommandBoxTest.java [hunk 22]
```diff
@@ -30,29 +30,44 @@ public void setUp() {
...
-        // add error style to simulate a failed command
-        commandBox.getStyleClass().add(CommandBox.ERROR_STYLE_CLASS);
-
+    private void assertBehaviorForSuccessfulCommand() {
         commandBox.runCommand(COMMAND_THAT_SUCCEEDS);
 
+        // verify that text is cleared
         assertEquals("", commandBox.getCommandInput());
+
+        // verify that command box does not have any ERROR_STYLE_CLASS, with style classes the same as default
```
Comment (yamgent) [inline src/test/java/guitests/CommandBoxTest.java]: With the header comment, I don't think these comments will be necessary, since the contract will be specified in the header comment.

**Comment by CanIHasReview** [comment]
# v8

@kychua submitted v8 for review.

* [v8 1/1] [CommandBox: limit no\. of ERROR\_STYLE\_CLASS added to 1](https://github.com/se-edu/addressbook-level4/pull/298/commits/e948502d12606c002901be321b2911c503f818e0)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...e948502d12606c002901be321b2911c503f818e0)) ([:chart_with_upwards_trend: Interdiff between v7 and v8](https://github.com/se-edu/addressbook-level4/compare/a468375f86a9107ba3bc064fc11a92b589c790f7~1...a468375f86a9107ba3bc064fc11a92b589c790f7))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/298/8/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>
