### PR TITLE
Extract exceptions in UniquePersonList #476

### LINKED ISSUE #476: Extract UniquePersonList.DuplicatePersonException, UniquePersonList.PersonNotFoundException
There's no need for these Exceptions to be inside `UniquePersonList`.

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #476

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/1] [Extract exceptions in UniquePersonList](https://github.com/se-edu/addressbook-level4/pull/479/commits/4cdc84f698e0ede6b08efd54fca96ca119c80653)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/3de3b34bcf05aa4a9a656b238be22d7de6d78279...4cdc84f698e0ede6b08efd54fca96ca119c80653))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/479/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

File: src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java [hunk 1]
```diff
@@ -0,0 +1,12 @@
+package seedu.address.model.person.exceptions;
+
+import seedu.address.commons.exceptions.DuplicateDataException;
+
+/**
+ * Signals that an operation would have violated the 'no duplicates' property of the list.
```
Comment (limmlingg) [inline src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java]: What list?

File: src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java [hunk 2]
```diff
@@ -0,0 +1,7 @@
+package seedu.address.model.person.exceptions;
+
+/**
+ * Signals that an operation targeting a specified person in the list would fail because
+ * there is no such matching person in the list.
```
Comment (limmlingg) [inline src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java]: What list?

**Comment by Zhiyuan-Amos** [comment]
@yamgent NO REVIEW?

**Comment by CanIHasReview** [comment]
# v2

@Zhiyuan-Amos submitted v2 for review.

* [v2 1/1] [Extract exceptions in UniquePersonList](https://github.com/se-edu/addressbook-level4/pull/479/commits/461afb8239434e70294d0a317b6cbfc37da63d48)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/a300eb7b7798dfd52a5b056874219042c7123ec7...461afb8239434e70294d0a317b6cbfc37da63d48)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/863d66870a7f09c18ec9ad8b06c4c73537b372a6~1...863d66870a7f09c18ec9ad8b06c4c73537b372a6))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/479/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 3]
```diff
@@ -9,7 +9,7 @@
 import seedu.address.logic.commands.exceptions.CommandException;
```
Comment (damithc) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: Commit message:
>To access DuplicatePersonException and PersonNotFoundException, external
classes have to access UniquePersonList.

`external` relative to what?

Suggested:
```
Model API refers to UniquePersonList.DuplicatePersonException 
and UniquePersonList.PersonNotFoundException.

UniquePersonList is a class inside the model component
which need not be exposed to classes outside the
Model component.

Let's extract these two exception as standalone classes
so that the Model API no longer exposes the
UniquePersonList  class.
```

File: src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java [hunk 4]
```diff
@@ -0,0 +1,12 @@
+package seedu.address.model.person.exceptions;
+
+import seedu.address.commons.exceptions.DuplicateDataException;
+
+/**
+ * Signals that the operation will result in 2 or more people having the same particulars.
```
Comment (damithc) [inline src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java]: `having the same particulars` may be the current definition of `equals()` but that can change in the future. A more future proof explanation is `result in duplicate Person objects`.

**Comment by CanIHasReview** [comment]
# v3

@Zhiyuan-Amos submitted v3 for review.

* [v3 1/1] [Extract exceptions in UniquePersonList](https://github.com/se-edu/addressbook-level4/pull/479/commits/652b4fd39df5dc47f1f746974182a7eb7e1c3fb9)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/a300eb7b7798dfd52a5b056874219042c7123ec7...652b4fd39df5dc47f1f746974182a7eb7e1c3fb9)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/bb969b4ad5fe3a9f0076fee48af794aa5cf7fadc~1...bb969b4ad5fe3a9f0076fee48af794aa5cf7fadc))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/479/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
@yamgent for last call:>
