### PR TITLE
DeveloperGuide: Update instructions on setting up #672

### LINKED ISSUE #672: HelpWindowTest fails on Windows
I was running it using Intellij. Keeps failing after multiple attempts. Also fails when run using Gradle (actually 6 tests failed in that mode) but passes in headless mode. 
```

java.lang.RuntimeException: java.lang.NullPointerException

	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:133)
	at org.testfx.api.FxRobot.interact(FxRobot.java:498)
	at seedu.address.ui.HelpWindowTest.setUp(HelpWindowTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at seedu.address.ui.testutil.StageRule$1.evaluate(StageRule.java:27)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at seedu.address.ui.HelpWindow.<init>(HelpWindow.java:38)
	at seedu.address.ui.HelpWindowTest.lambda$setUp$0(HelpWindowTest.java:22)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:364)
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$2(WaitForAsyncUtils.java:115)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #672.

### CODE REVIEW

**Comment by Zhiyuan-Amos** [comment]
On a side note, do we need to test the `Gradle` class? I'm not sure how to test it though :O

**Comment by pyokagan** [comment]
This seems like it will bloat up our JAR file size, for a scenario which should *not* happen in production ?

**Comment by Zhiyuan-Amos** [comment]
Noted, thanks for your review @pyokagan; always learn much from it. Have updated my PR.

Created `DocsNotFoundException` and I wanted to have it extend `MissingResourceException` to make it more descriptive, but it didn't quite work out because of the parameters required to create an instance of `MissingResourceException`.

**Comment by yamgent** [comment]
> This seems like it will bloat up our JAR file size, for a scenario which should not happen in production ?

Wasn't this similar to what I have stated in https://github.com/se-edu/addressbook-level4/issues/672#issuecomment-330245800? Why did V1 still happen in spite of the comment?

**Comment by Zhiyuan-Amos** [comment]
> Wasn't this similar to what I have stated in #672 (comment)? Why did V1 still happen in spite of the comment?

Because I misunderstood your comment, and I think I misunderstood prof's comment here too :P https://github.com/se-edu/addressbook-level4/issues/672#issuecomment-330418986

**Comment by damithc** [comment]
Yes, the 'user' in this case is the developer and the use case is 'run tests in intellij'; printing an error message to the console is enough.

**Comment by Zhiyuan-Amos** [comment]
@damithc prof I'm curious to know how you encountered the bug, because on my side, whenever I run tests, it seems that Gradle automatically executes the task `processResources` (see last line of the image below). As such, the file required by `HelpWindowTest` is always generated, unless I delete it by pausing the test after the task finishes execution.

image

**Comment by Zhiyuan-Amos** [comment]
Added instructions in DeveloperGuide. Can't connect to canihasreview atm.

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 1]
```diff
@@ -35,8 +37,13 @@ public HelpWindow() {
...
         FxViewUtil.setStageIcon(dialogStage, ICON);
 
-        String userGuideUrl = getClass().getResource(USERGUIDE_FILE_PATH).toString();
-        browser.getEngine().load(userGuideUrl);
+        URL userGuideUrl = getClass().getResource(USERGUIDE_FILE_PATH);
+        if (userGuideUrl != null) {
+            browser.getEngine().load(userGuideUrl.toString());
+        } else {
+            throw new DocsNotFoundException("UserGuide.html cannot be found. Run Gradle task 'processResources' to"
+                    + "create the missing file.");
```
Comment (yamgent) [inline src/main/java/seedu/address/ui/HelpWindow.java]: > The user, in this case, is the developer only right? Because this shouldn't be able to happen in production (I'm not too familiar with how the .jar file works, but we can't remove the UserGuide.html file right? If I'm reading Paul's comment #691 (comment) correctly, the reason why V.1 was rejected is because this code isn't required in production.), and I think we don't expect the user to run the app using IntelliJ either. As such, isn't having the error message printed to the console output sufficient for the developer to "debug"?


So it is OK for the students to see nothing after typing "help", get confused, has a fair chance of missing the console message, and end up having to post on the forum? OK then. No objections.

Would have expected the fix to at least include a message shown in the HelpWindow about what when wrong, But sure, no problem, pretty sure it's no big deal, feel free to ignore my comment if you want.

File: docs/DeveloperGuide.adoc [hunk 2]
```diff
@@ -50,6 +50,8 @@ Restart the IDE to complete the installation.
 . Locate the `build.gradle` file and select it. Click `OK`
 . Click `Open as Project`
 . Click `OK` to accept the default settings
+. If the Gradle task `processResources` is not executed before running the tests, `HelpWindowTest` will fail. This is because `HelpWindowTest` depends on one of the files generated by the Gradle's task. +
```
Comment (yamgent) [inline docs/DeveloperGuide.adoc]: No guidance on how to resolve this issue step-by-step, but only just mentioned the issue. Feel free to ignore my comment if you want.

**Comment by Zhiyuan-Amos** [comment]
Er no idea why you sound so angst but:

> You may 'misunderstood' all of my comments that I have made for this issue, but please don't ignore his comments: #672 (comment).

`processResources` depends on `asciidoctor`, as such when you run `processResources`, `asciidoctor` is automatically run as well.

> You may 'misunderstood' all of my comments

I legit didn't understand because I'm not too familiar with Gradle; I don't even know how this bug happened (which was why I asked prof above in https://github.com/se-edu/addressbook-level4/pull/691#issuecomment-330711546 to further understand this issue). Unfortunately, I'm not as experienced as yourself and Paul.

> So it is OK for the students to see nothing after typing "help", get confused, has a fair chance of missing the console message, and end up having to post on the forum? OK then. No objections.

> Would have expected the fix to at least include a message shown in the HelpWindow about what when wrong, But sure, no problem, pretty sure it's no big deal, feel free to ignore my comment if you want.

Based on the use case as mentioned by prof in https://github.com/se-edu/addressbook-level4/pull/691#issuecomment-330701844, printing on the console is sufficient (since the test fails, student will read the logs).

In fact because you mentioned this, I then realized that this issue is slightly bigger than what I thought because it doesn't just affect the tests, but it can affect the main code base as well. As such, what you mentioned is right, I should show an error message.

File: src/main/java/seedu/address/ui/HelpWindow.java (hunk 1 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/ui/HelpWindow.java]: I didn't mean to ignore https://github.com/se-edu/addressbook-level4/pull/691#pullrequestreview-63707084. I had no idea what you meant by "user", and I thought that this PR was meant to only resolve for tests.

If you had been this detailed in that comment, I would understand where you are driving at.

Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/ui/HelpWindow.java]: @damithc do you want an error dialog to pop up if the error occurs? 

My take is that there isn't a need to since this error shouldn't happen in production. Though arguably since this project is meant to be used by students only, we can perhaps add code that isn't related to production as it makes it easier for the students to know what's the error.

File: docs/DeveloperGuide.adoc (hunk 2 above)
Comment (Zhiyuan-Amos) [reply docs/DeveloperGuide.adoc]: I don't know how detailed this is required. Sure, I could have hyperlinked it to `Running Gradle Commands` in `UsingGradle.adoc` (missed this out), but to me, it's just about running a task `processResources`, and the link gives the instruction on how to do so, and this is detailed enough to me.

If this isn't detailed enough to you, then your role as a reviewer is to point that out isn't it. I don't get why it's necessary for you to mention "Feel free to ignore my comment if you want."; I mean it's not intentional that I submit poor PRs.

File: src/main/java/seedu/address/ui/HelpWindow.java (hunk 1 above)
Comment (damithc) [reply src/main/java/seedu/address/ui/HelpWindow.java]: >So it is OK for the students to see nothing after typing "help", get confused, has a fair chance of missing the console message, and end up having to post on the forum? OK then. No objections.

Actually, I didn't think of this scenario. I was thinking of testing only. While our users are developers, they _will_ try the app in normal user mode via intellij (i.e. not using jar file). In fact this might be the first thing they do after they set up the project. It's nice if the confusion can be avoided. Asking the dev to generate docs as part of the set up process is the easier way to avoid this issue (although some will still miss it --> an automated solution will cover those cases too :-p).

File: docs/DeveloperGuide.adoc (hunk 2 above)
Comment (damithc) [reply docs/DeveloperGuide.adoc]: Guys, chill :-)
Just phrase it as `Do X. Reason: X is needed because ...`

File: src/main/java/seedu/address/ui/HelpWindow.java (hunk 1 above)
Comment (Zhiyuan-Amos) [reply src/main/java/seedu/address/ui/HelpWindow.java]: > Asking the dev to generate docs as part of the set up process is the easier way to avoid this issue (although some will still miss it --> an automated solution will cover those cases too :-p).

Ah yes. That way, we don't have to edit the source code; we just have to update the setting up in Developer Guide right?

**Comment by damithc** [comment]
Guys, let's just update setup instructions in this PR. We can think of a better solution in a separate PR. Even printing the error message (the way it is done now) seems a bit dodgy (e.g. mentioning Gradle inside production code) -- so let's do it in this PR.

File: src/main/java/seedu/address/ui/HelpWindow.java (hunk 1 above)
Comment (damithc) [reply src/main/java/seedu/address/ui/HelpWindow.java]: Yes, just update the dev guide.

**Comment by Zhiyuan-Amos** [comment]
@damithc updated the DeveloperGuide, hopefully it's better now! Can't connect to canihasreview.

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 

> Can't connect to canihasreview.

Everytime I see a message like this I immediately go and try myself and it seems to work? What kind of error are you getting?

**Comment by Zhiyuan-Amos** [comment]
@pyokagan saw this when I went to the link: https://canihasreview.pyokagan.com/se-edu/addressbook-level4/pull/691

image

Tried it again, and now there isn't any screen displayed at all.

Seems like Eugene is facing the issue too: https://github.com/se-edu/addressbook-level4/pull/673#issuecomment-330743378

**Comment by pyokagan** [comment]
Might be a DNS misconfiguration, I'll go check, later...

**Comment by Zhiyuan-Amos** [comment]
Thanks Paul! ^^

File: docs/DeveloperGuide.adoc [hunk 3]
```diff
@@ -50,6 +50,12 @@ Restart the IDE to complete the installation.
 . Locate the `build.gradle` file and select it. Click `OK`
 . Click `Open as Project`
 . Click `OK` to accept the default settings
+. Run `seedu.address.ui.HelpWindowTest`
+. Observe that this test fails. This is because `HelpWindowTest` depends on `src/main/resources/docs/UserGuide.html`, but this file is missing as it has yet to be generated. To generate this file, execute Gradle task `processResources`. See <<UsingGradle#running-gradle-commands, UsingGradle.adoc>> for how to execute Gradle's tasks.
+.. Instead of performing steps 9 and 10, you can perform the following steps below instead:
+.. Go to `File` > `Settings` (Windows/Linux), or `IntelliJ IDEA` > `Preferences...` (macOS) > `Build, Execution, Deployment` > `Build Tools` > `Gradle` > `Runner`. Under `Run test using`, select `Gradle Test Runner`. `Gradle Test Runner` automatically executes Gradle tasks such as `processResources`.
+.. Run `HelpWindowTest`. Notice that the test doesn't fail at all, as the required `UserGuide.html` is generated by Gradle before the test is executed.
+. Observe that `UserGuide.html` is generated after executing `processResources`. Run the test again to ensure that it passes now.
```
Comment (damithc) [inline docs/DeveloperGuide.adoc]: Just this should be enough?

>Run the Gradle task `processResources` (see <<UsingGradle#running-gradle-commands, UsingGradle.adoc>> to learn how to execute Gradle's tasks). This task will generate an HTML version of the User Guide (from the asciidoc version), to be used by the help Window.

Comment (Zhiyuan-Amos) [reply docs/DeveloperGuide.adoc]: Ok! Was following the format in AB - Level 3 points 10 to 12: https://github.com/se-edu/addressbook-level3/blob/master/doc/DeveloperGuide.md#importing-the-project-into-intellij

File: docs/DeveloperGuide.adoc [hunk 4]
```diff
@@ -50,6 +50,12 @@ Restart the IDE to complete the installation.
 . Locate the `build.gradle` file and select it. Click `OK`
 . Click `Open as Project`
 . Click `OK` to accept the default settings
+. Run `seedu.address.ui.HelpWindowTest`
+. Observe that this test fails. This is because `HelpWindowTest` depends on `src/main/resources/docs/UserGuide.html`, but this file is missing as it has yet to be generated. To generate this file, execute Gradle task `processResources`. See <<UsingGradle#running-gradle-commands, UsingGradle.adoc>> for how to execute Gradle's tasks.
+.. Instead of performing steps 9 and 10, you can perform the following steps below instead:
+.. Go to `File` > `Settings` (Windows/Linux), or `IntelliJ IDEA` > `Preferences...` (macOS) > `Build, Execution, Deployment` > `Build Tools` > `Gradle` > `Runner`. Under `Run test using`, select `Gradle Test Runner`. `Gradle Test Runner` automatically executes Gradle tasks such as `processResources`.
```
Comment (eugenepeh) [inline docs/DeveloperGuide.adoc]: maybe can split this part into multiple lines/steps? takes me a while to know which belongs to windows :P
.. Go to `File` > `Settings` (Windows/Linux), or `IntelliJ IDEA` > `Preferences...` (macOS), +
  in `Build, Execution, Deployment` > `Build Tools` > `Gradle` > `Runner`, +
  select `Gradle Test Runner` under `Run test using`.
.. Click `OK` and `Gradle Test Runner` will now automatically executes Gradle tasks such as `processResources`.

P.S 
Does it really automatically executes? Cus I see nothing until I press run build myself o_o

Comment (pyokagan) [inline docs/DeveloperGuide.adoc]: Could we do without the whole "Run this test and observe it fails" thing above and below? It makes the list of setup instructions very long. Instead, just go directly to the step on this line?

You could add the `HelpWindowTest` failure thing in a separate "troubleshooting" section.

File: docs/DeveloperGuide.adoc (hunk 2 above)
Comment (yamgent) [reply docs/DeveloperGuide.adoc]: @damithc @Zhiyuan-Amos Apologies for the overly aggressive review.

File: docs/DeveloperGuide.adoc (hunk 4 above)
Comment (Zhiyuan-Amos) [reply docs/DeveloperGuide.adoc]: Opps bad phrasing, I mean it automatically executes Gradle tasks before tests are executed. ><

**Comment by Zhiyuan-Amos** [comment]
@damithc @pyokagan for your review :)

File: docs/DeveloperGuide.adoc [hunk 5]
```diff
@@ -50,6 +50,12 @@ Restart the IDE to complete the installation.
 . Locate the `build.gradle` file and select it. Click `OK`
 . Click `Open as Project`
 . Click `OK` to accept the default settings
+. Run the Gradle task `processResources` (see <<UsingGradle#running-gradle-commands, UsingGradle.adoc>> to learn how to execute Gradle's tasks). +
+This task will generate a HTML version of the User Guide (from the asciidoc version), to be used by the `HelpWindow`.
+. (Optional) You may want to use Gradle to execute tests. This automatically executes Gradle tasks such as `processResources` before running the tests.
+.. Go to `File` > `Settings` (Windows/Linux), or `IntelliJ IDEA` > `Preferences...` (macOS) +
+.. Select `Build, Execution, Deployment` > `Build Tools` > `Gradle` > `Runner` +
+.. Select `Gradle Test Runner` under `Run test using`
```
Comment (damithc) [inline docs/DeveloperGuide.adoc]: Leave out the Optional part? There is no need to give too much information when the person is completely new to the whole thing (he is still setting up!).

File: docs/DeveloperGuide.adoc [hunk 6]
```diff
@@ -403,6 +409,12 @@ e.g. `seedu.address.logic.LogicManagerTest`
 
 Thanks to the https://github.com/TestFX/TestFX[TestFX] library we use, our GUI tests can be run in the _headless_ mode. In the headless mode, GUI tests do not show up on the screen. That means the developer can do other things on the Computer while the tests are running. See <<UsingGradle#running-tests, UsingGradle.adoc>> to learn how to run tests in headless mode.
 
+=== Troubleshooting Testing
+**Problem: `HelpWindowTest` fails.**
```
Comment (damithc) [inline docs/DeveloperGuide.adoc]: `fails with a NullPointerException`? Good to narrow it down as much as we can.

File: docs/DeveloperGuide.adoc [hunk 7]
```diff
@@ -50,6 +50,12 @@ Restart the IDE to complete the installation.
 . Locate the `build.gradle` file and select it. Click `OK`
 . Click `Open as Project`
 . Click `OK` to accept the default settings
+. Run the Gradle task `processResources` (see <<UsingGradle#running-gradle-commands, UsingGradle.adoc>> to learn how to execute Gradle's tasks). +
+This task will generate a HTML version of the User Guide (from the asciidoc version), to be used by the `HelpWindow`.
+. (Optional) You may want to use Gradle to execute tests. This automatically executes Gradle tasks such as `processResources` before running the tests.
```
Comment (pyokagan) [inline docs/DeveloperGuide.adoc]: Could we make this the recommended approach rather than "running `processResources` once"? It is much more correct -- `processResources` will only generate the resources once, but setting up gradle integration properly in intellij will ensure that those generated resources always remain up-to-date.

Comment (Zhiyuan-Amos) [reply docs/DeveloperGuide.adoc]: You will still have to run it once, otherwise if you start the `MainApp` and run the `HelpCommand`, no Help Window appears because the resources hasn't been created yet :(

Comment (pyokagan) [reply docs/DeveloperGuide.adoc]: Well, that's intellij's fault as well :-P Can't we configure intellij to use gradle to launch the application as well? i.e. `gradle run`.

Comment (pyokagan) [reply docs/DeveloperGuide.adoc]: At this point, it seems that we should actually be shipping the intellij project files in our repo >:(

Comment (pyokagan) [reply docs/DeveloperGuide.adoc]: Alright, I guess for now you should just leave out the entire "Optional" part as @damithc mentioned.

Comment (Zhiyuan-Amos) [reply docs/DeveloperGuide.adoc]: > At this point, it seems that we should actually be shipping the intellij project files in our repo >:(

Sorry noob question, just to make sure I'm understanding you rightly, you're saying that cos our main code base depends on `UserGuide.html`, as such this should be committed as part of the code base is it?

**Comment by Zhiyuan-Amos** [comment]
@damithc @pyokagan ready for review; at SoC so can't connect to CanIHasReview :)

File: docs/DeveloperGuide.adoc [hunk 8]
```diff
@@ -50,6 +50,8 @@ Restart the IDE to complete the installation.
 . Locate the `build.gradle` file and select it. Click `OK`
 . Click `Open as Project`
 . Click `OK` to accept the default settings
+. Run the Gradle task `processResources` (see <<UsingGradle#running-gradle-commands, UsingGradle.adoc>> to learn how to execute Gradle's tasks). +
+This task will generate a HTML version of the User Guide (from the asciidoc version), to be used by the `HelpWindow`.
```
Comment (damithc) [inline docs/DeveloperGuide.adoc]: In my latest PR I ended up editing the same part. I used:
```
Open a console and run the command `./gradlew processResources` (it should finish the `BUILD SUCCESSFUL` message). 
This will generate a HTML version of the User Guide (from the asciidoc version), to be used by the 'Help Window' of the App.
```
I didn't want to redirect the user to another doc at this preliminary stage.

But in my version I forgot to mention Mac. So it should be 
```
... `gradlew processResources` (Mac/Linux: `./gradlew processResources`). It should finish the `BUILD SUCCESSFUL` message. ...

Comment (Zhiyuan-Amos) [reply docs/DeveloperGuide.adoc]: Ok, I will update this segment to use what you've written.

**Comment by Zhiyuan-Amos** [comment]
@damithc updated.

File: docs/DeveloperGuide.adoc [hunk 9]
```diff
@@ -50,6 +50,8 @@ Restart the IDE to complete the installation.
 . Locate the `build.gradle` file and select it. Click `OK`
 . Click `Open as Project`
 . Click `OK` to accept the default settings
+. Open a console and run the command `gradlew processResources` (Mac/Linux: `./gradlew processResources`). It should finish with the `BUILD SUCCESSFUL` message. +
+This will generate a HTML version of the User Guide (from the asciidoc version), to be used by the 'Help Window' of the App.
```
Comment (pyokagan) [inline docs/DeveloperGuide.adoc]: Could we make this more general? e.g. `This will generate all resources required by the application and tests`. We may be adding more resource preprocessing in the future.

Comment (damithc) [reply docs/DeveloperGuide.adoc]: Yup, good idea. 👍

File: docs/DeveloperGuide.adoc (hunk 7 above)
Comment (pyokagan) [reply docs/DeveloperGuide.adoc]: > you're saying that cos our main code base depends on UserGuide.html, as such UserGuide.html should be committed as well is it?

No, I meant that we should commit the `.idea` directory, especially the `.idea/runConfigurations/` directory.

Comment (pyokagan) [reply docs/DeveloperGuide.adoc]: > No, I meant that we should commit the .idea directory, especially the .idea/runConfigurations/ directory.

Not that I think that this would be good practice (since the .idea project files repeat some information in the build.gradle file, i.e. its not DRY). If this was any other project I would expect that developers know how to set up their own run configurations, regardless of which IDE they choose to use. But, we need to make things easy for students, so ¯\\\_(ツ)\_/¯

Comment (Zhiyuan-Amos) [reply docs/DeveloperGuide.adoc]: Understood, much thanks for your explanation Paul!
