### PR TITLE
Cannot add a label called `location` in person card #336

### LINKED ISSUE #336: Cannot add a label called `location` in person card
Steps to reproduce:

- Rename `address` to `location` in `java/seedu/address/ui/PersonCard.java` and `resources/view/PersonListCard.fxml`.
- Do gradle refresh (optional)
- Run the application

Throws the following exception:

```
Exception in thread "JavaFX Application Thread" java.lang.AssertionError: javafx.fxml.LoadException: 
/<path to>/addressbook-level4/bin/view/PersonListCard.fxml

	at seedu.address.ui.UiPart.<init>(UiPart.java:38)
	at seedu.address.ui.UiPart.<init>(UiPart.java:47)
	at seedu.address.ui.PersonCard.<init>(PersonCard.java:30)
	at seedu.address.ui.PersonListPanel$PersonListViewCell.updateItem(PersonListPanel.java:73)
	at seedu.address.ui.PersonListPanel$PersonListViewCell.updateItem(PersonListPanel.java:1)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
	at javafx.scene.control.ListCell.indexChanged(ListCell.java:330)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1797)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1879)
	at com.sun.javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2528)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1189)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException: 
/C:/Users/anarayan/Workspace/addressbook-level4/bin/view/PersonListCard.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at seedu.address.ui.UiPart.<init>(UiPart.java:35)
	... 33 more
Caused by: java.lang.IllegalArgumentException: Can not set javafx.scene.control.Label field seedu.address.ui.PersonCard.location to java.net.URL
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
	at java.lang.reflect.Field.set(Unknown Source)
	at javafx.fxml.FXMLLoader.injectFields(FXMLLoader.java:1163)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2554)
	... 36 more
```

### PR DESCRIPTION
**Pull request by MightyCupcakes**
Closes #336 

This PR does not resolve the issue. It merely documents the fact that there exists such reserved keywords in JavaFX that cannot be used for UI elements' identification.

### CODE REVIEW

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 1]
```diff
@@ -11,20 +11,27 @@
...
     @FXML
     private Label phone;
     @FXML
-    private Label address;
-    @FXML
     private Label email;
     @FXML
     private FlowPane tags;
+    @FXML
+    private HBox cardPane;
```
Comment (acjh) [inline src/main/java/seedu/address/ui/PersonCard.java]: Why were these reordered?

Comment (MightyCupcakes) [inline src/main/java/seedu/address/ui/PersonCard.java]: because a huge javadoc in the middle looks weird. nothing else. It can be moved back.

Comment (acjh) [inline src/main/java/seedu/address/ui/PersonCard.java]: 1. That explains moving `HBox` down, but why `addressbook`?
1. Does this only affect `Label` and not other `FXML` elements?

Comment (MightyCupcakes) [inline src/main/java/seedu/address/ui/PersonCard.java]: 1. This is partly because in the morphing stage, most students might want to change address to location

2. It affects all user-defined fields linked to a UI element

**Comment by CanIHasReview** [comment]
# v1

@MightyCupcakes submitted v1 for review.

* [v1 1/1] [PersonCard: Add documentation about reserved keywords in JavaFX](https://github.com/se-edu/addressbook-level4/pull/339/commits/f19e195b1d2014c4b767520824c62e904345fdb5)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/4c4e1ed78fd8465512c5b434a3c592da52740717...f19e195b1d2014c4b767520824c62e904345fdb5))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/339/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 2]
```diff
@@ -11,20 +11,27 @@
 
     private static final String FXML = "PersonListCard.fxml";
 
+    /**
+     * Note: Certain keywords such as "location" and "resources" are reserved keywords in JavaFX.
+     * As a consequence, {@code Label} fx-id cannot be set to such keywords
```
Comment (yamgent) [inline src/main/java/seedu/address/ui/PersonCard.java]: Following up with @acjh's comments, it seems to affect more than just the `Label` UIs. So perhaps make it more generic like "FXML objects"?

Also it feels weird to be explaining about fx-id here because the code does not use fx-id, but variable names, to link with the FXML files.

Comment (MightyCupcakes) [inline src/main/java/seedu/address/ui/PersonCard.java]: `FXML Objects` is not accurate. I think `UI elements` are more accurate.

> Also it feels weird to be explaining about fx-id here because the code does not use fx-id, but variable names, to link with the FXML files.

The variable name you're referring to is exactly the `fx-id` of the element defined in the FXML file

Comment (yamgent) [inline src/main/java/seedu/address/ui/PersonCard.java]: > The variable name you're referring to is exactly the fx-id of the element defined in the FXML file

Yes, but you might want to make that clearer so that the reader of the comment do not have to mentally make that connection.

File: src/main/java/seedu/address/ui/PersonCard.java (hunk 1 above)
Comment (PierceAndy) [inline src/main/java/seedu/address/ui/PersonCard.java]: 1. To be consistent with the rest of the application, it would be better to not reorder `address` before `name`. 
2. Given that the warning applies just as well to any of the other elements in this code block, and comments generally apply to the entire code block, there's no need to reorder it.

**Comment by CanIHasReview** [comment]
# v2

@MightyCupcakes submitted v2 for review.

* [v2 1/1] [PersonCard: Add documentation about reserved keywords in JavaFX](https://github.com/se-edu/addressbook-level4/pull/339/commits/318296e1b3b1f11444dfb96c8afd6a0d3fcf73d7)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/4c4e1ed78fd8465512c5b434a3c592da52740717...318296e1b3b1f11444dfb96c8afd6a0d3fcf73d7)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/ebb8b146fc985d84d98a6fd11d6ee20534adee5c~1...ebb8b146fc985d84d98a6fd11d6ee20534adee5c))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/339/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
@yl-coder can have a look?

**Comment by damithc** [comment]
@yl-coder reminder

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 3]
```diff
@@ -11,6 +11,14 @@
 
     private static final String FXML = "PersonListCard.fxml";
```
Comment (damithc) [inline src/main/java/seedu/address/ui/PersonCard.java]: Commit message:

> Using any of these strings as a field will result in JavaFX trying to
cast the field to the type of the corresponding value in the namespace.
For example, any fields with the name "location" will be casted into an
URL object which in most cases are not allowed. This is the main cause
of the Exception thrown.

`casted` or `cast`?

The commit message does not mention anything about an exception until that last sentence, so it is a bit strange.

**Comment by CanIHasReview** [comment]
# v3

@MightyCupcakes submitted v3 for review.

* [v3 1/1] [PersonCard: Add documentation about reserved keywords in JavaFX](https://github.com/se-edu/addressbook-level4/pull/339/commits/4d455c0c14763971c3b1ddfffab3217450675784)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/e1eafd1145cb5fdcc81bbacecf9e5145903b3fe2...4d455c0c14763971c3b1ddfffab3217450675784)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/56bfe091d96fe59946536c7ad78e3c60e1b299be~1...56bfe091d96fe59946536c7ad78e3c60e1b299be))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/339/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>
