### PR TITLE
HelpWindow: multiple help windows can be opened #819

### LINKED ISSUE #819: HelpWindow: multiple help windows can be opened
We should disallow multiple help windows to be opened.

To reproduce:
1. Click on `Help` button.
2. Execute "help" in the command box.

### PR DESCRIPTION
**Pull request by yamidark**
Fixes #819.
```
MainWindow creates a new HelpWindow instance and shows it whenever
MainWindow#handleHelp() is called.

This allows multiple help windows to be opened at the same time by
executing HelpCommand, pressing Help menu button or F1 multiple times.

Multiple help windows should be disallowed since each help window
are exactly the same thus having extra copies is unnecessary.

Let's update MainWindow to hold and show a single HelpWindow instance.
```

### CODE REVIEW

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -164,11 +164,15 @@ GuiSettings getCurrentGuiSetting() {
     }
 
     /**
-     * Opens the help window.
+     * Opens the help window or focus on it if already opened.
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/ui/MainWindow.java]: focus**es** on it if **it's** already opened.

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 2]
```diff
@@ -61,4 +61,18 @@ public void show() {
...
+
+    /**
+     * Returns true if the help window is currently being shown.
+     */
+    public boolean isShowing() {
+        return getRoot().isShowing();
+    }
+
+    /**
+     * Focus on the help window.
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/ui/HelpWindow.java]: Focus**es**

**Comment by yamidark** [comment]
>Can we do tests for this?

Will look into adding these tests in.

File: src/test/java/guitests/GuiRobot.java [hunk 3]
```diff
@@ -80,6 +80,13 @@ public boolean isWindowShown(String stageTitle) {
                 .count() >= 1;
     }
 
+    /**
+     * Returns the number of windows with {@code stageTitle} currently open.
+     */
+    public int getNumberOfWindowShown(String stageTitle) {
```
Comment (Zhiyuan-Amos) [inline src/test/java/guitests/GuiRobot.java]: Window**s**

File: src/test/java/guitests/GuiRobot.java [hunk 4]
```diff
@@ -80,6 +80,13 @@ public boolean isWindowShown(String stageTitle) {
                 .count() >= 1;
     }
 
+    /**
+     * Returns the number of windows with {@code stageTitle} currently open.
```
Comment (Zhiyuan-Amos) [inline src/test/java/guitests/GuiRobot.java]: ... **that are** currently open.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 5]
```diff
@@ -55,6 +56,14 @@ public void openHelpWindow() {
         executeCommand(HelpCommand.COMMAND_WORD);
         assertHelpWindowOpen();
 
+        // check that only 1 help window will be opened even with multiple commands
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: asserts that executing multiple commands to open help window will result in only 1 help window opened.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 6]
```diff
@@ -55,6 +56,14 @@ public void openHelpWindow() {
...
+        getMainMenu().openHelpWindowUsingMenu();
+        getMainWindowHandle().focus();
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: we should comment here on why there's a need to call `focus()`.

File: src/test/java/guitests/GuiRobot.java [hunk 7]
```diff
@@ -39,6 +40,14 @@ public void pauseForHuman() {
         sleep(PAUSE_FOR_HUMAN_DELAY_MILLISECONDS);
     }
 
+    /**
+     * Remove focus from the {@code Stage}.
```
Comment (Zhiyuan-Amos) [inline src/test/java/guitests/GuiRobot.java]: Removes focus from the current stage that is in focus,

File: src/test/java/seedu/address/ui/HelpWindowTest.java [hunk 8]
```diff
@@ -30,4 +32,23 @@ public void display() {
         URL expectedHelpPage = HelpWindow.class.getResource(USERGUIDE_FILE_PATH);
         assertEquals(expectedHelpPage, helpWindowHandle.getLoadedUrl());
     }
+
+    @Test
+    public void isShowing() {
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/ui/HelpWindowTest.java]: can we try to follow the 3-part structure for test naming? I can't quite think of an idea on how to name it though.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 9]
```diff
@@ -82,6 +86,12 @@ public void openHelpWindow() {
         assertNotEquals(StatusBarFooter.SYNC_STATUS_INITIAL, getStatusBarFooter().getSyncStatus());
     }
 
+    @Test
+    public void helpWindowIsShowing() {
+        getMainMenu().openHelpWindowUsingAccelerator();
+
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: extra new line

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 10]
```diff
@@ -82,6 +86,12 @@ public void openHelpWindow() {
         assertNotEquals(StatusBarFooter.SYNC_STATUS_INITIAL, getStatusBarFooter().getSyncStatus());
     }
 
+    @Test
+    public void helpWindowIsShowing() {
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: what is this test for?

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 11]
```diff
@@ -56,12 +56,16 @@ public void openHelpWindow() {
         executeCommand(HelpCommand.COMMAND_WORD);
         assertHelpWindowOpen();
 
-        // check that only 1 help window will be opened even with multiple commands
+        // check that if help window is open when command is given, we will focus on the opened help window
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: we shouldn't mix these tests together. Also, you didn't test for the case of `not focused -> handleHelp() -> focused`.

File: src/test/java/systemtests/HelpCommandSystemTest.java (hunk 6 above)
Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Also I think we should separate this into a different test, because we aren't specifically testing for the different ways of opening up help windows.

File: src/test/java/systemtests/HelpCommandSystemTest.java (hunk 10 above)
Comment (yamidark) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Test for `HelpWindow#isShowing()`?

Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: But there's no assertion below to verify that it's showing isn't it :P

Comment (yamidark) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: >But there's no assertion below to verify that it's showing isn't it :P

Whoops, I think this test was brought over the `HelpWindowTest` but I forgot to remove it here.

File: src/test/java/guitests/GuiRobot.java [hunk 12]
```diff
@@ -80,6 +80,13 @@ public boolean isWindowShown(String stageTitle) {
                 .count() >= 1;
     }
 
+    /**
+     * Returns the number of windows with {@code stageTitle} that are currently open.
+     */
+    public int getNumberOfWindowsShown(String stageTitle) {
+        return (int) listTargetWindows().stream()
+                .filter(window -> window instanceof Stage && ((Stage) window).getTitle().equals(stageTitle)).count();
```
Comment (vivekscl) [inline src/test/java/guitests/GuiRobot.java]: I think the `.count();` should be at the bottom. Like each stream operation show start on a new line right?

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 13]
```diff
@@ -73,14 +74,27 @@ public void openHelpWindow() {
         assertNotEquals(StatusBarFooter.SYNC_STATUS_INITIAL, getStatusBarFooter().getSyncStatus());
     }
 
+    @Test
+    public void help_multipleCommands_oneHelpWindowOpen() {
+        // execute multiple commands to open help window
+        getMainMenu().openHelpWindowUsingMenu();
+        // focus on main window so that command to open help window will trigger
```
Comment (vivekscl) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: Hmm, do we need this comment? :thinking:

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 14]
```diff
@@ -73,14 +74,27 @@ public void openHelpWindow() {
...
+        getMainWindowHandle().focus();
+        getMainMenu().openHelpWindowUsingAccelerator();
+        getMainWindowHandle().focus();
+        executeCommand(HelpCommand.COMMAND_WORD);
+        // assert that only 1 help window is open even with multiple commands to open the help window
```
Comment (vivekscl) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: I think this should be:
assert that only 1 help window is open **after using** multiple commands to open the help window

File: src/test/java/guitests/GuiRobot.java [hunk 15]
```diff
@@ -80,6 +80,13 @@ public boolean isWindowShown(String stageTitle) {
                 .count() >= 1;
```
Comment (vivekscl) [inline src/test/java/guitests/GuiRobot.java]: On a side note, now that we have `GuiRobot#getNumberOfWindowsShown(String)` we can use this method in `GuiRobot#isWindowShown(String)` right? Like, `getgetNumberOfWindowsShown(stageTitle) >= 1`.

File: src/test/java/guitests/guihandles/StageHandle.java [hunk 16]
```diff
@@ -43,6 +43,13 @@ public void focus() {
         logger.info("Finishing focus on" + windowTitle);
     }
 
+    /**
+     * Returns true if we are currently focusing on the this stage.
+     */
+    public boolean isFocused() {
```
Comment (vivekscl) [inline src/test/java/guitests/guihandles/StageHandle.java]: This method is never used right? When I checked the usages of this method in other places it says that the method comes from `Window#isFocused()`.

File: src/test/java/guitests/GuiRobot.java [hunk 17]
```diff
@@ -39,6 +40,14 @@ public void pauseForHuman() {
         sleep(PAUSE_FOR_HUMAN_DELAY_MILLISECONDS);
     }
 
+    /**
+     * Removes focus from the current stage that is in focus.
```
Comment (vivekscl) [inline src/test/java/guitests/GuiRobot.java]: I think `Removes focus from the current stage.` suffices since it is implied that the current stage would be in focus.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 18]
```diff
@@ -87,6 +88,21 @@ public void help_multipleCommands_oneHelpWindowOpen() {
         assertEquals(1, guiRobot.getNumberOfWindowsShown(HELP_WINDOW_TITLE));
     }
 
+    @Test
+    public void help_helpWindowNotFocused_helpWindowFocused() {
```
Comment (vivekscl) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: Maybe a better name for this method would be `help_helpWindowOutOfFocus_focusOnHelpWindow`?

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 19]
```diff
@@ -87,6 +88,21 @@ public void help_multipleCommands_oneHelpWindowOpen() {
...
+        getMainMenu().openHelpWindowUsingAccelerator();
+        Stage helpWindowStage = guiRobot.getStage(HELP_WINDOW_TITLE);
+
+        // assert command to open help window focuses on the open help window
```
Comment (vivekscl) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: assert **that** the command  to open help window focuses on the **currently opened** help window

File: src/test/java/seedu/address/ui/HelpWindowTest.java [hunk 20]
```diff
@@ -30,4 +32,26 @@ public void display() {
         URL expectedHelpPage = HelpWindow.class.getResource(USERGUIDE_FILE_PATH);
         assertEquals(expectedHelpPage, helpWindowHandle.getLoadedUrl());
     }
+
+    @Test
+    public void isShowing_helpWindowIsShowing_true() {
+        guiRobot.interact(() -> helpWindow.show());
```
Comment (vivekscl) [inline src/test/java/seedu/address/ui/HelpWindowTest.java]: You could use method references here right? like, `guiRobot.interact(helpWindow::show)`

File: src/test/java/seedu/address/ui/HelpWindowTest.java [hunk 21]
```diff
@@ -30,4 +32,26 @@ public void display() {
...
+        assertTrue(helpWindow.isShowing());
+    }
+
+    @Test
+    public void isShowing_helpWindowIsHiding_false() {
+        guiRobot.interact(() -> helpWindow.getRoot().hide());
```
Comment (vivekscl) [inline src/test/java/seedu/address/ui/HelpWindowTest.java]: Could use method references here as well: `guiRobot.interact(helpWindowgetRoot()::hide)`

File: src/test/java/seedu/address/ui/HelpWindowTest.java [hunk 22]
```diff
@@ -30,4 +32,26 @@ public void display() {
...
+        assertFalse(helpWindow.isShowing());
+    }
+
+    @Test
+    public void focus_helpWindowNotFocused_focused() {
+        guiRobot.interact(() -> helpWindow.show());
```
Comment (vivekscl) [inline src/test/java/seedu/address/ui/HelpWindowTest.java]: Same here. `guiRobot.interact(helpWindow::show)`

File: src/test/java/seedu/address/ui/HelpWindowTest.java [hunk 23]
```diff
@@ -30,4 +32,26 @@ public void display() {
...
+        guiRobot.removeFocus();
+        assertFalse(helpWindow.getRoot().isFocused());
+
+        guiRobot.interact(() -> helpWindow.focus());
```
Comment (vivekscl) [inline src/test/java/seedu/address/ui/HelpWindowTest.java]: Same here. `guiRobot.interact(helpWindow::focus)`

File: src/test/java/systemtests/HelpCommandSystemTest.java (hunk 13 above)
Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Initially, I told @yamidark to write this comment because I thought it would be unclear to people who aren't familiar with ui tests. 

However, yes I agree that this comment doesn't look too nice. Let's leave a new line instead of writing comments to show the demarcation between each opening of HelpWindow.

```java
getMainMenu().openHelpWindowUsingMenu();

getMainWindowHandle().focus();
getMainMenu().openHelpWindowUsingAccelerator();

getMainWindowHandle().focus();
executeCommand(HelpCommand.COMMAND_WORD);

assertEquals(1, guiRobot.getNumberOfWindowsShown(HELP_WINDOW_TITLE));
```

File: src/test/java/systemtests/HelpCommandSystemTest.java (hunk 14 above)
Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: There's no need for this comment; this is intuitive following the test method name and the assert method.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 24]
```diff
@@ -73,14 +74,27 @@ public void openHelpWindow() {
         assertNotEquals(StatusBarFooter.SYNC_STATUS_INITIAL, getStatusBarFooter().getSyncStatus());
     }
 
+    @Test
+    public void help_multipleCommands_oneHelpWindowOpen() {
+        // execute multiple commands to open help window
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: This comment is unnecessary since the test method name is rather descriptive.

File: src/test/java/guitests/GuiRobot.java [hunk 25]
```diff
@@ -39,6 +40,14 @@ public void pauseForHuman() {
         sleep(PAUSE_FOR_HUMAN_DELAY_MILLISECONDS);
     }
 
+    /**
+     * Removes focus from the current stage.
+     */
+    public void removeFocus() {
+        press(KeyCode.ALT, KeyCode.TAB);
+        release(KeyCode.ALT, KeyCode.TAB);
```
Comment (Zhiyuan-Amos) [inline src/test/java/guitests/GuiRobot.java]: Does this work? Cos `Alt-Tab` will be pressed until `release(...)` is called. Therefore, there may be some scenarios when the `Alt-Tab` causes it to revert back to the current stage.

We can take a look at this [SO solution](https://stackoverflow.com/a/25467653/8828382).

File: src/test/java/seedu/address/ui/HelpWindowTest.java [hunk 26]
```diff
@@ -30,4 +32,26 @@ public void display() {
         URL expectedHelpPage = HelpWindow.class.getResource(USERGUIDE_FILE_PATH);
         assertEquals(expectedHelpPage, helpWindowHandle.getLoadedUrl());
     }
+
+    @Test
+    public void isShowing_helpWindowIsShowing_true() {
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/ui/HelpWindowTest.java]: `_returnsTrue`

File: src/test/java/seedu/address/ui/HelpWindowTest.java [hunk 27]
```diff
@@ -30,4 +32,26 @@ public void display() {
...
+        guiRobot.interact(helpWindow::show);
+        assertTrue(helpWindow.isShowing());
+    }
+
+    @Test
+    public void isShowing_helpWindowIsHiding_false() {
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/ui/HelpWindowTest.java]: `_returnsFalse`

File: src/test/java/guitests/GuiRobot.java [hunk 28]
```diff
@@ -75,11 +75,17 @@ public void waitForEvent(BooleanSupplier event, int timeOut) {
...
     }
 
+    /**
+     * Returns the number of windows with {@code stageTitle} that are currently open.
+     */
+    public int getNumberOfWindowsShown(String stageTitle) {
+        return (int) listTargetWindows().stream()
+                .filter(window -> window instanceof Stage && ((Stage) window).getTitle().equals(stageTitle))
+                .count();
+    }
```
Comment (Zhiyuan-Amos) [inline src/test/java/guitests/GuiRobot.java]: missing new line

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 29]
```diff
@@ -1,5 +1,6 @@
 package systemtests;
 
+import static guitests.guihandles.HelpWindowHandle.HELP_WINDOW_TITLE;
```
Comment (vivekscl) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: There is no need to import this. Since it's a class level constant, you can just call it using the class name. Refer to this [SO](https://stackoverflow.com/questions/824011/a-simple-way-to-create-static-imports-for-constants-in-existing-code) post for more information on why it's better not to use static imports.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 30]
```diff
@@ -87,6 +88,21 @@ public void help_multipleCommands_oneHelpWindowOpen() {
         assertEquals(1, guiRobot.getNumberOfWindowsShown(HELP_WINDOW_TITLE));
     }
 
+    @Test
+    public void help_helpWindowOutOfFocus_focusOnHelpWindow() {
+        getMainMenu().openHelpWindowUsingAccelerator();
+        Stage helpWindowStage = guiRobot.getStage(HELP_WINDOW_TITLE);
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: You should not access the `Stage` directly, but access them through `Handle`s :P Which is why you need this [method](https://github.com/se-edu/addressbook-level4/compare/c94261e57a5ee4a79f983cd5c601f588d7e87d8c~1...c94261e57a5ee4a79f983cd5c601f588d7e87d8c#diff-5600101e1e39f84f3280c83b9f3d20edL49). But since the method is only used in `HelpWindowHandle`, maybe we should put there instead of `StageHandle`.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 31]
```diff
@@ -73,14 +74,27 @@ public void openHelpWindow() {
...
+    }
+
     /**
      * Asserts that the help window is open, and closes it after checking.
      */
     private void assertHelpWindowOpen() {
         assertTrue(ERROR_MESSAGE, HelpWindowHandle.isWindowPresent());
         guiRobot.pauseForHuman();
 
-        new HelpWindowHandle(guiRobot.getStage(HelpWindowHandle.HELP_WINDOW_TITLE)).close();
```
Comment (vivekscl) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: You can bring back this line after removing the static import as mentioned previously.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 32]
```diff
@@ -87,6 +88,21 @@ public void help_multipleCommands_oneHelpWindowOpen() {
...
+        Stage helpWindowStage = guiRobot.getStage(HELP_WINDOW_TITLE);
+
+        // assert command to open help window focuses on the open help window
+        getMainWindowHandle().focus();
+        getMainMenu().openHelpWindowUsingAccelerator();
+        assertTrue(helpWindowStage.isFocused());
+
+        getMainWindowHandle().focus();
+        executeCommand(HelpCommand.COMMAND_WORD);
+        assertTrue(helpWindowStage.isFocused());
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: I wonder whether there's a need for lines 101-103.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 33]
```diff
@@ -87,6 +88,21 @@ public void help_multipleCommands_oneHelpWindowOpen() {
         assertEquals(1, guiRobot.getNumberOfWindowsShown(HELP_WINDOW_TITLE));
     }
 
+    @Test
+    public void help_helpWindowOutOfFocus_focusOnHelpWindow() {
+        getMainMenu().openHelpWindowUsingAccelerator();
+        Stage helpWindowStage = guiRobot.getStage(HELP_WINDOW_TITLE);
+
+        // assert command to open help window focuses on the open help window
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: I think this comment is unnecessary because the test method name is self-explanatory.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 34]
```diff
@@ -87,6 +88,21 @@ public void help_multipleCommands_oneHelpWindowOpen() {
...
+        getMainWindowHandle().focus();
+        getMainMenu().openHelpWindowUsingAccelerator();
+        assertTrue(helpWindowStage.isFocused());
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: after line 97 we should `assertFalse(helpWindowStage.isFocused());`

Comment (yamidark) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: >after line 97 we should assertFalse(helpWindowStage.isFocused());

For some reason, when the test is done in `headless` mode, this `assertFalse` line would always fail, which is why I removed it.

Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: I tried, it seems that when the test is executed on `headless` mode and `getMainWindowHandle().focus()` is called, weirdly both `MainWindow` and `HelpWindow` are in focus.

Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: As such, this actually means that the test isn't executing as per intended, since `MainWindow` was already in focus from the start.

Comment (yamidark) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Tried using some other `JavaFx` object stages, but couldn't really get them to work, so I used the help windows to try this test:

```Java
    private HelpWindow hw1;
    private HelpWindow hw2;

    @Test
    public void test() throws Exception {
        guiRobot.interact(() -> hw1 = new HelpWindow());
        guiRobot.interact(() -> hw2 = new HelpWindow());

        FxToolkit.setupStage((stage) -> stage.setScene(hw1.getRoot().getScene()));
        FxToolkit.setupStage((stage) -> stage.setScene(hw2.getRoot().getScene()));
        FxToolkit.showStage();

        guiRobot.interact(hw1::show);
        guiRobot.interact(hw2::show);

        assertFalse(hw1.getRoot().isFocused());
        assertTrue(hw2.getRoot().isFocused());
        guiRobot.interact(hw1::focus);
        assertTrue(hw1.getRoot().isFocused());
        assertFalse(hw2.getRoot().isFocused());
    }
```

Test passes normally when run in `Intellji`, but when run on `gradlew` `headless` mode test fails as the 2 help window aren't in focus even after showing.
We can also focus on both of them in `headless` mode too when only 1 of them should be in focus at a time.

Comment (yamidark) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Should we leave this test like this for now, and add comments that in `headless` mode any of the windows that were once in focus will never leave focus?

Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Good job investigating 👍 Okay, the issue now is: We are updating the main code base but we aren't able to write tests to verify the updated behavior.

As such, we should remove this test because this test doesn't do anything. `getMainWindowHandle().focus()` is supposed to remove the focus from `HelpWindow`, then we verify that executing help command will cause the `HelpWindow` to go back in focus. But now, `HelpWindow` doesn't go out of focus, so we don't get to test the functionality that executing help command will cause the `HelpWindow` to go back in focus.

However, prior to removing this test, I think it's good that we make a sample class so that we can raise an issue to `TestFX` for verification. This class shouldn't be tied to the rest of our code base; you should create a new project e.g.:

```java
public class Foo {
    public static void main(String args[]) {
        // open 2 stages
        // perform assertions here. It doesn't matter that this isn't a test class, we can still do assertFalse etc here.
    }
}
```

Once we have raised an issue in TestFX and it is verified, then we can leave a comment in our code base that we aren't writing a test for this method because of the issue in TestFX. :)

Comment (yamidark) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Ok, managed to reproduce this using 2 `VBox`:

```Java
    Stage stage1;
    Stage stage2;

    @Test
    public void test() throws Exception {
        FxRobot fxRobot = new FxRobot();
        FxToolkit.registerPrimaryStage();

        VBox vBox = new VBox();
        Scene scene = FxToolkit.setupScene(() -> new Scene(vBox,300,250));
        fxRobot.interact(() -> {
            stage1 = new Stage();
            stage1.setScene(scene);
        });

        VBox vBox2 = new VBox();
        Scene scene2 = FxToolkit.setupScene(() -> new Scene(vBox2,300,250));
        fxRobot.interact(() -> {
            stage2 = new Stage();
            stage2.setScene(scene2);
        });

        fxRobot.interact(stage1::show);
        assertTrue(stage1.isFocused());
        assertFalse(stage2.isFocused());

        fxRobot.interact(stage2::show);
        assertFalse(stage1.isFocused());
        assertTrue(stage2.isFocused());
    }
```
Test passes when run normally, but fails on `headless` since `assertFalse(stage1.isFocused())` fails.
So I should post this issue on TestFX?

Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Great work. Just wondering whether there's a need for the VBox to be present I.e. Can we simplify our code further? Otherwise, I think we are good to go. :+1

Comment (yamidark) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Tried doing this with just 2 `stage` alone, but the test doesn't work, can't seem to even focus on them, and the test hangs in `gradle` `headless` mode. So, I believe there's a need for the VBox here.

Comment (Zhiyuan-Amos) [reply src/test/java/systemtests/HelpCommandSystemTest.java]: Ok. Yup, do post this issue on TestFX, include the whole class (not just the test method) ya :)

**Comment by yamidark** [comment]
Issue posted on [TestFX](https://github.com/TestFX/TestFX/issues/548).

**Comment by Zhiyuan-Amos** [comment]
This [test](https://github.com/se-edu/addressbook-level4/compare/1f16b1c764d337e10402329e5cd6ad40345ebfc3~1...1f16b1c764d337e10402329e5cd6ad40345ebfc3#diff-3558a92e4dc4346714c9e81d44c8ebfcL49) shouldn't be deleted as we still need to test that `HelpWindow#focus()` works.

File: src/test/java/systemtests/HelpCommandSystemTest.java [hunk 35]
```diff
@@ -73,6 +73,19 @@ public void openHelpWindow() {
         assertNotEquals(StatusBarFooter.SYNC_STATUS_INITIAL, getStatusBarFooter().getSyncStatus());
     }
 
+    @Test
+    public void help_multipleCommands_oneHelpWindowOpen() {
```
Comment (Zhiyuan-Amos) [inline src/test/java/systemtests/HelpCommandSystemTest.java]: maybe we should be clearer and specify **only**OneHelpWindowOpen.

**Comment by Zhiyuan-Amos** [comment]
@yamidark you can continue on this PR since [Monocle](https://github.com/javafxports/openjdk-jfx/issues/50) has responded by placing a bug tag. :)

**Comment by yamidark** [comment]
>Create an issue in our code base to note that we need to write test for this method, but it cannot be written 

Noted. Will do that after this PR is merged.

**Comment by Zhiyuan-Amos** [comment]
@yamidark can do last call for reviews on Gitter? :)

**Comment by Zhiyuan-Amos** [comment]
@yamidark great work! 👍 :)
