### PR TITLE
HelpWindowTest: Write header comments concerning possible test failure #680

### LINKED ISSUE #680: guitests.HelpWindowTest.openHelpWindow failing on Windows
Failing in one of my Comps, even after multiple tries. This was failing y'day too. I thought the two failures are related and reported only one of them (#672). 
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at guitests.HelpWindowTest.assertHelpWindowNotOpen(HelpWindowTest.java:56)
	at guitests.HelpWindowTest.openHelpWindow(HelpWindowTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #680.

### CODE REVIEW

**Comment by damithc** [comment]
If passes the previous line but fails at line 34 now. Apparently it tries to click on the menu item but ends up clicking outside it. The problem may be in the TextFx itself (some incompatibility with my Windows set up). Even in previous semesters there were students who couldn't get the help window test to pass. In my case it passes in my office comp but not here although both are Win 10 (but one is boot camp). I guess if a student runs into this problem we'll have ask them to run in headless mode.

**Comment by Zhiyuan-Amos** [comment]
Noted, does documenting it in the header comments of the test class sufficient?

**Comment by eugenepeh** [comment]
This problem exist since back in the semester I'm taking CS2103... however this only occurs on certain computer, e.g. it doesn't work on my asus but works on my teammate's surface pro.

Perhaps this is a some sort of Windows only issue? maybe missing some windows distributed packages.

**Comment by Zhiyuan-Amos** [comment]
Yup, I'll drop an issue to TestFX and see how it goes. ^^

**Comment by Zhiyuan-Amos** [comment]
@eugenepeh @damithc do take a look at the header comments to see if it's fine ^^

**Comment by eugenepeh** [comment]
Looks good. Since its not exactly a class header, i guess its fine for a temporary solution :P

**Comment by Zhiyuan-Amos** [comment]
Ready for review; at SoC and can't go to CanIHasReview. XD

File: src/test/java/guitests/HelpWindowTest.java [hunk 1]
```diff
@@ -9,6 +9,10 @@
 import seedu.address.logic.commands.HelpCommand;
 
 public class HelpWindowTest extends AddressBookGuiTest {
+    private static final String ERROR_MESSAGE = "On some computers, this test may fail when run on non-headless mode "
```
Comment (damithc) [inline src/test/java/guitests/HelpWindowTest.java]: Perhaps add something like `ATTENTION!!!! : ` Otherwise this message could get lost in the middle of a wall of text.

Comment (Zhiyuan-Amos) [reply src/test/java/guitests/HelpWindowTest.java]: Noted! However, I am wondering whether it's necessary because the test will fail at the line `assertTrue(ERROR_MESSAGE, var)`, and I think it's quite intuitive that the student will check out the error message ><

Comment (damithc) [reply src/test/java/guitests/HelpWindowTest.java]: Just a cosmetic suggestion. Can ignore. I'm ok with the current version.

Comment (Zhiyuan-Amos) [reply src/test/java/guitests/HelpWindowTest.java]: Made the changes; will merge it now :)

**Comment by Zhiyuan-Amos** [comment]
@eugenepeh since you mentioned [earlier](https://github.com/se-edu/addressbook-level4/pull/694#issuecomment-330759273) that your test may fail while running on your asus computer, can you help me to verify whether it's working now? :) That's cos I checked with Prof Damith and he mentioned that his Windows computer no longer faces this issue.

The test is now in `HelpCommandSystemTest`.

**Comment by eugenepeh** [comment]
image

It hates me.

**Comment by Zhiyuan-Amos** [comment]
@eugenepeh Oh man :< Just to double check: The test failure is caused by the cursor moving to the wrong location?

Also, can you help me to verify if your display scaling is at 100%? Someone raised an issue on TestFX mentioning that he faces the same issue as well when his PC display scaling is not at 100%. However, if he resets the display scaling back to 100%, it works fine.

Thanks again Eugene ^^

**Comment by eugenepeh** [comment]
>@eugenepeh Oh man :< Just to double check: The test failure is caused by the cursor moving to the wrong location?

Yup

image

hmm, mine is at 150%. I will try it at 100% later after my FYP meeting.

**Comment by eugenepeh** [comment]
image

Nope, doesn't work o_o
