### PR TITLE
Tests: Update helper methods to throw unchecked Exceptions #568

### LINKED ISSUE #568: Standardize all test related methods to throw AssertionError instead of checked exceptions
Some test related methods throw checked exceptions. This is unnecessary as callers are not expected to handle these exceptions, as we are expected to pass valid input into these test methods. As such, we should throw `AssertionError`, since `AssertionError` symbolises programmer error. 

Let's change all test related methods to throw `AssertionError`s instead of checked exceptions. By doing so, we can use lambda expressions to call these methods. As such, let's update the code base to use lambda expressions as well.

E.g `UiPartRule#setUiPart(UiPart<? extends Parent>)` throws a `TimeoutException`.

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #568

### CODE REVIEW

**Comment by Zhiyuan-Amos** [comment]
I did not throw AssertionError for all of them. Some of them I threw IllegalArgumentException instead. @yamgent :)

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/1] [Tests: Helper methods throw unchecked Exceptions](https://github.com/se-edu/addressbook-level4/pull/628/commits/88d0fc314776030e0528a382c451e040e2b11530)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/ddcea63541d5f73f6b3d7c6c7676d4db2bb1af9a...88d0fc314776030e0528a382c451e040e2b11530))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/628/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 1]
```diff
@@ -97,10 +97,14 @@ private void assertCommandBehavior(Class<?> expectedException, String inputComma
         assertEquals(expectedModel, model);
     }
 
-    private void assertHistoryCorrect(String... expectedCommands) throws Exception {
```
Comment (eugenepeh) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: Need a header comment here because it exceeds the length that qualifies it as non-trivial

File: src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java [hunk 2]
```diff
@@ -88,20 +88,24 @@ private UserPrefs getTypicalUserPrefs() {
...
     }
 
     @Test
-    public void saveUserPrefs_nullFilePath_throwsNullPointerException() throws IOException {
+    public void saveUserPrefs_nullFilePath_throwsNullPointerException() {
         thrown.expect(NullPointerException.class);
         saveUserPrefs(new UserPrefs(), null);
     }
 
-    private void saveUserPrefs(UserPrefs userPrefs, String prefsFileInTestDataFolder) throws IOException {
```
Comment (eugenepeh) [inline src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java]: and also here, thanks! :)

Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java]: You missed out `XmlAddressBookStorageTest#saveAddressBook(ReadOnlyAddressBook addressBook, String filePath)` :P 

What should I do if I don't know what's the method doing :(

File: src/test/java/seedu/address/logic/LogicManagerTest.java (hunk 1 above)
Comment (yamgent) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: @eugenepeh what is the specified length for it to be non-trivial? I was hoping that we can have some lee-way for really simple private methods, they are not exposed as API anyway.

Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: I think it's 3 lines. As such, the moment you have a try-catch block... it's over :P

Comment (yamgent) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: Maybe we should up the number of lines to 6. We can justify it as such:

```java
1. try {
2.     // simple assignment
3. } catch (Exception e) {
4.     // simple error handling
5. }
6. // just a buffer line in case either of the two blocks needs one more line.
```

Comment (eugenepeh) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: I'm have no issue up'ing it to 6 though but then its universal check so those that does not have try catch might not be trivial :P

Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: Is there a way to suppress the check if we deem that the comments aren't necessary? ^^

So we can have a hard limit such as 3 lines for private and 1 line for public, but we can suppress the check when there's special cases like try-catch blocks.

6 lines seem a bit too much because you can do quite a bit in 6 lines i.e. it isn't a trivial method. :P

**Comment by CanIHasReview** [comment]
# v2

@Zhiyuan-Amos submitted v2 for review.

* [v2 1/1] [Tests: Helper methods throw unchecked Exceptions](https://github.com/se-edu/addressbook-level4/pull/628/commits/59dd0d5843cb8ee1dd1f91cd7f23286ee8973995)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/ddcea63541d5f73f6b3d7c6c7676d4db2bb1af9a...59dd0d5843cb8ee1dd1f91cd7f23286ee8973995)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/78cb843164a0c6e38abe0087f07b896af6c16760~1...78cb843164a0c6e38abe0087f07b896af6c16760))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/628/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
@eugenepeh I will wait for your PR to be merged first, so that you won't face too many merge conflicts :P

**Comment by CanIHasReview** [comment]
# v3

@Zhiyuan-Amos submitted v3 for review.

* [v3 1/1] [Tests: Update helper methods to throw unchecked Exceptions](https://github.com/se-edu/addressbook-level4/pull/628/commits/fc5f27eab6b6f301f021f2292cd432de2d04cbce)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/da1601d8421af0408fa699ea96cdebb86c6520b3...fc5f27eab6b6f301f021f2292cd432de2d04cbce)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/dc70024d5218d2143325d9f30fe34dd02f1b5893~1...dc70024d5218d2143325d9f30fe34dd02f1b5893))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/628/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
@yamgent require your approval here ^^ Then tag prof afterwards; prefer to have this merged before merging all the other tests cos the merge conflict gonna be quite crazy.

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 3]
```diff
@@ -101,10 +101,14 @@ private void assertCommandBehavior(Class<?> expectedException, String inputComma
...
-        CommandResult result = logic.execute(HistoryCommand.COMMAND_WORD);
-        String expectedMessage = String.format(HistoryCommand.MESSAGE_SUCCESS,
-                String.join("\n", expectedCommands));
-        assertEquals(expectedMessage, result.feedbackToUser);
+    private void assertHistoryCorrect(String... expectedCommands) {
+        try {
+            CommandResult result = logic.execute(HistoryCommand.COMMAND_WORD);
+            String expectedMessage = String.format(HistoryCommand.MESSAGE_SUCCESS,
+                    String.join("\n", expectedCommands));
```
Comment (damithc) [inline src/test/java/seedu/address/logic/LogicManagerTest.java]: How about this line wrapping?
```java
String expectedMessage = String.format(
        HistoryCommand.MESSAGE_SUCCESS, String.join("\n", expectedCommands));
```
