### PR TITLE
ParserUtil: use exceptions for error handling #303

### LINKED ISSUE #303: ParserUtil: use exceptions for error handling
Some of the methods of `ParserUtil` currently use `Optional` values to indicate errors. Besides `Optional` being clunky to use due to the lack of sufficient language support, we also run into the problem of being unable to differentiate between whether an `Optional` is empty because of an error or whether it is just because it is not present (e.g. `ParserUtil#parseName()` vs `ParserUtil#parseIndex()`)

We should probably use checked exceptions instead to indicate errors that must be handled.

### PR DESCRIPTION
**Pull request by yamgent**
Fixes #303.

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@yamgent submitted v1 for review.

* [v1 1/1] [Modify ParserUtil\#parseIndex\(String\) to throw IllegalValueException](https://github.com/se-edu/addressbook-level4/pull/403/commits/380349b2ca214d58f10707ffa1a85395c15adaa9)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/8e4d306e4cc579b4e967b267a3c41aafcedbc700...380349b2ca214d58f10707ffa1a85395c15adaa9))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/403/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -18,8 +19,15 @@
      * and returns an DeleteCommand object for execution.
      */
     public Command parse(String args) {
+        Optional<Integer> index;
+
+        try {
+            index = ParserUtil.parseIndex(args);
+        } catch (IllegalValueException e) {
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: `IllegalValueException ive`, as per code base :>

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -23,12 +23,11 @@
 
     /**
      * Returns the specified index in the {@code command} if it is a positive unsigned integer
-     * Returns an {@code Optional.empty()} otherwise.
      */
-    public static Optional<Integer> parseIndex(String command) {
+    public static Optional<Integer> parseIndex(String command) throws IllegalValueException {
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: can return `Integer` instead of `Optional<Integer>` since we are not returning `Optional.empty()` anymore :>

File: src/main/java/seedu/address/logic/parser/SelectCommandParser.java [hunk 3]
```diff
@@ -18,7 +19,15 @@
      * and returns an SelectCommand object for execution.
      */
     public Command parse(String args) {
-        Optional<Integer> index = ParserUtil.parseIndex(args);
+        Optional<Integer> index;
+
+        try {
+            index = ParserUtil.parseIndex(args);
+        } catch (IllegalValueException e) {
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/parser/SelectCommandParser.java]: ive

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 2 above)
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Then there's no need for these checks `if (!index.isPresent())` in the various classes.

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 4]
```diff
@@ -34,8 +35,15 @@ public Command parse(String args) {
...
-        if (!index.isPresent()) {
+        if (!preambleFields.get(0).isPresent()) {
+            return new IncorrectCommand(String.format(MESSAGE_INVALID_COMMAND_FORMAT, EditCommand.MESSAGE_USAGE));
+        }
+
+        int index;
+
+        try {
+            index = ParserUtil.parseIndex(preambleFields.get(0).get());
+        } catch (NoSuchElementException | IllegalValueException ive) {
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java]: remove NSEE :)

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 5]
```diff
@@ -22,15 +22,14 @@
 public class ParserUtil {
 
     /**
-     * Returns the specified index in the {@code command} if it is a positive unsigned integer
-     * Returns an {@code Optional.empty()} otherwise.
+     * Returns the specified index in the {@code command} if it is a positive unsigned integer.
```
Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Add a `throws {@code IllegalValueException} if the specified index is not a valid integer` ?

**Comment by CanIHasReview** [comment]
# v2

@yamgent submitted v2 for review.

* [v2 1/1] [Modify ParserUtil\#parseIndex\(String\) to throw IllegalValueException](https://github.com/se-edu/addressbook-level4/pull/403/commits/b9a303b5e1cbba2ddcfa3b18c2740f6a4cc8afe2)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/8e4d306e4cc579b4e967b267a3c41aafcedbc700...b9a303b5e1cbba2ddcfa3b18c2740f6a4cc8afe2)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/e8b0de128c6cc8f049294d089a17fb5287367ca2~1...e8b0de128c6cc8f049294d089a17fb5287367ca2))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/403/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 6]
```diff
@@ -23,14 +23,14 @@
 
     /**
      * Returns the specified index in the {@code command} if it is a positive unsigned integer
-     * Returns an {@code Optional.empty()} otherwise.
+     * @throws IllegalValueException if the specified index is not a valid integer.
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: `is an invalid integer`.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 7]
```diff
@@ -23,14 +23,14 @@
...
      */
-    public static Optional<Integer> parseIndex(String command) {
+    public static int parseIndex(String command) throws IllegalValueException {
         String index = command.trim();
         if (!StringUtil.isUnsignedInteger(index)) {
-            return Optional.empty();
+            throw new IllegalValueException("index is not an unsigned integer");
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Should refactor the string out. Also, change the string to something like `Invalid index`.

Comment (yamgent) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: The convention in the codebase is to not refactor out the string unless it is repeated multiple times throughout the codebase.

Comment (yamgent) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Also seems counter-intuitive to remove details in the error messages :P. `Invalid index` would make it harder to understand the problem.

Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Then we can probably make it more informative i.e `Index is not a positive unsigned integer.` (also capitalise first letter, with a period at the end). Since in codebase, sometimes the information in IVE is being used display error messages to the user. So maybe we should make it look more of a proper sentence? :>

**Comment by CanIHasReview** [comment]
# v3

@yamgent submitted v3 for review.

* [v3 1/1] [Modify ParserUtil\#parseIndex\(String\) to throw IllegalValueException](https://github.com/se-edu/addressbook-level4/pull/403/commits/0e5d0346e2bfab3e2381c4df51372cb844c107cb)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/8e4d306e4cc579b4e967b267a3c41aafcedbc700...0e5d0346e2bfab3e2381c4df51372cb844c107cb)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/c0cea1b5973418d966c754188125ca3f75fc0536~1...c0cea1b5973418d966c754188125ca3f75fc0536))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/403/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v4

@yamgent submitted v4 for review.

* [v4 1/1] [Modify ParserUtil\#parseIndex\(String\) to throw IllegalValueException](https://github.com/se-edu/addressbook-level4/pull/403/commits/696413d85de0ca1065c4e33bdd361278fdab47a4)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/8e4d306e4cc579b4e967b267a3c41aafcedbc700...696413d85de0ca1065c4e33bdd361278fdab47a4)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level4/compare/eca446c14619760a5c2bac053e35311052d1cad1~1...eca446c14619760a5c2bac053e35311052d1cad1))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/403/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
@yamgent can issue a 'last call for reviews' for this

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 8]
```diff
@@ -23,14 +23,14 @@
 
     /**
      * Returns the specified index in the {@code command} if it is a positive unsigned integer
-     * Returns an {@code Optional.empty()} otherwise.
+     * @throws IllegalValueException if the specified index is an invalid integer.
```
Comment (eugenepeh) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Shouldn't it be invalid `unsigned` integer? Since -1 is still technically a valid integer :-P
Also, I think that `Returns the specified index in the {@code command} if it is a positive unsigned integer` can be reduced to `Returns the specified index in the {@code command}` since the exception has been specified.

Comment (yamgent) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Good point, thanks for the review.

**Comment by CanIHasReview** [comment]
# v5

@yamgent submitted v5 for review.

* [v5 1/1] [Modify ParserUtil\#parseIndex\(String\) to throw IllegalValueException](https://github.com/se-edu/addressbook-level4/pull/403/commits/4d3156fe7075bfca5a0c00619f90f786ab2a3cff)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/05a676443ef9016e1c6975b06d6fb322b43b4dc2...4d3156fe7075bfca5a0c00619f90f786ab2a3cff)) ([:chart_with_upwards_trend: Interdiff between v4 and v5](https://github.com/se-edu/addressbook-level4/compare/da0e615e26511729567d1bd1bffcb8cd0d5588bc~1...da0e615e26511729567d1bd1bffcb8cd0d5588bc))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/403/5/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>
