### PR TITLE
Fix tests failure #602

### LINKED ISSUE #602: Some tests fail on Windows in headful mode
7 tests failed in the first round and some of them still failed after a retry (screenshot below is for the retry). But all pass in headless mode.
image

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #602. Part of #559.

### CODE REVIEW

**Comment by Zhiyuan-Amos** [comment]
@yamgent classes like `ExitCommandTest`, `HelpCommandTest` use `EventsCollector`, which in turn calls the `static` `EventsCenter`. This is gonna be pretty problematic in the long run because every other test that uses `EventsCollector` will need to remember to call `EventsCenter.clearSubscribers()`.

One quick solution is to make a test superclass (like `AddressBookGuiTest` and `AddressBookSystemTest`) to call `EventsCenter.clearSubscribers()` after each test case (i.e. Annotate it with `@After`). However, this means other tests such as `AddCommandTest` that don't use `EventsCollector` will be calling this as well, which is unnecessary.

What do you think? 

Additional thoughts, just recording here in the event we need to refer to this: I thought of using `Object#finalize()` to call `EventsCenter.clearSubscribers()`, but upon reading up on it, I realized that it's not a really good idea (https://softwareengineering.stackexchange.com/questions/288715/is-overriding-object-finalize-really-bad), and we can't do that too since `eventBus` will be holding a reference to the `EventsCollector` object.

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/5] [AddressBookGuiTest: Shift EventsCenter\#clearSubscribers\(\)](https://github.com/se-edu/addressbook-level4/pull/613/commits/c9eeff4cda88ff513d3e56763640bd15d0622db9)
* [v1 2/5] [Update tests to call EventsCenter\#clearSubscribers\(\)](https://github.com/se-edu/addressbook-level4/pull/613/commits/8a5e43b249ade7254b9855489584c63990072211)
* [v1 3/5] [TypicalPersons: Update static constant to getter method](https://github.com/se-edu/addressbook-level4/pull/613/commits/0fdf3a4dac72212b9fef48026fb9a759188a6592)
* [v1 4/5] [BrowserPanel: Update string constants](https://github.com/se-edu/addressbook-level4/pull/613/commits/d5b1d910c167e7b3d7181981f834e822b01a67e4)
* [v1 5/5] [BrowserPanelHandle: Post WebViewLoadedEvent when WebView is done loading](https://github.com/se-edu/addressbook-level4/pull/613/commits/4c55bbb95e2c02155d90af80f83a3b5dba9c4443)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/816f07f953e8855556176cc0b6f9ca8a13a7b0f7...4c55bbb95e2c02155d90af80f83a3b5dba9c4443))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/613/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by yamgent** [comment]
> @yamgent classes like ExitCommandTest, HelpCommandTest use EventsCollector, which in turn calls the static EventsCenter. This is gonna be pretty problematic in the long run because every other test that uses EventsCollector will need to remember to call EventsCenter.clearSubscribers().

Consider using a JUnit rule. For example, [StageRule.java](https://github.com/se-edu/addressbook-level4/blob/master/src/test/java/seedu/address/ui/testutil/StageRule.java) automatically sets up and clean up JavaFx appropriately before and after tests. One would just need to use this rule in order to gain these behaviours automatically. For example, [GuiUnitTest.java](https://github.com/se-edu/addressbook-level4/blob/master/src/test/java/seedu/address/ui/GuiUnitTest.java) uses `UiPartRule` (a subclass of `StageRule`), so the setup and clean up is done automatically for GuiUnitTest.

File: src/test/java/guitests/guihandles/BrowserPanelHandle.java [hunk 1]
```diff
@@ -16,6 +22,14 @@
 
     public BrowserPanelHandle(Node browserPanelNode) {
         super(browserPanelNode);
+        WebView webView = getChildNode(BROWSER_ID);
```
Comment (yamgent) [inline src/test/java/guitests/guihandles/BrowserPanelHandle.java]: Can add a comment to explain what is going on here.

**Comment by CanIHasReview** [comment]
# v2

@Zhiyuan-Amos submitted v2 for review.

* [v2 1/7] [AddressBookGuiTest: Shift EventsCenter\#clearSubscribers\(\)](https://github.com/se-edu/addressbook-level4/pull/613/commits/c9eeff4cda88ff513d3e56763640bd15d0622db9)
* [v2 2/7] [Add EventsCollectorRule](https://github.com/se-edu/addressbook-level4/pull/613/commits/62de04adea4d5dcd2d065923156ca02b5a24a9a4)
* [v2 3/7] [Update tests to use EventsCollectorRule](https://github.com/se-edu/addressbook-level4/pull/613/commits/9615a54d6bc5178bafa7d151d1268d14c8ab0181)
* [v2 4/7] [Nest EventsCollector in EventsCollectorRule](https://github.com/se-edu/addressbook-level4/pull/613/commits/f6c7ee9c68900dacbeccd5a8b393519ea22dd313)
* [v2 5/7] [TypicalPersons: Update static constant to getter method](https://github.com/se-edu/addressbook-level4/pull/613/commits/587fe5296d66ea237c10ccf842ef7021144d5691)
* [v2 6/7] [BrowserPanel: Update string constants](https://github.com/se-edu/addressbook-level4/pull/613/commits/0a2533dc038d37a98eaac2b9eebbc948f37b604f)
* [v2 7/7] [BrowserPanelHandle: Post WebViewLoadedEvent when WebView is done loading](https://github.com/se-edu/addressbook-level4/pull/613/commits/85f09f17faaf930462a36ea5897846a5d2199636)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/816f07f953e8855556176cc0b6f9ca8a13a7b0f7...85f09f17faaf930462a36ea5897846a5d2199636)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/7c7667d83b9fe66ba6bd1c6277503860b64fadd4~1...7c7667d83b9fe66ba6bd1c6277503860b64fadd4))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/613/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

File: src/test/java/seedu/address/logic/commands/SelectCommandTest.java [hunk 2]
```diff
@@ -97,32 +100,29 @@ public void equals() {
...
         SelectCommand selectCommand = prepareCommand(index);
         CommandResult commandResult = selectCommand.execute();
 
         assertEquals(String.format(SelectCommand.MESSAGE_SELECT_PERSON_SUCCESS, index.getOneBased()),
                 commandResult.feedbackToUser);
 
-        JumpToListRequestEvent lastEvent = (JumpToListRequestEvent) eventCollector.getMostRecent();
+        JumpToListRequestEvent lastEvent = (JumpToListRequestEvent) eventsCollectorRule.eventsCollector.getMostRecent();
         assertEquals(index, Index.fromZeroBased(lastEvent.targetIndex));
-        assertTrue(eventCollector.getSize() == 1);
```
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/SelectCommandTest.java]: should we keep this check?

Comment (yamgent) [inline src/test/java/seedu/address/logic/commands/SelectCommandTest.java]: What is the rationale for removing this check?

File: src/test/java/seedu/address/ui/BrowserPanelTest.java [hunk 3]
```diff
@@ -44,6 +59,13 @@ public void display() throws Exception {
         post(selectionChangedEventStub);
         URL expectedPersonUrl = new URL(GOOGLE_SEARCH_URL_PREFIX
                 + ALICE.getName().fullName.replaceAll(" ", "+") + GOOGLE_SEARCH_URL_SUFFIX);
+
+        new GuiRobot().waitForEvent(() -> isUrlLoaded);
```
Comment (yamgent) [inline src/test/java/seedu/address/ui/BrowserPanelTest.java]: Will we not be using the `EventsCollectorRule` here?

File: src/test/java/guitests/guihandles/BrowserPanelHandle.java [hunk 4]
```diff
@@ -16,6 +22,15 @@
 
     public BrowserPanelHandle(Node browserPanelNode) {
         super(browserPanelNode);
+
+        // Posts WebViewLoadedEvent whenever a new page is loaded.
```
Comment (yamgent) [inline src/test/java/guitests/guihandles/BrowserPanelHandle.java]: Comments inside methods should not end in fullstop

File: src/test/java/seedu/address/logic/commands/SelectCommandTest.java (hunk 2 above)
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/SelectCommandTest.java]: That's because in 1 test method, we call this method multiple times i.e. size of `EventsCollector` increases from 1 to 2 to 3... 

So 1 way to fix this is by passing in the value of the size. But that's kinda weird too.

File: src/test/java/seedu/address/ui/BrowserPanelTest.java (hunk 3 above)
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/ui/BrowserPanelTest.java]: Didn't know how to do it when I submitted the current iteration. But thinking about it yup actually it can be done, thanks!

**Comment by CanIHasReview** [comment]
# v3

@Zhiyuan-Amos submitted v3 for review.

* [v3 1/7] [AddressBookGuiTest: Shift EventsCenter\#clearSubscribers\(\)](https://github.com/se-edu/addressbook-level4/pull/613/commits/c9eeff4cda88ff513d3e56763640bd15d0622db9)
* [v3 2/7] [Add EventsCollectorRule](https://github.com/se-edu/addressbook-level4/pull/613/commits/62de04adea4d5dcd2d065923156ca02b5a24a9a4)
* [v3 3/7] [Update tests to use EventsCollectorRule](https://github.com/se-edu/addressbook-level4/pull/613/commits/9615a54d6bc5178bafa7d151d1268d14c8ab0181)
* [v3 4/7] [Nest EventsCollector in EventsCollectorRule](https://github.com/se-edu/addressbook-level4/pull/613/commits/f6c7ee9c68900dacbeccd5a8b393519ea22dd313)
* [v3 5/7] [TypicalPersons: Update static constant to getter method](https://github.com/se-edu/addressbook-level4/pull/613/commits/587fe5296d66ea237c10ccf842ef7021144d5691)
* [v3 6/7] [BrowserPanel: Update string constants](https://github.com/se-edu/addressbook-level4/pull/613/commits/0a2533dc038d37a98eaac2b9eebbc948f37b604f)
* [v3 7/7] [BrowserPanelHandle: Post WebViewLoadedEvent when WebView is done loading](https://github.com/se-edu/addressbook-level4/pull/613/commits/4492ae125b86b3364b93e0b2330852cd647ea591)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/816f07f953e8855556176cc0b6f9ca8a13a7b0f7...4492ae125b86b3364b93e0b2330852cd647ea591)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/3b19115e8d8ae3da8111e6ef5f44ca6ede0d1494~1...3b19115e8d8ae3da8111e6ef5f44ca6ede0d1494))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/613/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
I will need this to be merged soon before I can submit other system tests PR.

That's because consecutive checks for `browserPanelHandle#isUrlChanged()` will fail as the `URL` may not have been loaded yet i.e. race condition. :P So for example, SelectCommandSystemTest will fail because the `URL` loads too slow :P

File: src/test/java/seedu/address/logic/commands/SelectCommandTest.java (hunk 2 above)
Comment (Zhiyuan-Amos) [inline src/test/java/seedu/address/logic/commands/SelectCommandTest.java]: There's other tests that use this check though. Like `ExitCommandTest`
