### PR TITLE
Move all parsing from AddCommand to AddCommandParser #306

### LINKED ISSUE #306: Move all parsing from AddCommand to AddCommandParser
`AddCommand` currently takes `Strings` in its constructor:
```java
    public AddCommand(String name, String phone, String email, String address, Set<String> tags)
            throws IllegalValueException {
```
Internally it would then parse these strings into their associated objects (`Name`, `Phone`, `Email` etc.)

Being in the `logic.commands` package, `AddCommand` should not be performing any parsing. `AddCommandParser` should be doing that instead.

### PR DESCRIPTION
**Pull request by MightyCupcakes**
Closes #306

Proposed merge commit message:

```
Parsing the add command string into a Person object
is split between the AddCommandParser and the AddCommand.

It is more cohesive if the said parsing is done entirely
by the AddCommandParser itself.

Let's modify the construction of add command as follows:
    * Add an explicit check for empty prefixes and remove the use of
      NoSuchElementException to detect missing prefixes.
    * Make AddCommandParser do the parsing and create a
      fully parsed Person object.
    * Make AddCommand's constructor accept a fully parsed
      ReadOnlyPerson.
```

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@MightyCupcakes submitted v1 for review.

* [v1 1/1] [Move AddCommand's parsing responsiblites to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/fa0919c1904c38dc697d5d2c9ccd0a2abc09437b)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...fa0919c1904c38dc697d5d2c9ccd0a2abc09437b))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by MightyCupcakes** [comment]
[v1 1/1] Typo in commit message `responsiblites` -> `responsibilities` 

`Let's modify the constructor AddCommand` -> `Let's modify the constructor of AddCommand`

This will be corrected in the next iteration

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -29,18 +28,9 @@
...
-    public AddCommand(String name, String phone, String email, String address, UniqueTagList tags)
-            throws IllegalValueException {
-        this.toAdd = new Person(
-                new Name(name),
-                new Phone(phone),
-                new Email(email),
-                new Address(address),
-                new UniqueTagList(tags)
-        );
+    public AddCommand(Name name, Phone phone, Email email, Address address, UniqueTagList tags) {
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: This can be avoided if `AddCommand` takes a `ReadOnlyPerson` directly.

**Comment by MightyCupcakes** [comment]
@PierceAndy any comments?

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 2]
```diff
@@ -29,18 +28,9 @@
...
+        this.toAdd = new Person(name, phone, email, address, new UniqueTagList(tags));
```
Comment (PierceAndy) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: The `this` keyword here is not necessary.

**Comment by PierceAndy** [comment]
[v1 1/1]:

> Let's modify the constructor AddCommand

How about this instead?

> Let's modify AddCommand's constructor

@MightyCupcakes Thanks for the mention, I must have missed this PR in my notifications.

**Comment by CanIHasReview** [comment]
# v2

@MightyCupcakes submitted v2 for review.

* [v2 1/1] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/0b0f64aabddc62af2b688d821a28c8bcf2074080)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...0b0f64aabddc62af2b688d821a28c8bcf2074080)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/e86a5a06732795b8174148da2140f57537c07b7f~1...e86a5a06732795b8174148da2140f57537c07b7f))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v3

@MightyCupcakes submitted v3 for review.

* [v3 1/1] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/20eefc3eb98bf903caf3231f69ba20ee2663d6ca)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...20eefc3eb98bf903caf3231f69ba20ee2663d6ca)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/1b9ae3877b19931a4173fe8c015b3fab72a60876~1...1b9ae3877b19931a4173fe8c015b3fab72a60876))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 3]
```diff
@@ -28,19 +22,10 @@
...
-    public AddCommand(String name, String phone, String email, String address, UniqueTagList tags)
-            throws IllegalValueException {
-        this.toAdd = new Person(
-                new Name(name),
-                new Phone(phone),
-                new Email(email),
-                new Address(address),
-                new UniqueTagList(tags)
-        );
+    public AddCommand(Person person) {
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: Quick comment: should be taking a `ReadOnlyPerson` (DIP and all that jazz)

Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: That is what I thought but Model#addPerson() expects a Person

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 4]
```diff
@@ -27,13 +33,15 @@ public Command parse(String args) {
...
-                    argsTokenizer.getValue(PREFIX_PHONE).get(),
-                    argsTokenizer.getValue(PREFIX_EMAIL).get(),
-                    argsTokenizer.getValue(PREFIX_ADDRESS).get(),
-                    ParserUtil.parseTags(argsTokenizer.getAllValues(PREFIX_TAG))
-            );
+            Address address = ParserUtil.parseAddress(argsTokenizer.getValue(PREFIX_ADDRESS)).get();
+            Email email = ParserUtil.parseEmail(argsTokenizer.getValue(PREFIX_EMAIL)).get();
+            Name name = new Name(argsTokenizer.getPreamble());
+            Phone phone = ParserUtil.parsePhone(argsTokenizer.getValue(PREFIX_PHONE)).get();
+            UniqueTagList tagList = ParserUtil.parseTags(argsTokenizer.getAllValues(PREFIX_TAG));
```
Comment (PierceAndy) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: To be consistent, rather than ordering alphabetically, the ordering of these variables should be similar to the order of the Prefix arguments taken by `new ArgumentTokenizer(...)` in line 33, and the arguments taken by `new Person(...)` in line 42.

**Comment by CanIHasReview** [comment]
# v4

@MightyCupcakes submitted v4 for review.

* [v4 1/1] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/7be9a8c0fe4a37bb7278e79c4488720f9023817d)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/297506b87fabe6de6baa7901388039ec50199802...7be9a8c0fe4a37bb7278e79c4488720f9023817d)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level4/compare/e2c447dc3a274a1ffa91a30b07c8572d6692ed45~1...e2c447dc3a274a1ffa91a30b07c8572d6692ed45))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 5]
```diff
@@ -27,18 +35,37 @@ public Command parse(String args) {
...
+            return new AddCommand(person);
         } catch (NoSuchElementException nsee) {
             return new IncorrectCommand(String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_USAGE));
         } catch (IllegalValueException ive) {
             return new IncorrectCommand(ive.getMessage());
         }
     }
 
+    /**
+     * Verifies that the given prefixes does not contain an empty {@code Optional} value.
```
Comment (PierceAndy) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: - `prefixes does not contain` -> `prefixes do not contain`
- `an empty {@code Optional} value` -> `empty {@code Optional} values`

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 6]
```diff
@@ -27,18 +35,37 @@ public Command parse(String args) {
...
+     *
+     * @throws NoSuchElementException if any of the prefix given has an empty Optional value
```
Comment (PierceAndy) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: `if any of the prefix given` -> `if any of the given prefixes`

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 7]
```diff
@@ -27,18 +35,37 @@ public Command parse(String args) {
...
         argsTokenizer.tokenize(args);
         try {
-            return new AddCommand(
-                    argsTokenizer.getPreamble(),
-                    argsTokenizer.getValue(PREFIX_PHONE).get(),
-                    argsTokenizer.getValue(PREFIX_EMAIL).get(),
-                    argsTokenizer.getValue(PREFIX_ADDRESS).get(),
-                    ParserUtil.parseTags(argsTokenizer.getAllValues(PREFIX_TAG))
-            );
+            checkCompulsoryPrefixPresent(argsTokenizer, PREFIX_ADDRESS, PREFIX_PHONE, PREFIX_EMAIL);
```
Comment (kychua) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Also, why do you check that address, phone, email are present but not name?

Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Does name have a prefix?

**Comment by damithc** [comment]
Commit message:

Tried to rephrase to avoid `proposed solution` (when the commit is merged, it is no longer just `proposed`). Also, trying to favor bullet points over paragraphs. Can consider this kind of phrasing if you feel it's easier to read.

```txt
Let's modify AddCommand construction as follows:
* Make AddCommandParser do the parsing and create a
  Person object.
* Make AddCommand's constructor accept a fully parsed
  ReadOnlyPerson.
* Make {who?} verify that all  prefixes exists in the given arguments 
  string to in order  to keep the behaviour of AddCommandParser 
  consistent.

Benefits:
* The parser will always tell the user of an invalid command
  format first before passing the values to the respective Person
  attributes objects for further input verification.
```

**Comment by CanIHasReview** [comment]
# v5

@MightyCupcakes submitted v5 for review.

* [v5 1/1] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/45a52363fcb26b7915dc799fe252db7394e1432a)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/297506b87fabe6de6baa7901388039ec50199802...45a52363fcb26b7915dc799fe252db7394e1432a)) ([:chart_with_upwards_trend: Interdiff between v4 and v5](https://github.com/se-edu/addressbook-level4/compare/87f60cc1c65ab38c62c851c72ed49f67119a0c52~1...87f60cc1c65ab38c62c851c72ed49f67119a0c52))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/5/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v6

@MightyCupcakes submitted v6 for review.

* [v6 1/1] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/68cfbb19d0add6129cb75f9af1e50986adfc8db7)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/297506b87fabe6de6baa7901388039ec50199802...68cfbb19d0add6129cb75f9af1e50986adfc8db7)) ([:chart_with_upwards_trend: Interdiff between v5 and v6](https://github.com/se-edu/addressbook-level4/compare/b0fb365b4ef4cff012b5579130faca88097f76d7~1...b0fb365b4ef4cff012b5579130faca88097f76d7))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/6/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 8]
```diff
@@ -25,29 +20,22 @@
...
+    public AddCommand(ReadOnlyPerson person) {
+        toAdd = person;
     }
 
     @Override
     public CommandResult execute() throws CommandException {
         assert model != null;
         try {
-            model.addPerson(toAdd);
+            assert toAdd instanceof Person;
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: It would be better to do this kind of check at the constructor to catch it early. At the same time, you can do the cast as well.

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 9]
```diff
@@ -25,29 +20,22 @@
...
-            throws IllegalValueException {
-        this.toAdd = new Person(
-                new Name(name),
-                new Phone(phone),
-                new Email(email),
-                new Address(address),
-                new UniqueTagList(tags)
-        );
+    public AddCommand(ReadOnlyPerson person) {
+        toAdd = person;
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: Need to defensively copy the person.

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 10]
```diff
@@ -27,18 +35,38 @@ public Command parse(String args) {
...
         try {
-            return new AddCommand(
-                    argsTokenizer.getPreamble(),
-                    argsTokenizer.getValue(PREFIX_PHONE).get(),
-                    argsTokenizer.getValue(PREFIX_EMAIL).get(),
-                    argsTokenizer.getValue(PREFIX_ADDRESS).get(),
-                    ParserUtil.parseTags(argsTokenizer.getAllValues(PREFIX_TAG))
-            );
+            if (!isCompulsoryPrefixesPresent(argsTokenizer, PREFIX_ADDRESS, PREFIX_PHONE, PREFIX_EMAIL)) {
+                throw new NoSuchElementException();
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: This is a... strange mix of using exceptions for flow control and not using exceptions for flow control.

If you want to use exceptions for flow control, the `get()` calls in the line belows will already throw the `NoSuchElementException`, so you don't need the `isCompulsoryPrefixesPresent()`.

On the other hand, if you don't want to use exceptions for flow control, then `NoSuchElementException` shouldn't be thrown.

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 11]
```diff
@@ -27,18 +35,38 @@ public Command parse(String args) {
...
         } catch (IllegalValueException ive) {
             return new IncorrectCommand(ive.getMessage());
         }
     }
 
+    /**
+     * Returns true if all the given prefixes do not contain empty {@code Optional} values in the given
+     * {@code ArgumentTokenizer}.
+     */
+    private boolean isCompulsoryPrefixesPresent(ArgumentTokenizer argsTokenizer, Prefix... compulsoryPrefixes) {
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Sounds like `arePrefixesPresent()` describes this method well enough -- whether these prefixes are compulsory or not depend on how the caller chooses to react to the resuit, this method shouldn't need to care about that.

File: src/main/java/seedu/address/logic/commands/AddCommand.java (hunk 8 above)
Comment (yamgent) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: Since we are defensively copying, perhaps `toAdd` should just be a `Person` instead? If we use the copy constructor `Person(ReadOnlyPerson)`, the cast doesn't seem to be necessary.

**Comment by CanIHasReview** [comment]
# v7

@MightyCupcakes submitted v7 for review.

* [v7 1/1] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/cbd1692d14a1aac7e3327dc7c546ece3e484fe54)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/297506b87fabe6de6baa7901388039ec50199802...cbd1692d14a1aac7e3327dc7c546ece3e484fe54)) ([:chart_with_upwards_trend: Interdiff between v6 and v7](https://github.com/se-edu/addressbook-level4/compare/30d8dc8ed0f230cdd1e2a5c8254dc881278559db~1...30d8dc8ed0f230cdd1e2a5c8254dc881278559db))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/7/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 12]
```diff
@@ -26,19 +34,40 @@ public Command parse(String args) {
...
         } catch (IllegalValueException ive) {
             return new IncorrectCommand(ive.getMessage());
         }
     }
 
+    /**
+     * Returns true if all the given prefixes do not contain empty {@code Optional} values in the given
+     * {@code ArgumentTokenizer}.
+     */
+    private boolean arePrefixesPresent(ArgumentTokenizer argsTokenizer, Prefix... compulsoryPrefixes) {
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Some more references to `compulsory` in the code...

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 13]
```diff
@@ -26,19 +34,40 @@ public Command parse(String args) {
...
+            Email email = ParserUtil.parseEmail(argsTokenizer.getValue(PREFIX_EMAIL)).get();
+            Address address = ParserUtil.parseAddress(argsTokenizer.getValue(PREFIX_ADDRESS)).get();
+            UniqueTagList tagList = ParserUtil.parseTags(argsTokenizer.getAllValues(PREFIX_TAG));
+
+            ReadOnlyPerson person = new Person(name, phone, email, address, tagList);
+
+            return new AddCommand(person);
         } catch (NoSuchElementException nsee) {
-            return new IncorrectCommand(String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_USAGE));
+            throw new AssertionError("Unreachable code: A check for empty optionals have been performed.");
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Do we really still need this?

**Comment by CanIHasReview** [comment]
# v8

@MightyCupcakes submitted v8 for review.

* [v8 1/1] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/a0a1797b4c28b8c5b0f0e183accfa5d1a822ab03)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/3ace38e7e981e3433ab1af9f0ce69afa6aa108e0...a0a1797b4c28b8c5b0f0e183accfa5d1a822ab03)) ([:chart_with_upwards_trend: Interdiff between v7 and v8](https://github.com/se-edu/addressbook-level4/compare/45d8247eb7ef2ae63d2677829def9065df30d7e3~1...45d8247eb7ef2ae63d2677829def9065df30d7e3))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/8/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 14]
```diff
@@ -26,19 +32,38 @@ public Command parse(String args) {
...
         } catch (IllegalValueException ive) {
             return new IncorrectCommand(ive.getMessage());
         }
     }
 
+    /**
+     * Returns true if all the given prefixes do not contain empty {@code Optional} values in the given
+     * {@code ArgumentTokenizer}.
+     */
+    private boolean arePrefixesPresent(ArgumentTokenizer argsTokenizer, Prefix... prefixes) {
```
Comment (pyokagan) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Since this is just a utility method that does not depend on object state, make this `static`?

**Comment by pyokagan** [comment]
So, after pondering about the overall "off"-ness of the commit message, I realized that the commit actually consists of two separate changes:

1. Modification of the constructor of `AddCommand`, which the commit focuses on, and

2. Ensure that the "invalid command format" error has a higher priority than the "invalid name/email/address/phone/tag format" error.

These should be split into separate commits.

By the way, (2) above is a behavioral change and I'm surprised that none of our tests failed. I guess the testing is lacking somewhere...

**Comment by MightyCupcakes** [comment]
Number 2 is not a behavioural change. Without it, some tests will fail because they pass in invalid `Person` attributes and expect an invalid command message. This is precisely because `AddCommandParser` will check for command format before passing it to `AddCommand`.

**Comment by pyokagan** [comment]
Ah okay, then I think you can split your commit as follows:

1. Remove the use of exceptions for control flow in `AddCommandParser`.

    This is where you can introduce your `arePrefixesPresent()`

2. Move AddCommand's parsing responsibilities to AddCommandParser

    You will then not need to mention anything about `arePrefixesPresent()` or "keeping the behavior consistent".

**Comment by CanIHasReview** [comment]
# v9

@MightyCupcakes submitted v9 for review.

* [v9 1/2] [Remove the use of exceptions for control flow in AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/c6aff41d2238cdc4703d00c340a16bb1b3899e58)
* [v9 2/2] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/17bc36a5490cdfc0bce85b7237606d51dd14dc34)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/1f784b06cd8055123a5aa5ad06da7a1a0382bffc...17bc36a5490cdfc0bce85b7237606d51dd14dc34)) ([:chart_with_upwards_trend: Interdiff between v8 and v9](https://github.com/se-edu/addressbook-level4/compare/bf792636ffd3e9f14ac0eb506f5f621f4ccfa504~1...bf792636ffd3e9f14ac0eb506f5f621f4ccfa504))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/9/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v10

@MightyCupcakes submitted v10 for review.

* [v10 1/2] [Remove the use of exceptions for control flow in AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/62629bd92972f1bf07d2a2d31c140d76405abcd6)
* [v10 2/2] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/ef6a021d52620b9969fde17d683014506d1ceb6a)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/4c4e1ed78fd8465512c5b434a3c592da52740717...ef6a021d52620b9969fde17d683014506d1ceb6a)) ([:chart_with_upwards_trend: Interdiff between v9 and v10](https://github.com/se-edu/addressbook-level4/compare/b46b6af0d293f4aa786aaeae51f1e3d587cd6964~1...b46b6af0d293f4aa786aaeae51f1e3d587cd6964))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/10/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 15]
```diff
@@ -34,11 +38,23 @@ public Command parse(String args) {
...
         } catch (IllegalValueException ive) {
             return new IncorrectCommand(ive.getMessage());
         }
     }
 
+    /**
+     * Returns true if all the given prefixes do not contain empty {@code Optional} values in the given
+     * {@code ArgumentTokenizer}.
+     */
+    private static boolean arePrefixesPresent(ArgumentTokenizer argsTokenizer, Prefix... prefixes) {
```
Comment (yamgent) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Should this be an `ArgumentTokenizer` method?

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 16]
```diff
@@ -34,11 +38,23 @@ public Command parse(String args) {
                     argsTokenizer.getValue(PREFIX_ADDRESS).get(),
                     ParserUtil.parseTags(argsTokenizer.getAllValues(PREFIX_TAG))
             );
-        } catch (NoSuchElementException nsee) {
-            return new IncorrectCommand(String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_USAGE));
```
Comment (yamgent) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: My only concern with this is that whenever a new field is added, they must remember to update the `arePrefixesPresent()` call to include the new field. Otherwise, if the user forget to input the new field, it is going to throw a `NoSuchElementException`, and this time no one is there to handle it. But that's probably out of the scope of this PR since it sounds like an issue with `ArgumentTokenizer` design...

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java (hunk 15 above)
Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: No.

ArgumentsTokenizer does not even contain the Map of prefixes anymore after #320 is merged.

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java (hunk 16 above)
Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: That is what tests are for.

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 17]
```diff
@@ -1,14 +1,9 @@
 package seedu.address.logic.commands;
```
Comment (damithc) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: Message of commit 2:

>AddCommand then parses the String attributes into their
respective objects (i.e. email, phone, address, tags) and creates a
new Person object.

`Email, Phone, ...`?

Perhaps something like this (I'm trying to give one strong reason
than list all reasons)?

```
Parsing the add command string into a Person object
is split between the AddCommandParser and the AddCommand.

It is more cohesive if the said parsing is done entirely 
by the AddCommandParser itself.
```
What do you think? Any important info missing?

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 18]
```diff
@@ -34,11 +38,23 @@ public Command parse(String args) {
...
+     * {@code ArgumentTokenizer}.
+     */
+    private static boolean arePrefixesPresent(ArgumentTokenizer argsTokenizer, Prefix... prefixes) {
+        for (Prefix prefix : prefixes) {
+            if (!argsTokenizer.getValue(prefix).isPresent()) {
+                return false;
+            }
+        }
+
+        return true;
```
Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Well, there is but it is required to wrap it first like so:

``` java

Stream<List<Prefix>> stream = Stream.of (prefixes);
// ...

````

Comment (damithc) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: I see. I'll leave you to decide which one to use. I have a feeling the stream version is more elegant but I could be wrong.

**Comment by CanIHasReview** [comment]
# v11

@MightyCupcakes submitted v11 for review.

* [v11 1/2] [Remove the use of exceptions for control flow in AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/5bfc23549aacd6d2f68c8d840f254d074382997b)
* [v11 2/2] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/f841c46f221c7e904e6bfebc1f72b01a9938b924)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/4c4e1ed78fd8465512c5b434a3c592da52740717...f841c46f221c7e904e6bfebc1f72b01a9938b924)) ([:chart_with_upwards_trend: Interdiff between v10 and v11](https://github.com/se-edu/addressbook-level4/compare/7f362d0a7c3c187fb53d22d7e7f4c6e7ce092722~1...7f362d0a7c3c187fb53d22d7e7f4c6e7ce092722))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/11/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v12

@MightyCupcakes submitted v12 for review.

* [v12 1/2] [Remove the use of exceptions for control flow in AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/0cc3c14829bf08ac389fb45bfd4a5a69ec02fc45)
* [v12 2/2] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/778d030506eb6a6764d905ccf968e58e50e21aff)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/e1eafd1145cb5fdcc81bbacecf9e5145903b3fe2...778d030506eb6a6764d905ccf968e58e50e21aff)) ([:chart_with_upwards_trend: Interdiff between v11 and v12](https://github.com/se-edu/addressbook-level4/compare/a042c5149d9391f946dffa758fa5a6d10faad4f8~1...a042c5149d9391f946dffa758fa5a6d10faad4f8))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/12/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 19]
```diff
@@ -6,12 +6,13 @@
 import static seedu.address.logic.parser.CliSyntax.PREFIX_PHONE;
 import static seedu.address.logic.parser.CliSyntax.PREFIX_TAG;
 
-import java.util.NoSuchElementException;
+import java.util.stream.Stream;
```
Comment (damithc) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Commit 1 message:
>ArgumentsTokenzier throws a NoSuchElementException if an attempt is
made to retrieve the value of a prefix that is not present or has an
empty value. AddCommandParser interprets that exception as
an invalid add command format.

Add this to the end?
```
The flow of this check is harder to understand because
it is embedded in a call to the AddCommand constructor
and spills over to a catch block.
```

>This is not a good design because the check for empty prefixes is not
made explicit. Furthermore, in preparation for the migration of
parsing responsibilities from AddCommand to AddCommandParser, the
verification of the command format should be performed first.

Consider this (I'm trying to limit the justification to just the readability issue):
```
The code is easier to understand if there is an explicit prefix 
check before calling the AddCommand constructor.
``` 

>Let's modify AddCommandParser as follows:
    * Make AddCommandParser#arePrefixesPresent(...) verify that
      all compulsory prefixes exist in the given arguments string first
      before passing the values to AddCommand
    * Remove the use of exceptions for command string format
      verification.

```
Let's add such an explicit check and remove the use of 
NoSuchElementException to detect missing prefixes.
```

**Comment by CanIHasReview** [comment]
# v13

@MightyCupcakes submitted v13 for review.

* [v13 1/2] [Remove the use of exceptions for control flow in AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/7812c8de0aeb14fa342ddff74210948bb7afe64b)
* [v13 2/2] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/1e078b20935223e5f95c7910c0f090a320635996)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/e1eafd1145cb5fdcc81bbacecf9e5145903b3fe2...1e078b20935223e5f95c7910c0f090a320635996)) ([:chart_with_upwards_trend: Interdiff between v12 and v13](https://github.com/se-edu/addressbook-level4/compare/793ec3be54809aebfd9e3b90375c111cfeaef568~1...793ec3be54809aebfd9e3b90375c111cfeaef568))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/13/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
@MightyCupcakes @yamgent can have another look as there were some changes after you approved. @pyokagan have a look if you have time.

**Comment by damithc** [comment]
@kychua you too can take another look because the PR has changed after you approved.

**Comment by damithc** [comment]
@MightyCupcakes this needs de-conflicting

**Comment by CanIHasReview** [comment]
# v14

@MightyCupcakes submitted v14 for review.

* [v14 1/2] [Remove the use of exceptions for control flow in AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/6fd7e489d6063a985472c278c3a9808d55c11a8d)
* [v14 2/2] [Move AddCommand's parsing responsibilities to AddCommandParser](https://github.com/se-edu/addressbook-level4/pull/315/commits/d79c47f6bf119284dfa67e9d3a96bc826a6619e1)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/49075017cc9b788001cbb8d4a410adec18dc8406...d79c47f6bf119284dfa67e9d3a96bc826a6619e1)) ([:chart_with_upwards_trend: Interdiff between v13 and v14](https://github.com/se-edu/addressbook-level4/compare/8b66f2ac84ff72673b4ac6196123973d7cee2686~1...8b66f2ac84ff72673b4ac6196123973d7cee2686))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/315/14/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by MightyCupcakes** [comment]
# v14

Rebased and resolved conflict

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 20]
```diff
@@ -25,6 +25,11 @@
     public Command parse(String args) {
         ArgumentMultimap argMultimap =
                 ArgumentTokenizer.tokenize(args, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ADDRESS, PREFIX_TAG);
+
+        if (!arePrefixesPresent(argMultimap, PREFIX_ADDRESS, PREFIX_PHONE, PREFIX_EMAIL)) {
```
Comment (kychua) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Doesn't this mean that when the user enters `add p/123 e/abc@gmail.com a/address`, they get the invalid name error even though it's technically a missing name (invalid format)?

Comment (MightyCupcakes) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: It is not possible for preamble to return an empty optional. This is asserted as such in the tests

Comment (kychua) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: I see, didn't realise it's impossible for preamble to be empty, so `add p/123 ...` is a valid format with an empty string as name. I'll see if I can make the error message clearer in `Name`.
