### PR TITLE
StringUtil#isUnsignedInteger(String): Fix unhandled NFE #436

### LINKED ISSUE #436: Unhandled NumberFormatException in StringUtil#isUnsignedInteger(String)
Running the command delete `12312432535323212321` results in
>Caused by: java.lang.NumberFormatException: For input string: "12312432535323212321"

This Exception is not handled by the method StringUtil#isUnsignedInteger(String).

Identified in #423

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #436

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/1] [StringUtil\#isUnsignedInteger\(String\): Fix unhandled NFE](https://github.com/se-edu/addressbook-level4/pull/460/commits/d68c91955b3e2307c88a34b8bc1d3f19982b6036)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/cfc8ecc72a73a989ecc58427e6ddd1c564361408...d68c91955b3e2307c88a34b8bc1d3f19982b6036))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/460/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -51,10 +53,18 @@ public static String getDetails(Throwable t) {
...
      * @param s Should be trimmed.
+     * @throws NullPointerException if {@code s} is null.
      */
     public static boolean isUnsignedInteger(String s) {
-        return s != null && s.matches("^0*[1-9]\\d*$");
+        requireNonNull(s);
+
+        try {
+            int value = Integer.parseInt(s);
+            return value > 0 && !s.startsWith("+"); // "+1" is successfully parsed by parseInt(String)
```
Comment (yamgent) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: `Integer#parseInt(String)`

File: src/test/java/seedu/address/commons/util/StringUtilTest.java [hunk 2]
```diff
@@ -43,6 +40,9 @@ public void isUnsignedPositiveInteger() {
         assertFalse(StringUtil.isUnsignedInteger(" 10 ")); // Leading/trailing spaces
         assertFalse(StringUtil.isUnsignedInteger("1 0"));  // Spaces in the middle
 
+        // EP: number larger than Integer.MAX_VALUE
+        assertFalse(StringUtil.isUnsignedInteger(String.valueOf(Integer.MAX_VALUE).concat(String.valueOf(0))));
```
Comment (yamgent) [inline src/test/java/seedu/address/commons/util/StringUtilTest.java]: Use `"9999999999999"` instead of `String.valueOf(Integer.MAX_VALUE).concat(String.valueOf(0))` (less brainpower required). But still leave the comment intact.

**Comment by CanIHasReview** [comment]
# v2

@Zhiyuan-Amos submitted v2 for review.

* [v2 1/1] [StringUtil\#isUnsignedInteger\(String\): Fix unhandled NFE](https://github.com/se-edu/addressbook-level4/pull/460/commits/1d2d33644ffacfbc819de21758e4379e3aca80e5)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/cfc8ecc72a73a989ecc58427e6ddd1c564361408...1d2d33644ffacfbc819de21758e4379e3aca80e5)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/e2798326ec2395838b630dc94d95a1867b72fd9d~1...e2798326ec2395838b630dc94d95a1867b72fd9d))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/460/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 3]
```diff
@@ -51,10 +53,18 @@ public static String getDetails(Throwable t) {
     /**
      * Returns true if s represents an unsigned integer e.g. 1, 2, 3, ... <br>
```
Comment (limmlingg) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: `{@code s}`

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 4]
```diff
@@ -51,10 +53,18 @@ public static String getDetails(Throwable t) {
...
      * Will return false if the string is:
```
Comment (limmlingg) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: ...`if {@code s} is`...

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 5]
```diff
@@ -51,10 +53,18 @@ public static String getDetails(Throwable t) {
...
-     * null, empty string, "-1", "0", "+1", and " 2 " (untrimmed) "3 0" (contains whitespace).
+     * empty string, "-1", "0", "+1", and " 2 " (untrimmed) "3 0" (contains whitespace).
      * @param s Should be trimmed.
```
Comment (Zhiyuan-Amos) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: remove param

**Comment by CanIHasReview** [comment]
# v3

@Zhiyuan-Amos submitted v3 for review.

* [v3 1/1] [StringUtil\#isUnsignedInteger\(String\): Fix unhandled NFE](https://github.com/se-edu/addressbook-level4/pull/460/commits/ca28d6550a52deb386844596697552fd192f1c39)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/cfc8ecc72a73a989ecc58427e6ddd1c564361408...ca28d6550a52deb386844596697552fd192f1c39)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/af1074ed40268635d9e1101a351f4e02bcab6137~1...af1074ed40268635d9e1101a351f4e02bcab6137))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/460/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 6]
```diff
@@ -1,5 +1,7 @@
 package seedu.address.commons.util;
```
Comment (damithc) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: Suggested commit message:

```
StringUtil#isUnsignedInteger(String) attempts to convert any given
number to an integer (as a step in checking if it is an unsigned integer).

When the input  is a number higher than Integer.MAX_VALUE, 
the method fails with an exception instead of returning false.

Let’s teach Util#isUnsignedInteger(String) to return false if the 
input number is higher than Integer.MAX_VALUE.
```

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 7]
```diff
@@ -49,12 +51,19 @@ public static String getDetails(Throwable t) {
     }
 
     /**
-     * Returns true if s represents an unsigned integer e.g. 1, 2, 3, ... <br>
-     * Will return false if the string is:
-     * null, empty string, "-1", "0", "+1", and " 2 " (untrimmed) "3 0" (contains whitespace).
-     * @param s Should be trimmed.
+     * Returns true if {@code s} represents an unsigned integer e.g. 1, 2, 3, ... <br>
```
Comment (damithc) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: `represents an unsigned integer e.g. 1, 2, 3, ...` -> `is an integer in the range 1, 2, 3, ..., Integer.MAX`?

File: src/main/java/seedu/address/commons/util/StringUtil.java [hunk 8]
```diff
@@ -49,12 +51,19 @@ public static String getDetails(Throwable t) {
...
+     * Will return false if {@code s} is:
+     * empty string, "-1", "0", "+1", and " 2 " (untrimmed) "3 0" (contains whitespace).
```
Comment (damithc) [inline src/main/java/seedu/address/commons/util/StringUtil.java]: `Will return false for any other non-null string input e.g. empty string, "-1", "0", "+1", and " 2 " (untrimmed), "3 0" (contains whitespace)`?

**Comment by CanIHasReview** [comment]
# v4

@Zhiyuan-Amos submitted v4 for review.

* [v4 1/1] [StringUtil\#isUnsignedInteger\(String\): Fix unhandled NFE](https://github.com/se-edu/addressbook-level4/pull/460/commits/ca28d6550a52deb386844596697552fd192f1c39)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/cfc8ecc72a73a989ecc58427e6ddd1c564361408...ca28d6550a52deb386844596697552fd192f1c39)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level4/compare/21c7f79ffed9e831a152cdc93b631503f64ba51f~1...21c7f79ffed9e831a152cdc93b631503f64ba51f))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/460/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
Sorry please ignore the above iteration; accidentally submitted it.

**Comment by CanIHasReview** [comment]
# v5

@Zhiyuan-Amos submitted v5 for review.

* [v5 1/1] [StringUtil\#isUnsignedInteger\(String\): Fix unhandled NFE](https://github.com/se-edu/addressbook-level4/pull/460/commits/eed5d986bc9f88afa7c34c223863a87e9e9ce1ae)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/cfc8ecc72a73a989ecc58427e6ddd1c564361408...eed5d986bc9f88afa7c34c223863a87e9e9ce1ae)) ([:chart_with_upwards_trend: Interdiff between v4 and v5](https://github.com/se-edu/addressbook-level4/compare/c2cc21e2d915ebef74c05d463b0cfe8b30901d2e~1...c2cc21e2d915ebef74c05d463b0cfe8b30901d2e))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/460/5/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

File: src/test/java/seedu/address/logic/parser/ParserUtilTest.java [hunk 9]
```diff
@@ -45,8 +46,9 @@ public void parseIndex_invalidInput_throwsIllegalValueException() throws Excepti
     }
 
     @Test
-    public void parseIndex_outOfRangeInput_throwsNumberFormatException() throws Exception {
-        thrown.expect(NumberFormatException.class);
+    public void parseIndex_outOfRangeInput_throwsIllegalValueException() throws Exception {
+        thrown.expect(IllegalValueException.class);
+        thrown.expectMessage(MESSAGE_INVALID_INDEX);
         ParserUtil.parseIndex("3423423423423432");
```
Comment (damithc) [inline src/test/java/seedu/address/logic/parser/ParserUtilTest.java]: Here as well?

File: src/test/java/seedu/address/commons/util/StringUtilTest.java [hunk 10]
```diff
@@ -43,6 +40,10 @@ public void isUnsignedPositiveInteger() {
         assertFalse(StringUtil.isUnsignedInteger(" 10 ")); // Leading/trailing spaces
         assertFalse(StringUtil.isUnsignedInteger("1 0"));  // Spaces in the middle
 
+        // EP: number larger than Integer.MAX_VALUE
+        Long value = new Long(Integer.MAX_VALUE + 1);
+        assertFalse(StringUtil.isUnsignedInteger(value.toString()));
+
```
Comment (damithc) [inline src/test/java/seedu/address/commons/util/StringUtilTest.java]: Is "001" accepted?

**Comment by CanIHasReview** [comment]
# v6

@Zhiyuan-Amos submitted v6 for review.

* [v6 1/1] [StringUtil\#isUnsignedInteger\(String\): Fix unhandled NFE](https://github.com/se-edu/addressbook-level4/pull/460/commits/a32c4a67df7d5809aa06d985c1e2c3ed41346a8b)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/cfc8ecc72a73a989ecc58427e6ddd1c564361408...a32c4a67df7d5809aa06d985c1e2c3ed41346a8b)) ([:chart_with_upwards_trend: Interdiff between v5 and v6](https://github.com/se-edu/addressbook-level4/compare/a6d9c7fbb0daffaeaa2fa2b7ef07f883ace00d7d~1...a6d9c7fbb0daffaeaa2fa2b7ef07f883ace00d7d))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/460/6/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
@yamgent last call :>

**Comment by CanIHasReview** [comment]
# v7

@Zhiyuan-Amos submitted v7 for review.

* [v7 1/1] [StringUtil\#isUnsignedInteger\(String\): Fix unhandled NFE](https://github.com/se-edu/addressbook-level4/pull/460/commits/4f492f4eb8e19f6a42a3e23d77c37be43f998c6e)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/2f5b10f106c34d815c23f7d029920f166ffd4c51...4f492f4eb8e19f6a42a3e23d77c37be43f998c6e)) ([:chart_with_upwards_trend: Interdiff between v6 and v7](https://github.com/se-edu/addressbook-level4/compare/fea5ab8f95a1346998b856301f115237735d0762~1...fea5ab8f95a1346998b856301f115237735d0762))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/460/7/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>
