### PR TITLE
SampleDataTest: Fix buggy implementation of getDataFileLocation() #678

### LINKED ISSUE #678: SampleDataTest: Fix buggy implementation of getDataFileLocation()
getDataFileLocation() must return a non-existent file location as part
of this method's post-condition.

However, this isn't ensured in the current implementation. As a result,
the test case in SampleDataTest may fail.

Let's update getDataFileLocation() to ensure that it returns a 
non-existent file location.

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #678

### CODE REVIEW

File: src/test/java/guitests/SampleDataTest.java [hunk 1]
```diff
@@ -19,7 +23,21 @@ protected AddressBook getInitialData() {
...
-        return TestUtil.getFilePathInSandboxFolder("SomeFileThatDoesNotExist1234567890.xml");
+        String filePath = TestUtil.getFilePathInSandboxFolder("SomeFileThatDoesNotExist1234567890.xml");
+        deleteFileIfExists(filePath);
+        return filePath;
+    }
+
+    /**
+     * Deletes the file at {@code filePath} if it exists.
+     */
+    private void deleteFileIfExists(String filePath) {
```
Comment (Zhiyuan-Amos) [inline src/test/java/guitests/SampleDataTest.java]: Thought of placing this method in `FileUtil`, but `FileUtil` is a class that's used by the main code base. As such, I left this method here instead.

File: src/test/java/guitests/SampleDataTest.java [hunk 2]
```diff
@@ -19,7 +23,21 @@ protected AddressBook getInitialData() {
...
+        File file = new File(filePath);
+        try {
+            Files.deleteIfExists(file.toPath());
```
Comment (pyokagan) [inline src/test/java/guitests/SampleDataTest.java]: Can use `Paths.get()`?

File: src/test/java/guitests/SampleDataTest.java [hunk 3]
```diff
@@ -19,7 +23,21 @@ protected AddressBook getInitialData() {
...
+        } catch (IOException ioe) {
+            throw new AssertionError();
```
Comment (pyokagan) [inline src/test/java/guitests/SampleDataTest.java]: `new AssertionError(ioe)` please.
